### ISSUE TITLE
Buddybuild SDK crash: No static method getNewDefaultConfig(Landroid/app/Application;)Lorg/acra/ACRAConfiguration

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1004]
Our build that we distribute via buddybuild crash constantly:

```
 E  FATAL EXCEPTION: main
 E  Process: org.mozilla.focus.beta, PID: 32493
 E  java.lang.NoSuchMethodError: No static method getNewDefaultConfig(Landroid/app/Application;)Lorg/acra/ACRAConfiguration; in class Lorg/acr
    a/ACRA; or its super classes (declaration of 'org.acra.ACRA' appears in /data/app/org.mozilla.focus.beta-eBP6hABJWfmXwQhT_CPGGw==/base.apk
    )
 E      at com.buddybuild.sdk.crashreports.CrashReports.attach(CrashReports.java:21)
 E      at com.buddybuild.sdk.BuddyBuild.setup(BuddyBuild.java:75)
 E      at org.mozilla.focus.FocusApplication.onCreate(FocusApplication.java:25)
 E      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
 E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
 E      at android.app.ActivityThread.-wrap1(Unknown Source:0)
 E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
 E      at android.os.Handler.dispatchMessage(Handler.java:105)
 E      at android.os.Looper.loop(Looper.java:164)
 E      at android.app.ActivityThread.main(ActivityThread.java:6541)
 E      at java.lang.reflect.Method.invoke(Native Method)
 E      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
 E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by pocmo** [comment]
This might be caused by Proguard taking away too much.

**Comment by pocmo** [comment]
I temporarily disabled feedback and crash reports - This fixed the issue for now.

On a branch I tried excluding ACRA from proguard but this didn't help.

**Comment by pocmo** [comment]
From buddybuild: "We've been able to identify the issue and are working on a fix to rectify the situation."

**Comment by pocmo** [comment]
The issue has been fixed by buddybuild. I enabled crash and feedback reporting again.
