### ISSUE TITLE
InfoActivity crashes with default locale (NullPointerException: Can't set default locale to NULL)

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1005]
BB shows this failure across all platform, when going to 'Your Rights' page.

java.lang.NullPointerException

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.focus.debug/org.mozilla.focus.activity.InfoActivity}: java.lang.NullPointerException: Can't set default locale to NULL
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThreadXH.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInitXMethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Can't set default locale to NULL
	at java.util.Locale.setDefault(Locale.java:976)
	at java.util.Locale.setDefault(Locale.java:937)
	at org.mozilla.focus.fragment.WebFragment.applyLocale(WebFragment.java:78)
	at org.mozilla.focus.fragment.InfoFragment.inflateLayout(InfoFragment.java:54)
	at org.mozilla.focus.fragment.WebFragment.onCreateView(WebFragment.java:55)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
	at android.support.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:544)
	at android.app.Activity.performStart(Activity.java:6696)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
	... 9 more

**Comment by pocmo** [comment]
@ekager Looks like a regression from #788 - We probably want to run this new code only if there's a custom locale set (e.g. language is set to non system default)?
