### ISSUE TITLE
UI tests failing on connected devices

### ISSUE THREAD

**Issue by n-jay** [mozilla-mobile/focus-android#1262]
When running the unit tests on connected a device instead of an emulator, all tests except 1 are failing while all permissions have been provided. 
![screenshot_2017-09-02-16-01-12](https://user-images.githubusercontent.com/24616975/29995646-f9bbda9a-900b-11e7-8d9c-e314633856a6.png)

I believe this is mainly due to the "localhost" URL not being recognized therefore the test logic cannot be executed properly.
It should be mentioned that the Gradle build and the app work perfectly fine, and only the unit tests fail in the connected device.

Device is a Huawei and runs Android 5.1.1

**Comment by n-jay** [comment]
After running unit tests on an emulator with Android 7.1.1 the BadURchechTest fails while all others pass.
The full stack is mentioned below.

`junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at org.mozilla.focus.activity.BadURLTest.BadURLcheckTest(BadURLTest.java:86)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:369)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)`

Note this is without any edits to the project with the default configuration as soon as I cloned the repo.

**Comment by npark-mozilla** [comment]
Ah yes, badurltest will fail on vanilla version of simulators, because it cannot redirect market:// url to google play store app. (Since simulators do not come with google play store app) The test was designed with buddybuild ci test in mind. We should make this clear in the comments of the test. Thanks!

**Comment by npark-mozilla** [comment]
Just to add, the badurltest will pass when connected to an actual device with google play store installed.

**Comment by n-jay** [comment]
Thanks for the update!
I'm still confused over whether if we are supposed to or not supposed to run the tests on connected **devices** and not _only_ emulated devices.
Since the wiki explains it as follows:

> 8. To run all tests in folder right click on the folder and select run. For individual tests you will do the same but right click on the specific test.

> 9. select your emulator or _your device connected via ADB_

**Comment by npark-mozilla** [comment]
@n-jay you're right the wiki was unclear on this - I have added explanation at the end.  Because tests are designed with our CI in mind, this one may fail when running it locally.

**Comment by n-jay** [comment]
@npark-mozilla I'm yet to test it again. Will update the issue thread accordingly and close issue if no further errors found

**Comment by n-jay** [comment]
@npark-mozilla I ran the UI tests on my Huawei device with Android 5.1.1 and got very different results this time around. 
For example; when all tests are run in sequence they all fail while earlier the BadURLTest was the only one that worked when all the tests were run.
![image](https://user-images.githubusercontent.com/24616975/30240065-c7502540-9586-11e7-9e31-93d58d0a8335.png)

When I proceeded to run the tests individually starting from the top this is what I came up with;

- Some tests when run individually turn up fine. Eg - BadURLTest, DownloadTest
- Some tests continue to fail even when ran them individually. Eg - TestCustomTabUI, ImageSelectTest
![image](https://user-images.githubusercontent.com/24616975/30240264-7490b0e6-958a-11e7-98a9-03d6a0a535e2.png)
- Some tests simply give the below error and refuse to run altogether.
![image](https://user-images.githubusercontent.com/24616975/30240279-b7a1291a-958a-11e7-836b-4c7b265e4712.png)

Afterwards, I ran the tests on the exact emulator I tried initially and 2 failed when the tests were run sequentially.
![image](https://user-images.githubusercontent.com/24616975/30240591-e120d1fe-9590-11e7-8545-6cfa8f559894.png)
After messing around with the storage permissions the ImageSelectTest and the LocalSessionStorageTest passed.

I'm working on running the tests in other devices as well to see if the tests are failing in my device is isolated.
Will update this thread accordingly. In the meantime is it relevant that this thread be kept open since the original issue is still unresolved: UI tests failing on connected devices.

**Comment by pocmo** [comment]
Note that it's not necessarily a goal of the Focus team to make those tests run on *all* available devices. Primarily those tests are meant to find and prevent regressions when running the tests in a controlled automation environment.
Of course they should run on the same emulator configuration everywhere and ideally be independent of other tests and the execution order.

**Comment by npark-mozilla** [comment]
@n-jay hmm, looking at your screen, it looks like it's either one of two things:
- the device was locked/unavailable when the test started (hence 'Client not ready yet' message)
- the device required initial access  permission to be set (this shows as a pop-up message that comes up only once) 

If you monitor what's showing up on the device screen when the tests are run, this might give you clues on what the problem would be.

**Comment by n-jay** [comment]
@pocmo understood; I'll take note of it. It was a misunderstanding on my behalf.
@npark-mozilla the access permissions were set as shown in the screenshot at the very top. And I've properly set the developer settings so that the screen does not deactivate once plugged in for charging. As per the suggestions provided, I will be more vigilant of any issues thrown here after :)

**Comment by n-jay** [comment]
@pocmo understood; I'll take note of it. It was a misunderstanding on my behalf.
@npark-mozilla the access permissions were set as shown in the screenshot at the very top. And I've properly set the developer settings so that the screen does not deactivate once plugged in for charging. As per the suggestions provided, I will be more vigilant of any issues thrown here after :)

**Comment by pocmo** [comment]
@npark-mozilla I wonder if we should document somewhere what our reference devices / "emulator configurations" are so that every engineer can reproduce the setting and write/debug tests.

**Comment by npark-mozilla** [comment]
@n-jay hmm, for some reason your device is not accepting test request properly - I wonder what it is.  For our UI Test setup, what we did is to use nexus (5x, 6p, pixel) devices with vanilla launcher to avoid proprietary software interfering with it.  @pocmo that's a good idea, I'll mention it in the test wiki.

**Comment by n-jay** [comment]
@npark-mozilla I might be very very wrong and this is just assumptions on my part, but I think it's the "localhost" URL that's causing the problem in the connected device.

**Comment by npark-mozilla** [comment]
@n-jay hmm, if localhost was an issue, it would fail while going to 'localhost' website most likely - not fail to initialize the test - if you change 'localhost' to some valid url, does it at least start every test?
