### ISSUE TITLE
ScreenGrabTest: takeScreenshotOfNotification(): junit.framework.AssertionFailedError

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1367]
This one fails very often when running the screenshot test for all locales:
```

[11:33:53]: ▸ org.mozilla.focus.activity.screenshots.ScreenGrabTest:
[11:33:53]: ▸ Error in screenGrabTest(org.mozilla.focus.activity.screenshots.ScreenGrabTest):
[11:33:53]: ▸ junit.framework.AssertionFailedError
[11:33:53]: ▸ at junit.framework.Assert.fail(Assert.java:48)
[11:33:53]: ▸ at junit.framework.Assert.assertTrue(Assert.java:20)
[11:33:53]: ▸ at junit.framework.Assert.assertTrue(Assert.java:27)
[11:33:53]: ▸ at org.mozilla.focus.activity.screenshots.ScreenGrabTest.takeScreenshotOfNotification(ScreenGrabTest.java:280)
[11:33:53]: ▸ at org.mozilla.focus.activity.screenshots.ScreenGrabTest.screenGrabTest(ScreenGrabTest.java:149)
[11:33:53]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[11:33:53]: ▸ at java.lang.reflect.Method.invoke(Method.java:372)
[11:33:53]: ▸ at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[11:33:53]: ▸ at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[11:33:53]: ▸ at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[11:33:53]: ▸ at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[11:33:53]: ▸ at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
```

**Comment by pocmo** [comment]
I added some code locally to take a screenshot when this assertion fails. With that we should be able to see what state the emulator is in at the time of the error.

**Comment by pocmo** [comment]
![no_notification_delete_item_1506083850548](https://user-images.githubusercontent.com/89638/30744788-f6059696-9fa3-11e7-8ff2-0ae6c09629b6.png)

^--- Looks like the notification is not expanded in this case.

**Comment by pocmo** [comment]
Both failures are related. If this one does not fail and the erase button is visible then closing the notification shade fails and the erase button in takeScreenshotOfEraseSnackbar() can't be found (#1368).

**Comment by pocmo** [comment]
This is now fixed. We were waiting for the English string. This failed after we added the assertion. We might have more areas where we wait for an English string unnecessarily and slow down the test (but do not crash because there's no assertion).

**Comment by pocmo** [comment]
Nope, still happens.

**Comment by pocmo** [comment]
This one still happens :(
```

[13:43:13]: ▸ org.mozilla.focus.activity.screenshots.ScreenGrabTest:
[13:43:13]: ▸ Error in screenGrabTest(org.mozilla.focus.activity.screenshots.ScreenGrabTest):
[13:43:13]: ▸ junit.framework.AssertionFailedError
[13:43:13]: ▸ at junit.framework.Assert.fail(Assert.java:48)
[13:43:13]: ▸ at junit.framework.Assert.assertTrue(Assert.java:20)
[13:43:13]: ▸ at junit.framework.Assert.assertTrue(Assert.java:27)
[13:43:13]: ▸ at org.mozilla.focus.activity.screenshots.ScreenGrabTest.takeScreenshotOfNotification(ScreenGrabTest.java:316)
[13:43:13]: ▸ at org.mozilla.focus.activity.screenshots.ScreenGrabTest.screenGrabTest(ScreenGrabTest.java:155)
[13:43:13]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[13:43:13]: ▸ at java.lang.reflect.Method.invoke(Method.java:372)
[13:43:13]: ▸ at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[13:43:13]: ▸ at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[13:43:13]: ▸ at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

```

**Comment by mcomella** [comment]
@npark-mozilla Please add `help-wanted` if a contributor could help us out here! :)

**Comment by npark-mozilla** [comment]
One thing I noted was that in above screenshot, Focus was the only notification, but it wasn't expanded. (and it's probably not timing)  In a normal scenario, that wouldn't normally happen, would it?

**Comment by pocmo** [comment]
> In a normal scenario, that wouldn't normally happen, would it?

Yeah, that super strange and I have never seen that.

**Comment by npark-mozilla** [comment]
I actually noticed this on the *older* android api when I ran the test locally.  I was still able to expand it by sliding down on the text, but not with the current script, because its step value was too small. when I changed the step value to 20 from current value of 5, it seemed to swipe down and showed open menu. (https://github.com/mozilla-mobile/focus-android/blob/master/app/src/androidTest/java/org/mozilla/focus/activity/screenshots/NotificationScreenshots.java#L97)
@pocmo when you have time, could you try this in TC?

**Comment by Sdaswani** [comment]
Moving this out of 4.0, doesn't need to be fixed by tomorrow.

**Comment by bbinto** [comment]
Re-surfacing for triage after 4.1 and 4.2 will be skipped > 5.0!
