### ISSUE TITLE
a2po import fails: expected only letters, got u'bn-bd'

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#137]
I can't import translations from the l10n repository with a2po:

`Traceback (most recent call last):
  File "/usr/local/bin/a2po", line 11, in <module>
    load_entry_point('android2po==1.5.0', 'console_scripts', 'a2po')()
  File "/usr/local/lib/python2.7/site-packages/android2po-1.5.0-py2.7.egg/android2po/program.py", line 227, in run
    sys.exit(main(sys.argv) or 0)
  File "/usr/local/lib/python2.7/site-packages/android2po-1.5.0-py2.7.egg/android2po/program.py", line 215, in main
    command_result = cmd.execute()
  File "/usr/local/lib/python2.7/site-packages/android2po-1.5.0-py2.7.egg/android2po/commands.py", line 597, in execute
    for language in list_languages('gettext', self.env, self.w):
  File "/usr/local/lib/python2.7/site-packages/android2po-1.5.0-py2.7.egg/android2po/commands.py", line 116, in list_languages
    'get_gettext_languages' if source=='gettext' else 'get_android_languages')()
  File "/usr/local/lib/python2.7/site-packages/android2po-1.5.0-py2.7.egg/android2po/env.py", line 519, in get_gettext_languages
    language = resolve_locale(code, self)
  File "/usr/local/lib/python2.7/site-packages/android2po-1.5.0-py2.7.egg/android2po/env.py", line 122, in resolve_locale
    return Language(code, env)
  File "/usr/local/lib/python2.7/site-packages/android2po-1.5.0-py2.7.egg/android2po/env.py", line 59, in __init__
    self.locale = Locale.parse(code) if code else None
  File "/usr/local/lib/python2.7/site-packages/Babel-2.3.4-py2.7.egg/babel/core.py", line 270, in parse
    parts = parse_locale(identifier, sep=sep)
  File "/usr/local/lib/python2.7/site-packages/Babel-2.3.4-py2.7.egg/babel/core.py", line 1096, in parse_locale
    raise ValueError('expected only letters, got %r' % lang)
ValueError: expected only letters, got u'bn-bd'`

**Comment by pocmo** [comment]
The problem is that a2po uses Locale.parse() from the babel module:
http://babel.pocoo.org/en/latest/api/core.html

By default it does not recognize locales in the format 'de-DE' (It expects de_DE). It can be fixed quite easily here: https://github.com/miracle2k/android2po/blob/master/android2po/env.py#L59

Instead of:
`self.locale = Locale.parse(code) if code else None`
specify the separator and use:
`self.locale = Locale.parse(code, sep='-') if code else None`

**Comment by pocmo** [comment]
There's another part of the script I had to fix in order to support exporting new strings to existing locales. It doesn't seem to be straight-forward to get those changes into upstream without breaking the process for others. In the worst case we could keep a fork of a2po in our repository.
