### ISSUE TITLE
OnWebView() call in ScreenGrabTest times out intermittently

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/focus-android#1415]
On average about once per 60 run, this (https://github.com/mozilla-mobile/focus-android/blob/master/app/src/androidTest/java/org/mozilla/focus/activity/screenshots/ScreenGrabTest.java#L492) call will time out with below error after repeated calls in a loop.  This is different from element not being found, it seems to me it's waiting for the lock to be freed.  Looking at the video, the elements are present as well.

This does not seem to happen with .waitForExists call. is there a proper way to fix it, or should we go back to .waitForExists for all APIs? @pocmo, thoughts?

java.lang.RuntimeException: java.util.concurrent.TimeoutException: Waited 10 seconds for android.support.test.espresso.core.internal.deps.guava.util.concurrent.AbstractTransformFutureXTransformFuture@982ad95[status=PENDING, info=[inputFuture=[android.support.test.espresso.core.internal.deps.guava.util.concurrent.SettableFuture@3c57eaa[status=PENDING]], function=[android.support.test.espresso.web.action.AtomActionX3@92aea9b]]]
	at android.support.test.espresso.web.sugar.WebXWebInteractionXExceptionPropagator.<init>(Web.java:326)
	at android.support.test.espresso.web.sugar.WebXWebInteraction.doEval(Web.java:298)
	at android.support.test.espresso.web.sugar.WebXWebInteraction.withElement(Web.java:208)
	at org.mozilla.focus.activity.screenshots.ScreenGrabTest.takeScreenshotOfErrorPages(ScreenGrabTest.java:493)
	at org.mozilla.focus.activity.screenshots.ScreenGrabTest.screenGrabTest(ScreenGrabTest.java:168)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethodX1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at android.support.test.rule.ActivityTestRuleXActivityStatement.evaluate(ActivityTestRule.java:433)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunnerX3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunnerX1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.accessX000(ParentRunner.java:58)
	at org.junit.runners.ParentRunnerX2.evaluate(ParentRunner.java:268)
	at tools.fastlane.screengrab.locale.LocaleTestRuleX1.evaluate(LocaleTestRule.java:32)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunnerX3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunnerX1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.accessX000(ParentRunner.java:58)
	at org.junit.runners.ParentRunnerX2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
	at android.app.InstrumentationXInstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.util.concurrent.TimeoutException: Waited 10 seconds for android.support.test.espresso.core.internal.deps.guava.util.concurrent.AbstractTransformFutureXTransformFuture@982ad95[status=PENDING, info=[inputFuture=[android.support.test.espresso.core.internal.deps.guava.util.concurrent.SettableFuture@3c57eaa[status=PENDING]], function=[android.support.test.espresso.web.action.AtomActionX3@92aea9b]]]
	at android.support.test.espresso.core.internal.deps.guava.util.concurrent.AbstractFuture.get(AbstractFuture.java:458)
	at android.support.test.espresso.core.internal.deps.guava.util.concurrent.AbstractFutureXTrustedFuture.get(AbstractFuture.java:92)
	at android.support.test.espresso.web.action.AtomAction.get(AtomAction.java:194)
	at android.support.test.espresso.web.sugar.WebXWebInteraction.doEval(Web.java:287)
	... 34 more

**Comment by mcomella** [comment]
@npark-mozilla Please add the `help-wanted` label if you think a contributor could help us out here! :)
