### ISSUE TITLE
'lo' Locale causes app to crash when entering URL

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#156]
With Laotian locale 'lo', fastlane/screengrab test fails with following error when inputing URL in the search bar.  The placeholder for this locale may be broken

[18:04:28]: ▸ org.mozilla.focus.activity.ScreenGrabTest:
[18:04:28]: ▸ Error in screenGrabTest(org.mozilla.focus.activity.ScreenGrabTest):
[18:04:28]: ▸ java.util.UnknownFormatConversionException: Conversion: @
[18:04:28]: ▸ at java.util.Formatter$FormatToken.unknownFormatConversionException(Formatter.java:1399)
[18:04:28]: ▸ at java.util.Formatter$FormatToken.checkFlags(Formatter.java:1336)
[18:04:28]: ▸ at java.util.Formatter.transform(Formatter.java:1442)
[18:04:28]: ▸ at java.util.Formatter.doFormat(Formatter.java:1081)
[18:04:28]: ▸ at java.util.Formatter.format(Formatter.java:1042)
[18:04:28]: ▸ at java.util.Formatter.format(Formatter.java:1011)
[18:04:28]: ▸ at java.lang.String.format(String.java:1554)
[18:04:28]: ▸ at android.content.res.Resources.getString(Resources.java:437)
[18:04:28]: ▸ at android.support.v4.app.Fragment.getString(Fragment.java:681)
[18:04:28]: ▸ at org.mozilla.focus.fragment.UrlInputFragment.afterTextChanged(UrlInputFragment.java:168)
[18:04:28]: ▸ at android.widget.TextView.sendAfterTextChanged(TextView.java:8017)
[18:04:28]: ▸ at android.widget.TextView.setText(TextView.java:4363)
[18:04:28]: ▸ at android.widget.TextView.setText(TextView.java:4211)
[18:04:28]: ▸ at android.widget.EditText.setText(EditText.java:84)
[18:04:28]: ▸ at org.mozilla.focus.widget.InlineAutocompleteEditText.setText(InlineAutocompleteEditText.java:133)
[18:04:28]: ▸ at android.widget.TextView.setText(TextView.java:4186)
[18:04:28]: ▸ at android.support.test.espresso.action.ReplaceTextAction.perform(ReplaceTextAction.java:51)
[18:04:28]: ▸ at android.support.test.espresso.ViewInteraction$1.run(ViewInteraction.java:144)
[18:04:28]: ▸ at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
[18:04:28]: ▸ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
[18:04:28]: ▸ at android.os.Handler.handleCallback(Handler.java:739)
[18:04:28]: ▸ at android.os.Handler.dispatchMessage(Handler.java:95)
[18:04:28]: ▸ at android.os.Looper.loop(Looper.java:224)
[18:04:28]: ▸ at android.app.ActivityThread.main(ActivityThread.java:5526)
[18:04:28]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[18:04:28]: ▸ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[18:04:28]: ▸ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[18:04:29]: ▸ Time: 7,214

**Comment by pocmo** [comment]
Fixed by flod in l10n repository:
https://github.com/mozilla-l10n/focus-android-l10n/commit/f846b7f12cbb1e58e582fba5e4bb0be617bd4da5

I'll close this bug after doing a fresh import.

**Comment by npark-mozilla** [comment]
It works fine now!

**Comment by pocmo** [comment]
Thanks!
