### ISSUE TITLE
Crash when exiting BrowserFragment during load

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#171]
Our accessibility code crashes if you exit BrowserFragment while a page is loading
STR:
1) find a slow network
2) open focus, enter a URL, press enter
3) once the browser is visible (but before loading has completed), press back

`03-07 12:15:17.223 25749-25749/org.mozilla.focus.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.mozilla.focus.debug, PID: 25749
                                                                         java.lang.IllegalStateException: Fragment BrowserFragment{597438e} not attached to Activity
                                                                             at android.support.v4.app.Fragment.getResources(Fragment.java:646)
                                                                             at android.support.v4.app.Fragment.getString(Fragment.java:668)
                                                                             at org.mozilla.focus.fragment.BrowserFragment$1.onPageFinished(BrowserFragment.java:101)
                                                                             at org.mozilla.focus.web.WebViewProvider$WebkitView$1.onPageFinished(WebViewProvider.java:128)
                                                                             at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:545)
                                                                             at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:201)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by ahunt** [comment]
Hopefully this is a bit more readable:
https://gist.github.com/ahunt/f1896a5bea9e4842bbfda5ee7ff2dd11
