### ISSUE TITLE
NullPointerException when accessing default search engine.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#1819]
We saw this crash happen in a UI test. It looks like a valid crash that could happen for users too.

We recently started to reload search engines and set the list to null now (I wonder why). Depending on the timing this might trigger this crash. We either need to synchronize some access or even better never set the list to null.

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at org.mozilla.focus.search.SearchEngineManager.getDefaultSearchEngine(SearchEngineManager.java:288)
	at org.mozilla.focus.search.SearchEngineListPreference.refreshSearchEngineViews(SearchEngineListPreference.java:68)
	at org.mozilla.focus.search.SearchEngineListPreference.refetchSearchEngines(SearchEngineListPreference.java:57)
	at org.mozilla.focus.settings.SettingsFragment.refetchSearchEngines(SettingsFragment.java:216)
	at org.mozilla.focus.settings.SettingsFragment.onResume(SettingsFragment.java:204)
	at android.app.Fragment.performResume(Fragment.java:2657)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1319)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1549)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1611)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2204)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
	at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:867)
	at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:811)
	at android.app.Activity.onBackPressed(Activity.java:2993)
	at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:175)
```

**Comment by npark-mozilla** [comment]
This also happens when deleting two or more search engines, and closing the dialog.

**Comment by liuche** [comment]
Okay, I set `searchEngines` to null when we need to refetch, in order to force a wait while the search engines reload, but it looks like we need an extra lock so we can't set `searchEngines` to `null` after the `awaitLoadingSearchEnginesLocked` check.
