### ISSUE TITLE
Focus crashes when switching tabs

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#1996]
Device: Pixel 2
STR:

Open 4+ tabs.  Do it fast so the new tab is created before the parent page is fully loaded.  (e.g. www.thestar.com)
switch between tabs.  Switch to another tab before the site is fully loaded.
Expected:
Switches fine
Actual:
Crashes.

adb logcat shows following:
12-13 11:28:12.623 18337 18489 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
12-13 11:28:12.623 18337 18489 W System.err: 	at org.mozilla.focus.utils.UrlUtils.urlsMatchExceptForTrailingSlash(UrlUtils.java:108)
12-13 11:28:12.623 18337 18489 W System.err: 	at org.mozilla.focus.webview.FocusWebViewClient.shouldInterceptRequest(FocusWebViewClient.java:124)
12-13 11:28:12.623 18337 18489 W System.err: 	at com.android.webview.chromium.Ap.shouldInterceptRequest(WebViewContentsClientAdapter.java:54)
12-13 11:28:12.623 18337 18489 W System.err: 	at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:9)
12-13 11:28:12.623 18337 18489 W System.err: 	at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:11)
12-13 11:28:12.624 18337 18489 F chromium: [FATAL:jni_android.cc(243)] Please include Java exception stack in crash report
12-13 11:28:12.636 18337 18337 D GeckoLocales: No selected locale. No correction needed.
12-13 11:28:12.638 18337 18337 W Notification: Use of stream types is deprecated for operations other than volume control
12-13 11:28:12.638 18337 18337 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case

**Comment by npark-mozilla** [comment]
@liuche FYI

BTW, this shows up on 2.5

**Comment by npark-mozilla** [comment]
Hmm, it looks like the crash is still there, here's the logcat:

12-13 14:48:33.160   757  2908 D audio_hw_primary: out_write: retry previous failed cal level set
12-13 14:48:34.527 27016 27433 W System.err: java.lang.NullPointerException: uriString
12-13 14:48:34.531 27016 27433 W System.err: 	at android.net.Uri$StringUri.<init>(Uri.java:476)
12-13 14:48:34.531 27016 27433 W System.err: 	at android.net.Uri$StringUri.<init>(Unknown Source:0)
12-13 14:48:34.531 27016 27433 W System.err: 	at android.net.Uri.parse(Uri.java:438)
12-13 14:48:34.531 27016 27433 W System.err: 	at org.mozilla.focus.webview.TrackingProtectionWebViewClient.shouldInterceptRequest(TrackingProtectionWebViewClient.java:106)
12-13 14:48:34.531 27016 27433 W System.err: 	at org.mozilla.focus.webview.FocusWebViewClient.shouldInterceptRequest(FocusWebViewClient.java:141)
12-13 14:48:34.531 27016 27433 W System.err: 	at com.android.webview.chromium.Ap.shouldInterceptRequest(WebViewContentsClientAdapter.java:54)
12-13 14:48:34.531 27016 27433 W System.err: 	at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:9)
12-13 14:48:34.531 27016 27433 W System.err: 	at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:11)
12-13 14:48:34.532 27016 27433 F chromium: [FATAL:jni_android.cc(243)] Please include Java exception stack in crash report
12-13 14:48:34.542 27016 27016 D GeckoLocales: No selected locale. No correction needed.
12-13 14:48:34.545 27016 27016 W Notification: Use of stream types is deprecated for operations other than volume control
12-13 14:48:34.545 27016 27016 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
12-13 14:48:34.569 27504 27433 F

**Comment by npark-mozilla** [comment]
fix looks good now
