### ISSUE TITLE
Klar+Gecko: Crash when opening a drop-down menu

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#2225]
Build: Klar+GeckoView 4.0
Devices:
HTC Desire 820 (Android 6.0.1)
Samsung Galaxy S8 (Android 7.0)
Google Pixel (Android 8.0)

STR:
Go to wikipedia.com and tap the language menu in the search toolbar.

Expected result: A combo box opens.

Actual result: Klar crashes. See log attached.
[dropdown logcat.txt](https://github.com/mozilla-mobile/focus-android/files/1781037/dropdown.logcat.txt)

**Comment by pocmo** [comment]
```
03-05 15:50:52.824 27468-27468/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.mozilla.klar.gecko.beta, PID: 27468
                                                   java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
                                                       at org.mozilla.gecko.util.GeckoBundle.getBoolean(GeckoBundle.java:131)
                                                       at org.mozilla.gecko.util.GeckoBundle.getBoolean(GeckoBundle.java:142)
                                                       at org.mozilla.geckoview.GeckoSession$PromptDelegate$Choice.<init>(GeckoSession.java:1731)
                                                       at org.mozilla.geckoview.GeckoSession.handlePromptEvent(GeckoSession.java:1113)
                                                       at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:449)
                                                       at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:341)
                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:180)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6944)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
03-05 15:50:52.824 27468-27468/? E/GeckoCrashHandler: >>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 2 ("main")
                                                      java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
                                                          at org.mozilla.gecko.util.GeckoBundle.getBoolean(GeckoBundle.java:131)
                                                          at org.mozilla.gecko.util.GeckoBundle.getBoolean(GeckoBundle.java:142)
                                                          at org.mozilla.geckoview.GeckoSession$PromptDelegate$Choice.<init>(GeckoSession.java:1731)
                                                          at org.mozilla.geckoview.GeckoSession.handlePromptEvent(GeckoSession.java:1113)
                                                          at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:449)
                                                          at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:341)
                                                          at android.os.Handler.handleCallback(Handler.java:789)
                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                          at android.os.Looper.loop(Looper.java:180)
                                                          at android.app.ActivityThread.main(ActivityThread.java:6944)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
03-05 15:50:52.842 27468-27468/? W/google-breakpad: ExceptionHandler::GenerateDump cloned child 
```

**Comment by ekager** [comment]
Can't reproduce the crash, but I can't select a new language from the drop down menu.

**Comment by sv-ohorvath** [comment]
I confirm that the crash doesn't reproduce anymore on my devices either, with one exception: a Samsung Galaxy Note 4 (Android 5.0.1). Logcat attached.
[Note 4 logcat.txt](https://github.com/mozilla-mobile/focus-android/files/1796164/Note.4.logcat.txt)

**Comment by ekager** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1446211

**Comment by sv-ohorvath** [comment]
Verified this is fixed following the initial STR on the Samsung Galaxy Note 4 too.
