### ISSUE TITLE
DeleteWebViewDataTest fails intermittently, not finding the files it expect

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2230]
In some cases, deleteWebViewDataTest fails with:

java.lang.AssertionError: Expected file 'files' to be in the app's data dir whitelist
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.mozilla.focus.privacy.WebViewDataTest.DeleteWebViewDataTest(WebViewDataTest.java:239)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)

On second look, it doesn't look like firebase is randomizing the test order, but it usually fails when other tests are failing.  see here for more detail: https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6780175006496742457/executions/bs.b9b39f93c75551a9/test-cases

**Comment by pocmo** [comment]
Was finally able to reproduce this on the same Nexus 5X, API 23 configuration that Firebase Test Lab uses.

Some of the things the other tests do lead to an empty "files" directory to be created. Adding this to our whitelist should be enough here.
