### ISSUE TITLE
PageVisitTest intermittently fails with: Error performing 'single click - At Coordinates: 751, 170 and precision: 16, 16' on view 'with id: org.mozilla.focus.debug:id/whats_new'.

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2231]
It appears that this is timing related. Looking at the video, the menu item might be getting tapped too early.  Also, what's new page seems to be failing to load

android.support.test.espresso.PerformException: Error performing 'single click - At Coordinates: 751, 170 and precision: 16, 16' on view 'with id: org.mozilla.focus.debug:id/whats_new'.
	at android.support.test.espresso.PerformException$Builder.build(PerformException.java:84)
	at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:81)
	at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:52)
	at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
	at android.support.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:167)
	at android.support.test.espresso.ViewInteraction.perform(ViewInteraction.java:110)
	at org.mozilla.focus.activity.PageVisitTest.clickMenuItem(PageVisitTest.java:127)
	at org.mozilla.focus.activity.PageVisitTest.visitPagesTest(PageVisitTest.java:84)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

**Comment by Sdaswani** [comment]
Not an issue.
