### ISSUE TITLE
UI Test fails on Custom Tab

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2280]
Looks like this failure might be related to the latest checkin:

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}: java.lang.IllegalArgumentException: This custom tab intent  has no ID assigned

FATAL EXCEPTION: main
Process: org.mozilla.focus.debug, PID: 6688
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity}: java.lang.IllegalArgumentException: This custom tab intent  has no ID assigned
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by pocmo** [comment]
Yes, this looks like it is caused by my refactoring. This test needs to be updated.
