### ISSUE TITLE
Klar geckoview crashes when restarting from Home screen

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2429]
SearchTermShortcutTest on Geckoview Klar crashes when the app is restarting after being minimized.

The crashstack on logcat is as follows:

04-05 12:43:35.914: D/AndroidRuntime(7256): Calling main entry com.android.commands.am.Am
04-05 12:43:35.916: I/ActivityManager(2160): START u0 {act=org.mozilla.gecko.reportCrash flg=0x10000000 cmp=org.mozilla.klar.gecko.debug/org.mozilla.gecko.CrashReporter (has extras)} from uid 10084 on display 0
04-05 12:43:35.916: D/AndroidRuntime(7256): Shutting down VM
04-05 12:43:35.888: I/main(7256): type=1400 audit(0.0:242): avc: denied { mounton } for path="/proc/cpuinfo" dev="proc" ino=4026531988 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_cpuinfo:s0 tclass=file permissive=1
04-05 12:43:36.181: I/WindowState(2160): WIN DEATH: Window{a64194 u0 org.mozilla.klar.gecko.debug/org.mozilla.focus.activity.MainActivity}
04-05 12:43:36.181: W/WindowManager(2160): Force-removing child win Window{5ce238e u0 SurfaceView} from container Window{a64194 u0 org.mozilla.klar.gecko.debug/org.mozilla.focus.activity.MainActivity}
04-05 12:43:36.181: D/GraphicsStats(2160): Buffer count: 4
04-05 12:43:36.182: W/WindowManager(2160): Attempted to remove non-existing token: android.os.Binder@67a0a28
04-05 12:43:36.182: I/Zygote(1849): Process 6025 exited cleanly (11)
04-05 12:43:36.182: W/WindowManager(2160): Failed looking up window
04-05 12:43:36.182: W/WindowManager(2160): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@fa737c4 does not exist
04-05 12:43:36.182: W/WindowManager(2160): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8743)
04-05 12:43:36.182: W/WindowManager(2160): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8734)
04-05 12:43:36.182: W/WindowManager(2160): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1209)
04-05 12:43:36.182: W/WindowManager(2160): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
04-05 12:43:36.182: I/WindowState(2160): WIN DEATH: null
04-05 12:43:36.186: I/ActivityManager(2160): Process org.mozilla.klar.gecko.debug (pid 6025) has died
04-05 12:43:36.186: D/ActivityManager(2160): cleanUpApplicationRecord -- 6025
04-05 12:43:36.186: W/ActivityManager(2160): Scheduling restart of crashed service org.mozilla.klar.gecko.debug/org.mozilla.focus.session.SessionNotificationService in 1000ms
04-05 12:43:36.186: W/ActivityManager(2160): Crash of app org.mozilla.klar.gecko.debug running instrumentation ComponentInfo{org.mozilla.klar.gecko.debug.test/android.support.test.runner.AndroidJUnitRunner}
04-05 12:43:36.187: D/AndroidRuntime(6003): Shutting down VM
04-05 12:43:36.187: I/ActivityManager(2160): Force stopping org.mozilla.klar.gecko.debug appid=10084 user=0: finished inst
04-05 12:43:36.188: I/ActivityManager(2160):   Force finishing activity ActivityRecord{be70c2a u0 org.mozilla.klar.gecko.debug/org.mozilla.focus.activity.MainActivity t4}

**Comment by bbinto** [comment]
@pocmo to confirm severity, effort etc.

**Comment by bbinto** [comment]
friendly ping, @pocmo :)
