### ISSUE TITLE
Clicking notification item to delete history crashes the app

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#2499]
### Steps to reproduce
Run systemBarHomeViewTest in TrashcanTest.java
- Open website
- Press home button to minimize the app
- pull down the notification item, and tap the 'delete browsing history' text

### Expected behavior
- Opens Focus, history deleted
```
java.lang.NullPointerException: Attempt to invoke direct method 'void org.mozilla.focus.session.VisibilityLifeCycleCallback.finishAndRemoveTaskIfInBackground()' on a null object reference
at org.mozilla.focus.session.VisibilityLifeCycleCallback.finishAndRemoveTaskIfInBackground(VisibilityLifeCycleCallback.java:28)
at org.mozilla.focus.session.SessionNotificationService.onStartCommand(SessionNotificationService.java:70)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3474)
at android.app.ActivityThread.-wrap20(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Actual behavior
- App crashes

### Device information
Both on sim and device

**Comment by ekager** [comment]
Found the problem and filed PR #2503
