### ISSUE TITLE
Sentry: RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#2901]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4326368/

```
RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6798)
    at java.lang.reflect.Method.invoke(Method.java)
...
(2 additional frame(s) were not displayed)

Context.startForegroundService() did not then call Service.startForeground()
```

This is one of the Focus top crshes, with 349 crashes from 86 users.

**Comment by colintheshots** [comment]
In general, this common exception occurs when a phone is being sluggish. Android gives the app five seconds to start the foreground service and it didn't happen in time. This could be strictly due to a slow phone with an old processor and less memory requiring frequent garbage collections. More likely, the issue is caused by ANRs, which can simply be more significant on some phones than others. This is likely related to other ANR issues already reported.

**Comment by pocmo** [comment]
This looks interesting and could be causing this:
https://issuetracker.google.com/issues/76112072

Not sure how to work around that though..

**Comment by pocmo** [comment]
With this being our top crash I assume this is not a P5 anymore (CC @Sdaswani @vesta0 @boek).

**Comment by pocmo** [comment]
![screenshot_2018-10-05 anrs crashes - firefox focus the privacy browser - google play console](https://user-images.githubusercontent.com/89638/46526163-c1abb600-c88d-11e8-935c-c5e2b5aee737.png)

Something in 7.0.x has definitely made this more likely to occur.

One guess is the "wait a bit for fretboard to update" workaround that blocks the UI thread and may lead to `onStartCommand` being called too late (CC @colintheshots)?

**Comment by pocmo** [comment]
> https://issuetracker.google.com/issues/76112072

Calling `stopService()` before the Service had time to get to `startForeground()` is definitely triggering this exception 🤔:

```
E  android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e8f676b u0 org.mozilla.focus.debug/org.mozilla.focus.session.SessionNotificationService}
E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
E      at android.os.Handler.dispatchMessage(Handler.java:106)
E      at android.os.Looper.loop(Looper.java:193)
E      at android.app.ActivityThread.main(ActivityThread.java:6669)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Reproducible with just:

```Kotlin
SessionNotificationService.start(context)
SessionNotificationService.stop(context)
```

**Comment by Sdaswani** [comment]
> One guess is the "wait a bit for fretboard to update" workaround that blocks the UI thread and may lead to onStartCommand being called too late (CC @colintheshots)?

I _thought_ all this code had been removed, but @boek can confirm.
