### ISSUE TITLE
Sentry: RuntimeException: Unable to resume activity {org.mozilla.focus/org.mozilla.focus.activity.MainActivity}: android.vi...

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#2903]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4422894/

```
NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x101045c a=-1}
    at android.content.res.Resources.loadDrawable(Resources.java:2068)
    at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
    at android.view.View.<init>(View.java:3554)
    at android.widget.ImageView.<init>(ImageView.java:123)
    at android.widget.ImageButton.<init>(ImageButton.java:87)
...
(43 additional frame(s) were not displayed)

InflateException: Binary XML file line #100: Error inflating class ImageButton
    at org.mozilla.focus.fragment.UrlInputFragment.onCreateView(UrlInputFragment.kt:168)
    at org.mozilla.focus.locale.LocaleAwareAppCompatActivity.onResume(LocaleAwareAppCompatActivity.java:99)
    at org.mozilla.focus.activity.MainActivity.onResume(MainActivity.java:124)
...
(31 additional frame(s) were not displayed)

RuntimeException: Unable to resume activity {org.mozilla.focus/org.mozilla.focus.activity.MainActivity}: android.view.InflateException: Binary XML file line #100: Error inflating class ImageButton
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2786)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2815)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2248)
    at android.app.ActivityThread.access$800(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
...
(8 additional frame(s) were not displayed)

Unable to resume activity {org.mozilla.focus/org.mozilla.focus.activity.MainActivity}: android.view.InflateException: Binary XML file line #100: Error inflating class ImageButton
```

This is one of the Focus top crashes, with 150 crashes from 49 users.

**Comment by ekager** [comment]
From looking through these crashers, it looks like they are all KitKat devices lower than our minimum target. Might be rooted devices not getting the APK from GP or possibly a cloned app that is still using our Sentry end? I'm not sure, but I recommend closing.

**Comment by ekager** [comment]
Closing see #3370 for followup about unsupported device crashes
