### ISSUE TITLE
IllegalAccessError: There's no active custom tab session with id 405ad8af-5c7d-4b23-bfab-455010f35bce

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/focus-android#2986]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4416121/

```
IllegalAccessError: There's no active custom tab session with id 405ad8af-5c7d-4b23-bfab-455010f35bce
    at org.mozilla.focus.session.SessionManager.getCustomTabSessionByCustomTabIdOrThrow(SessionManager.java:150)
    at org.mozilla.focus.activity.CustomTabActivity$customTabSession$2.invoke(CustomTabActivity.kt:19)
    at org.mozilla.focus.activity.CustomTabActivity$customTabSession$2.invoke(CustomTabActivity.kt:16)
    at org.mozilla.focus.activity.CustomTabActivity.getCustomTabSession
    at org.mozilla.focus.activity.CustomTabActivity.getCurrentSessionForActivity(CustomTabActivity.kt:46)
...
(35 additional frame(s) were not displayed)

There's no active custom tab session with id 405ad8af-5c7d-4b23-bfab-455010f35bce
```

**Comment by bbinto** [comment]
@pocmo - would you mind briefly looking at this and letting @boek if you have an idea how to fix this?

**Comment by pocmo** [comment]
Without STR hard to debug. How often does the crash happen? (I locked myself out of Sentry..)

**Comment by ekager** [comment]
Closing because of our session changes
