### ISSUE TITLE
App crashes when using app with no fingerprints setup

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3049]
## Steps to reproduce
- open app
- put in url, hit submit

### Device information

Sim (without biometric capabilities?)

**Comment by boek** [comment]
```
018-08-02 11:29:43.284 20804-20804/org.mozilla.focus.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.debug, PID: 20804
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:248)
        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi$AES.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:54)
        at javax.crypto.KeyGenerator.init(KeyGenerator.java:519)
        at javax.crypto.KeyGenerator.init(KeyGenerator.java:502)
        at org.mozilla.focus.biometrics.BiometricAuthenticationHandler.createKey(BiometricAuthenticationHandler.kt:78)
        at org.mozilla.focus.biometrics.BiometricAuthenticationHandler.<init>(BiometricAuthenticationHandler.kt:43)
        at org.mozilla.focus.fragment.BrowserFragment.onCreate(BrowserFragment.java:201)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
        at android.security.keystore.KeymasterUtils.addUserAuthArgs(KeymasterUtils.java:132)
        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:246)
        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi$AES.engineInit(AndroidKeyStoreKeyGeneratorSpi.java:54) 
        at javax.crypto.KeyGenerator.init(KeyGenerator.java:519) 
        at javax.crypto.KeyGenerator.init(KeyGenerator.java:502) 
        at org.mozilla.focus.biometrics.BiometricAuthenticationHandler.createKey(BiometricAuthenticationHandler.kt:78) 
        at org.mozilla.focus.biometrics.BiometricAuthenticationHandler.<init>(BiometricAuthenticationHandler.kt:43) 
        at org.mozilla.focus.fragment.BrowserFragment.onCreate(BrowserFragment.java:201) 
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2331) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386) 
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188) 
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071) 
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```
