### ISSUE TITLE
Focus Crashes with no Internet connection or Slow connections

### ISSUE THREAD

**Issue by Scripterr** [mozilla-mobile/focus-android#3167]
For this issue to replicate there should be no Internet connection at all or should be below 30kbps. 

## STR: 
1.open firefox focus. 
2. Enter keyword or site url and search.

### expected result: 
Displays _connection not available_ or _Failed to Connect_ dialogue . 

### actual result: 
Firefox focus crashes. 

### Device information 
Android version: 8.0.0
Focus version:7.0 (Build #322291208 🦎 62.0.20180813190114)

**Comment by colintheshots** [comment]
I'm seeing the same. The problem is with search suggestions, which seem to default to on. We'll get a fix out soon.

    Process: org.mozilla.focus, PID: 20727
    mozilla.components.browser.search.suggestions.SearchSuggestionClient$FetchException: There was a problem fetching suggestions
        at mozilla.components.browser.search.suggestions.SearchSuggestionClient.getSuggestions(SearchSuggestionClient.kt:47)
        at org.mozilla.focus.searchsuggestions.SearchSuggestionsFetcher.getSuggestions(SearchSuggestionsFetcher.kt:55)
        at org.mozilla.focus.searchsuggestions.SearchSuggestionsFetcher$1.doResume(SearchSuggestionsFetcher.kt:89)
