### ISSUE TITLE
Custom Tabs crash in Nightly

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/focus-android#3248]
## Steps to reproduce
1. Open custom tab with Nightly as your default browser

### Expected behavior
Focus opens

### Actual behavior
Focus crashes before opening

### Device information

* Android device: Pixel 2
* Focus version: Nightly

**Comment by ekager** [comment]
Looks like a regression from  #3225
 

> Process: org.mozilla.klar.debug, PID: 10154
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.mozilla.klar.debug/org.mozilla.focus.activity.CustomTabActivity}: kotlin.UninitializedPropertyAccessException: lateinit property customTabId has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property customTabId has not been initialized
        at org.mozilla.focus.activity.CustomTabActivity.access$getCustomTabId$p(CustomTabActivity.kt:16)
        at org.mozilla.focus.activity.CustomTabActivity$customTabSession$2.invoke(CustomTabActivity.kt:19)
        at org.mozilla.focus.activity.CustomTabActivity$customTabSession$2.invoke(CustomTabActivity.kt:16)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.focus.activity.CustomTabActivity.getCustomTabSession(Unknown Source:25)
        at org.mozilla.focus.activity.CustomTabActivity.<init>(CustomTabActivity.kt:46)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
