### ISSUE TITLE
Crash - minimized app after sending link to a fresh install

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#3733]
## Steps to reproduce
1. Fresh install Focus/clear app data. Don't launch the app.
2. From another app, send a link to Focus (e.g from Fennec).
3. Skip the first run, wait for the page to load. Minimize the app - tap the homescreen button.
### Expected behavior
App is sent to background, no crash.

### Actual behavior
"Focus has stopped working" error and the app is closed.

### Device information

* Android device: Samsung Galaxy S8 (Android 8.0), Mi 4i (Android 5.0.2)
* Focus version: 8.0 (Build# 322961216)

**Comment by ekager** [comment]
Can reproduce on master 
Logcat:

> Process: org.mozilla.klar.debug, PID: 9680
    java.lang.RuntimeException: Unable to pause activity {org.mozilla.klar.debug/org.mozilla.focus.activity.MainActivity}: java.lang.ClassCastException: org.mozilla.focus.fragment.BrowserFragment cannot be cast to org.mozilla.focus.fragment.UrlInputFragment
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4031)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3986)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3938)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: org.mozilla.focus.fragment.BrowserFragment cannot be cast to org.mozilla.focus.fragment.UrlInputFragment
        at org.mozilla.focus.activity.MainActivity.onPause(MainActivity.kt:166)
        at android.app.Activity.performPause(Activity.java:7329)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4021)

**Comment by ekager** [comment]
Good find thanks @sv-ohorvath !

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nightly (2018-10-25) build.
