### ISSUE TITLE
SearchSuggestions: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/focus-android#3907]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4718936/?query=is:unresolved

```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1e9251c position=10 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{9b51559 VFED..... ......I. 0,108-720,1188 #7f090126 app:id/suggestionList}, adapter:org.mozilla.focus.searchsuggestions.ui.SearchSuggestionsFragment$SuggestionsAdapter@6fa0fb9, layout:android.support.v7.widget.LinearLayoutManager@b593ffe, context:org.mozilla.focus.activity.MainActivity@17047fb
    at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5715)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5898)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
    at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3330)
    at android.view.View.measure(View.java:18804)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
```

**Comment by sv-ohorvath** [comment]
Are there any STR for this? Thanks!
