### ISSUE TITLE
Focus takes 5 minutes to start

### ISSUE THREAD

**Issue by hackel** [mozilla-mobile/focus-android#3938]
When I launch Firefox Focus 8.0, it opens to an empty grey screen, and I see a toast message "Starting app was delayed by system".  All I can do is go back to the home screen.  Then, out of the blue ~5 minutes later, Focus suddenly opens up in the middle of whatever else I've started doing at the time.

I have tried wiping app data, but the issue persists.  I've used Focus since it first came out and have never experienced this issue.  I finally examined my logcat and discovered this after the 5 minute delay:
```
java.net.ConnectException: Failed to connect to settings.prod.mozaws.net/52.39.59.46:443
mozilla.components.service.fretboard.ExperimentDownloadException: java.net.ConnectException: Failed to connect to settings.prod.mozaws.net/52.39.59.46:443
	at mozilla.components.service.fretboard.source.kinto.HttpURLConnectionHttpClient.get(HttpURLConnectionHttpClient.kt:33)
	at mozilla.components.service.fretboard.source.kinto.KintoClient.get(KintoClient.kt:32)
	at mozilla.components.service.fretboard.source.kinto.KintoExperimentSource.getExperimentsDiff(KintoExperimentSource.kt:48)
	at mozilla.components.service.fretboard.source.kinto.KintoExperimentSource.getExperiments(KintoExperimentSource.kt:34)
	at mozilla.components.service.fretboard.Fretboard.updateExperiments(Fretboard.kt:53)
	at org.mozilla.focus.FocusApplication$loadExperiments$2$1$1.invokeSuspend(FocusApplication.kt:95)
	at org.mozilla.focus.FocusApplication$loadExperiments$2$1$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:95)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:77)
	at kotlinx.coroutines.TimeoutKt.access$setupTimeout(Timeout.kt:1)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:56)
	at org.mozilla.focus.FocusApplication$loadExperiments$2$1.invokeSuspend(FocusApplication.kt:94)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: java.net.ConnectException: Failed to connect to settings.prod.mozaws.net/52.39.59.46:443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
	at mozilla.components.service.fretboard.source.kinto.HttpURLConnectionHttpClient.get(HttpURLConnectionHttpClient.kt:26)
	... 16 more
```

I do block connections to settings.prod.mozaws.net, but this should not be required merely to start the app.  Even more worrisome is that I have "Send usage data" disabled.  This is hard to understand for a browser focused on privacy.

**Comment by colintheshots** [comment]
The issue here is settings.prod.mozaws.net is required to load the A/B experiments so the app knows which code branch to load. We had a requirement to put the browser engine itself behind an A/B test, so the call isn't cosmetic in any way. We'll need to come up with a good fallback if this URL is blocked. No doubt the main issue is that the blocked URL is acting like a black hole instead of the connection being refused immediately. This isn't a trivial fix or workaround and we'll need to discuss what, if anything, we should do here.

**Comment by colintheshots** [comment]
I think adding the withTimeout() or withTimeoutOrNull() coroutine helper and handling timeout exceptions is likely the right move. https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/with-timeout.html

**Comment by rpappalax** [comment]
I connected Focus to a 100% throttled AP and it starts up without crashing nor does it crash after 5+ minutes.  Also, no crashes throttling network on and off with navigation, playing videos, etc.

**Comment by vesta0** [comment]
@rpappalax that is great news! Thank you for testing and investigating.
