### ISSUE TITLE
InvocationTargetException and URISyntaxException occurs when opening about:

### ISSUE THREAD

**Issue by makotokato** [mozilla-mobile/focus-android#3963]
## Steps to reproduce
1. Turn on GV by focus:test
2. input `about:` to address bar and go

### Expected behavior
No crash

### Actual behavior
Crash by InvocationTargetException
```
11-22 14:41:22.380  9697  9697 D AndroidRuntime: Shutting down VM
11-22 14:41:22.381  9697  9697 E AndroidRuntime: FATAL EXCEPTION: main
11-22 14:41:22.381  9697  9697 E AndroidRuntime: Process: org.mozilla.focus, PID: 9697
11-22 14:41:22.381  9697  9697 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-22 14:41:22.381  9697  9697 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        ... 1 more
11-22 14:41:22.381  9697  9697 E AndroidRuntime: Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 6: about:
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at java.net.URI$Parser.fail(URI.java:2892)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at java.net.URI$Parser.failExpecting(URI.java:2898)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at java.net.URI$Parser.parse(URI.java:3101)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at java.net.URI.<init>(URI.java:583)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at org.mozilla.focus.fragment.BrowserFragment$sessionObserver$1.onUrlChanged(BrowserFragment.kt:1436)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at org.mozilla.focus.fragment.BrowserFragment.onViewCreated(BrowserFragment.kt:344)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6680)
11-22 14:41:22.381  9697  9697 E AndroidRuntime:        ... 3 more
```

### Device information

* Android device:  Pixel 2 with Android P
* Focus version: 8.0 (Build #323202344 GV: 64.0.20181112164519)

**Comment by ekager** [comment]
Thanks for filing @makotokato ! On it
