### ISSUE TITLE
GeckoView: Open/ Erase&open when the Settings menu is opened crashes Focus

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4021]
## Steps to reproduce
1. Load a webpage.
2. Go to the Settings menu.
3. Minimize the app. 
4. Tap open or erase&open in the notification tray.
### Expected behavior
Existing (for open) or new session (for erase&open) of Focus is launched.
### Actual behavior
Focus crashes.
### Device information
* Android device: 
Motorola Nexus 6 (Android 7.1.1), Huawei P9 Lite (Android 6.0)
* Focus version: 8.0.2 Beta GV. Also reproducible on Master.

**Comment by sv-ohorvath** [comment]
GV Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1513929

**Comment by rpappalax** [comment]
I'm seeing this as well but only on erase & open

**Comment by sblatz** [comment]
Here's the crash on GV:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/4400286/50238321-1a6af500-038d-11e9-826b-d4d7c1d28818.png">

**Comment by cpeterso** [comment]
@snorp can reproduce this crash but he says this is a Focus bug, not a GV bug. Focus appears to be reusing one GeckoSession in multiple views:

```
1-03 11:51:01.166 22102 22102 W GeckoSession: Attempted to close a GeckoSession that was already closed.
01-03 11:51:01.167 22102 22102 D AndroidRuntime: Shutting down VM
01-03 11:51:01.170 22102 22102 E AndroidRuntime: FATAL EXCEPTION: main
01-03 11:51:01.170 22102 22102 E AndroidRuntime: Process: org.mozilla.focus, PID: 22102
01-03 11:51:01.170 22102 22102 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.mozilla.focus/org.mozilla.focus.activity.MainActivity}: java.lang.IllegalStateException: Display already acquired
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3785)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Display already acquired
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:1527)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:312)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:282)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView.restoreWebViewState(GeckoWebViewProvider.kt:585)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at org.mozilla.focus.fragment.WebFragment.restoreStateOrLoadUrl(WebFragment.kt:155)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at org.mozilla.focus.fragment.WebFragment.onResume(WebFragment.kt:111)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at org.mozilla.focus.fragment.BrowserFragment.onResume(BrowserFragment.kt:814)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7325)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3777)
01-03 11:51:01.170 22102 22102 E AndroidRuntime: 	... 11 more
01-03 11:51:01.171 22102 22102 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to resume activity {org.mozilla.focus/org.mozilla.focus.activity.MainActivity}: java.lang.IllegalStateException: Display already acquired)
01-03 11:51:01.171 22102 22102 I mozac/CrashReporter: Showing prompt
```

**Comment by vesta0** [comment]
@sblatz can you please confirm this is not a GV bug?

**Comment by sblatz** [comment]
Confirming that this is not a GV bug, just a crash that only happens when using GV (due to our implementation). I will dig into this and see if it's possible for us to fix!

I tested WebView and while it does not crash, it actually does not erase the session, either. Filed a follow up ticket for this: #4102 (likely low priority or no priority as it's WV specific).

**Comment by sblatz** [comment]
Ah, this is another issue tied to #4034. Leaving to @vesta0 to comment on that ticket and its priority!

**Comment by lobontiumira** [comment]
This isssue is no longer reproducible on the latest RC 95.1.0, nor on the 12/7 Focus Nightly build with Samsung Galaxy Note 8 (Android 9), and Sony Xperia Z5 Premium (Android 7.1.1).
