### ISSUE TITLE
On fresh install, the Focus app hangs on startup

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#405]
This can be reproduced in 5.1, 6.1, 7.1 sim and 5.1 6.1 device.
When a working Focus build was already installed, installing a newer version of Focus via 
$ adb push /Users/mozilla/GitRepo/focus-android/app/build/outputs/apk/app-focus-webkit-debug.apk /data/local/tmp/org.mozilla.focus.debug
$ adb shell pm install -r "/data/local/tmp/org.mozilla.focus.debug"
works fine. However, when Focus is pushed/installed after the existing older version of Focus is removed, then it hangs on the startup.

This is probably why the BB UI Tests were failing.

**Comment by pocmo** [comment]
From the ANR trace:

```
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x74e3ba88 self=0x78e8495a00
  | sysTid=4447 nice=-10 cgrp=default sched=0/0 handle=0x78ec336a98
  | state=S schedstat=( 63118176 9621250 111 ) utm=2 stm=3 core=3 HZ=100
  | stack=0x7fecb86000-0x7fecb88000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x0aa48f50> (a org.mozilla.focus.search.SearchEngineManager)
  at org.mozilla.focus.search.SearchEngineManager.awaitLoadingSearchEnginesLocked(SearchEngineManager.java:162)
  at org.mozilla.focus.search.SearchEngineManager.getDefaultSearchEngine(SearchEngineManager.java:143)
  - locked <0x0aa48f50> (a org.mozilla.focus.search.SearchEngineManager)
  at org.mozilla.focus.search.SearchEnginePreference.init(SearchEnginePreference.java:46)
  at org.mozilla.focus.search.SearchEnginePreference.<init>(SearchEnginePreference.java:36)
  at java.lang.reflect.Constructor.newInstance0!(Native method)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
  at android.preference.GenericInflater.createItem(GenericInflater.java:385)
  at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:432)
  at android.preference.GenericInflater.rInflate(GenericInflater.java:483)
  at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
  at android.preference.GenericInflater.inflate(GenericInflater.java:327)
  - locked <0x039b9549> (a java.lang.Object[])
  at android.preference.GenericInflater.inflate(GenericInflater.java:264)
  at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:280)
  at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:609)
  at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:568)
  at org.mozilla.focus.FocusApplication.onCreate(FocusApplication.java:22)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
  at android.app.ActivityThread.-wrap2(ActivityThread.java:-1)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6119)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by npark-mozilla** [comment]
So the first build that I see this is 36592130df653941b5fd9b898fe61396d1ff1dbb

**Comment by pocmo** [comment]
`PreferenceManager.setDefaultValues()` initializes the preferences -> `SearchEnginePreference` waits for the search engines to be loaded. However `SearchEngineManager.init()` is called after `setDefaultValues()` has been completed. A quick fix would be to call `SearchEngineManager.init()` before `PreferenceManager.setDefaultValues()` in `FocusApplication`.

**Comment by ahunt** [comment]
Leaving this bug open for the followup work (we've got an initial/basic fix that avoids the hang)!
