### ISSUE TITLE
Focus crashes on launch when switching engines

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4067]
## Steps to reproduce
1. Open "focus:test".
2. Flip the engine render flag.
3. Reopen Focus.

### Expected behavior
- Doesn't crash.

### Actual behavior
- Crashes 😢 

### Device information

* Android device: Android 9
* Focus version: 8.0.4 (Build #11) (Debug build - aarch64)

## Logs
<details>

```
2018-12-27 11:05:59.426 12619-12660/? E/GeckoLoader: Load diagnostics: LOAD mozglue: ABI: aarch64-gcc3, arm64-v8a: Data: /data/user/0/org.mozilla.focus.debug, ax=false, ddx=false, -1x=false, -2x=false, nativeLib: /data/app/org.mozilla.focus.debug-gJZ_Ydcp4Xa93z7cxzDLbw==/lib/arm64, dirx=false, libx=false
    
    --------- beginning of crash
2018-12-27 11:05:59.427 12619-12660/? E/AndroidRuntime: FATAL EXCEPTION: Gecko
    Process: org.mozilla.focus.debug, PID: 12619
    java.lang.RuntimeException: LOAD mozglue: ABI: aarch64-gcc3, arm64-v8a: Data: /data/user/0/org.mozilla.focus.debug, ax=false, ddx=false, -1x=false, -2x=false, nativeLib: /data/app/org.mozilla.focus.debug-gJZ_Ydcp4Xa93z7cxzDLbw==/lib/arm64, dirx=false, libx=false
        at org.mozilla.gecko.mozglue.GeckoLoader.doLoadLibrary(GeckoLoader.java:426)
        at org.mozilla.gecko.mozglue.GeckoLoader.loadMozGlue(GeckoLoader.java:434)
        at org.mozilla.gecko.GeckoThread.initGeckoEnvironment(GeckoThread.java:292)
        at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:455)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.mozilla.focus.debug-gJZ_Ydcp4Xa93z7cxzDLbw==/base.apk"],nativeLibraryDirectories=[/data/app/org.mozilla.focus.debug-gJZ_Ydcp4Xa93z7cxzDLbw==/lib/arm64, /system/lib64]]] couldn't find "libmozglue.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.mozilla.gecko.mozglue.GeckoLoader.doLoadLibraryExpected(GeckoLoader.java:347)
        at org.mozilla.gecko.mozglue.GeckoLoader.doLoadLibrary(GeckoLoader.java:373)
        at org.mozilla.gecko.mozglue.GeckoLoader.loadMozGlue(GeckoLoader.java:434) 
        at org.mozilla.gecko.GeckoThread.initGeckoEnvironment(GeckoThread.java:292) 
        at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:455) 
2018-12-27 11:05:59.428 1189-1203/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2018-12-27 11:05:59.428 1189-1203/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2018-12-27 11:05:59.431 1189-1203/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2018-12-27 11:05:59.431 1189-1203/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2018-12-27 11:05:59.433 1189-1199/? W/ActivityManager:   Force finishing activity org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity
2018-12-27 11:05:59.452 1189-1204/? I/ActivityManager: Showing crash dialog for package org.mozilla.focus.debug u0
2018-12-27 11:05:59.454 12619-12619/? W/lla.focus.debu: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
2018-12-27 11:05:59.454 12619-12619/? W/lla.focus.debu: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
2018-12-27 11:05:59.454 12619-12619/? W/lla.focus.debu: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
2018-12-27 11:05:59.490 1189-5459/? I/OpenGLRenderer: Initialized EGL, version 1.4
2018-12-27 11:05:59.490 1189-5459/? D/OpenGLRenderer: Swap behavior 1
2018-12-27 11:05:59.536 4928-29532/? W/ziparchive: Unable to open '/data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk': No such file or directory
2018-12-27 11:05:59.536 4928-29532/? E/s.nexuslaunche: Failed to open APK '/data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk' I/O error
2018-12-27 11:05:59.536 4928-29532/? E/ResourcesManager: failed to add asset path /data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk
2018-12-27 11:05:59.536 4928-29532/? W/PackageManager: Failure retrieving resources for org.mozilla.fennec_aurora
2018-12-27 11:05:59.536 4928-29532/? W/ziparchive: Unable to open '/data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk': No such file or directory
2018-12-27 11:05:59.536 4928-29532/? E/s.nexuslaunche: Failed to open APK '/data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk' I/O error
2018-12-27 11:05:59.536 4928-29532/? E/ResourcesManager: failed to add asset path /data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk
2018-12-27 11:05:59.536 4928-29532/? W/PackageManager: Failure retrieving resources for org.mozilla.fennec_aurora
2018-12-27 11:05:59.536 4928-29532/? W/ziparchive: Unable to open '/data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk': No such file or directory
2018-12-27 11:05:59.536 4928-29532/? E/s.nexuslaunche: Failed to open APK '/data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk' I/O error
2018-12-27 11:05:59.536 4928-29532/? E/ResourcesManager: failed to add asset path /data/app/org.mozilla.fennec_aurora-fqFbE5LiNWni287TdRl5Kg==/base.apk
2018-12-27 11:05:59.536 4928-29532/? W/PackageManager: Failure retrieving resources for org.mozilla.fennec_aurora
2018-12-27 11:05:59.579 790-790/? I//vendor/bin/hw/android.hardware.health@2.0-service.wahoo: SRAM data: 2541000
2018-12-27 11:05:59.582 2050-2050/? E/QtiImsExtUtils: getConfigForPhoneId phoneId is invalid
2018-12-27 11:05:59.582 2050-2050/? E/QtiImsExtUtils: isCarrierConfigEnabled bundle is null
2018-12-27 11:05:59.735 12619-12619/org.mozilla.focus.debug D/GeckoLocales: No selected locale. No correction needed.
2018-12-27 11:05:59.750 12619-12619/org.mozilla.focus.debug D/OpenGLRenderer: Skia GL Pipeline
2018-12-27 11:05:59.802 12619-12619/org.mozilla.focus.debug D/StrictMode: StrictMode policy violation; ~duration=228 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:605)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:596)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:552)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:747)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:400)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
        at mozilla.components.service.fretboard.DeviceUuidFactory$uuid$2.invoke(DeviceUuidFactory.kt:28)
        at mozilla.components.service.fretboard.DeviceUuidFactory$uuid$2.invoke(DeviceUuidFactory.kt:18)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mozilla.components.service.fretboard.DeviceUuidFactory.getUuid(Unknown Source:7)
        at mozilla.components.service.fretboard.ValuesProvider.getClientId(ValuesProvider.kt:101)
        at mozilla.components.service.fretboard.ExperimentEvaluator.getUserBucket(ExperimentEvaluator.kt:93)
        at mozilla.components.service.fretboard.ExperimentEvaluator.evaluate$default(ExperimentEvaluator.kt:35)
        at mozilla.components.service.fretboard.Fretboard.isInExperiment(Fretboard.kt:74)
        at org.mozilla.focus.utils.ExperimentsKt.isInExperiment(Experiments.kt:24)
        at org.mozilla.focus.tips.TipManager.getNextTipIfAvailable(TipManager.kt:214)
        at org.mozilla.focus.fragment.UrlInputFragment.updateTipsLabel(UrlInputFragment.kt:221)
        at org.mozilla.focus.fragment.UrlInputFragment.onViewCreated(UrlInputFragment.kt:341)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2938)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-12-27 11:05:59.806 12619-12619/org.mozilla.focus.debug D/StrictMode: StrictMode policy violation; ~duration=226 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:605)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:596)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:552)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:747)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:400)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
        at mozilla.components.service.fretboard.ExperimentEvaluator.evaluate(ExperimentEvaluator.kt:39)
        at mozilla.components.service.fretboard.ExperimentEvaluator.evaluate$default(ExperimentEvaluator.kt:35)
        at mozilla.components.service.fretboard.Fretboard.isInExperiment(Fretboard.kt:74)
        at org.mozilla.focus.utils.ExperimentsKt.isInExperiment(Experiments.kt:24)
        at org.mozilla.focus.tips.TipManager.getNextTipIfAvailable(TipManager.kt:214)
        at org.mozilla.focus.fragment.UrlInputFragment.updateTipsLabel(UrlInputFragment.kt:221)
        at org.mozilla.focus.fragment.UrlInputFragment.onViewCreated(UrlInputFragment.kt:341)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2938)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

</details>

**Comment by colintheshots** [comment]
We believe the cause is using the aarch64 arch type. We don't currently distribute ARM64 APKs for Focus due to known issues GeckoView used to have with them. These should be resolved soon, but we make no promises to support this arch yet.

**Comment by jonalmeida** [comment]
You're right! Just tried again with the arm build instead of the arm64 - all works fine.

**Comment by colintheshots** [comment]
Close as not a real issue for now.
