### ISSUE TITLE
Crash on invalid URL in UrlUtils.stripUserInfo

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#414]
URL -> `data:`

<pre>FATAL EXCEPTION: main
         Process: org.mozilla.focus.debug, PID: 7033
         java.lang.IllegalStateException: WebView is expected to always supply a valid URL
              at org.mozilla.focus.utils.UrlUtils.stripUserInfo(UrlUtils.java:81)
              at org.mozilla.focus.fragment.BrowserFragment.updateURL(BrowserFragment.java:81)
              at org.mozilla.focus.fragment.BrowserFragment.inflateLayout(BrowserFragment.java:89)
              at org.mozilla.focus.fragment.WebFragment.onCreateView(WebFragment.java:43)</pre>

**Comment by pocmo** [comment]
@ahunt A regression from the refactoring?
