### ISSUE TITLE
White Screen of Death - no pages loading

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4142]
## Steps to reproduce
n/a

### Actual behavior
- I was seeing a white window and entering various search terms and urls in the toolbar wasn't giving me any results.

### Device information

* Android device: Android 9 (Pixel 2)
* Focus version: 8.0.6 (Build #330151226 :lizard: 64.0.20190111134233)

Two bug reports attached here: https://drive.google.com/drive/folders/1O_NB4wZMHe_NhPf7KhuTAonc-XqadRX8?usp=sharing

There were two Strict Mode violations around the same time but that might be a red herring. Trace below:

<details>

```
2019-01-16 10:54:38.280 7319-7319/? D/StrictMode: StrictMode policy violation; ~duration=49 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:605)
        at android.app.ContextImpl.ensurePrivateCacheDirExists(ContextImpl.java:601)
        at android.app.ContextImpl.getCacheDir(ContextImpl.java:694)
        at android.content.ContextWrapper.getCacheDir(ContextWrapper.java:269)
        at org.mozilla.focus.utils.MobileMetricsPingStorage.<init>(MobileMetricsPingStorage.kt:17)
        at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView.storeTelemetrySnapshots(GeckoWebViewProvider.kt:685)
        at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView.onResume(GeckoWebViewProvider.kt:211)
        at org.mozilla.focus.fragment.WebFragment.onResume(WebFragment.kt:109)
        at org.mozilla.focus.fragment.BrowserFragment.onResume(BrowserFragment.kt:811)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7325)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-01-16 10:54:38.280 7319-7319/? D/StrictMode: StrictMode policy violation; ~duration=49 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at org.mozilla.focus.utils.MobileMetricsPingStorage.shouldStoreMetrics(MobileMetricsPingStorage.kt:21)
        at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView.storeTelemetrySnapshots(GeckoWebViewProvider.kt:686)
        at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView.onResume(GeckoWebViewProvider.kt:211)
        at org.mozilla.focus.fragment.WebFragment.onResume(WebFragment.kt:109)
        at org.mozilla.focus.fragment.BrowserFragment.onResume(BrowserFragment.kt:811)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
        at android.app.Activity.performResume(Activity.java:7325)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-01-16 10:54:38.576 27579-27598/? D/GeckoViewModule: dispatch GeckoView:SaveState, data=null
2019-01-16 10:54:38.576 27579-27598/? D/GeckoViewContent: onEvent: event=GeckoView:SaveState, data=null
2019-01-16 10:54:38.581 27659-27681/? D/GeckoViewContent[C]: receiveMessage: GeckoView:SaveState
2019-01-16 10:54:38.621 27579-27598/? D/GeckoViewContent: receiveMessage: GeckoView:SaveStateFinish
```

</details>

**Comment by jonalmeida** [comment]
cc: @snorp

**Comment by 4ut0-M-4t** [comment]
The only thing that helps is killing the app process, cleaning its cache and restarting Focus/Klar.

**Comment by gaganpreet** [comment]
I have been struggling with the same for months since the switch to GeckoView. Force killing the process fixes it for a while, until it happens again.

**Comment by lobontiumira** [comment]
I did not encounter this issue lately.
I tested on the 8.16.0 Focus also, and no white screens were displayed, opening different pages, or different tabs, using a Google Pixel (Android 10), and a Samsung Galaxy Note 8 (Android 9).
I'll close this issue.
