### ISSUE TITLE
Focus crashes at long tap on videos

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4189]
## Steps to reproduce
1. Go to youtube.com and play a video.
2. Long tap on the video (either paused or playing).
### Expected behavior
A context menu is displayed (?). On 8.0.6 nothing happened. On webView there is a link context menu displayed.
### Actual behavior
Focus crashes.
### Device information

* Android device: 
HTC Desire 820 (Android 6.0.1), Samsung Galaxy Note 8 (Android 8.0)
* Focus version: Nightly 9.0 GV 65. Not reproducing on webView.

**Comment by kbrosnan** [comment]
I ran into this as well. Seems really bad to ship this.

    Process: org.mozilla.focus, PID: 32460
    java.lang.IllegalStateException: WebContextMenu can only handle long-presses on images and/or links.
        at org.mozilla.focus.menu.context.WebContextMenu.show(WebContextMenu.kt:64)
        at org.mozilla.focus.fragment.BrowserFragment$createCallback$1.onLongPress(BrowserFragment.kt:519)
        at org.mozilla.focus.session.SessionCallbackProxy.onLongPress(SessionCallbackProxy.kt:118)
        at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView$createContentDelegate$1.onContextMenu(GeckoWebViewProvider.kt:355)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:375)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:356)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:79)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by iadeelzafar** [comment]
@ekager  @kbrosnan  @sv-ohorvath Any updates on this? I'd like to work on this but I need some directions on how this could be solved.

**Comment by kbrosnan** [comment]
Sentry issue: [FOCUS-ANDROID-3V1](https://sentry.prod.mozaws.net/operations/focus-android/issues/5135898/)

**Comment by kbrosnan** [comment]
Fixing this bug may require working on GeckoView. This is not a good first bug in the project as it requires knowledge of how Focus and GeckoView integrate with each other. This may be fixed by upgrading to a more recent version of GeckoView which someone is already working on.

**Comment by iadeelzafar** [comment]
@kbrosnan Alright. Thanks.

**Comment by kbrosnan** [comment]
This appears to be resolved. No longer crashing on long pressing on YouTube videos and not seeing any crash reports that mention WebContextMenu in their stack traces
