### ISSUE TITLE
'Erase and Open' does not delete the loaded webpage when Settings menu is displayed

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/focus-android#4429]
## Steps to reproduce
1. Load a webpage and then enter the Settings menu;
2. Press the home button to go to app view;
3. Pull down the notification tray;
4. Tap Erase and Open.
### Expected behavior
The initial screen of Focus is displayed, with the previous webpage deleted.
### Actual behavior
The webpage from Step 1 is displayed.
### Notes
[Video](https://drive.google.com/file/d/1qt232l99tc-EPhyaXoA2kTcyTBjNZG3T/view?usp=sharing)

### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: 8.0.24 GV 71

**Comment by crazyman10123** [comment]
I can look into this as a potential first bug for me to fix. 

Following the same steps you've provided cause the app to completely crash on my device. I'm setting up a virtual device using your model as reference to see if I can recreate the exact behavior you're describing.

**Comment by crazyman10123** [comment]
I've found that following the steps provided in the bug report cause a FatalException. I haven't been able to figure out what I could do within Focus to remedy this. 

My thoughts are to have the app switch off of the settings view when minimizing, but I'm not sure how to go about that. 

`2019-12-28 14:17:29.756 10931-10931/org.mozilla.focus.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.debug, PID: 10931
    java.lang.IllegalStateException: Display already acquired
        at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:2391)
        at org.mozilla.geckoview.GeckoView.onAttachedToWindow(GeckoView.java:436)`
