### ISSUE TITLE
Crash in [@ kotlin.KotlinNullPointerException: at androidx.transition.CanvasUtils.contentState(CanvasUtils.java)]

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#4682]
Crash report: https://crash-stats.mozilla.org/report/index/b502b748-d479-4c82-8e80-e8e190201216

This is the #1 topcrash on Focus at the moment and appears to be new in the 8.11 release.

Java stack trace:

```
kotlin.KotlinNullPointerException
	at androidx.transition.CanvasUtils.contentState(CanvasUtils.java:2)
	at org.mozilla.focus.session.SessionCallbackProxy.onRequest(SessionCallbackProxy.kt:3)
	at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView$createNavigationDelegate$1.onLoadRequest(GeckoWebViewProvider.kt:22)
	at org.mozilla.geckoview.GeckoSession.lambda$shouldLoadUri$3$GeckoSession(GeckoSession.java:1)
	at org.mozilla.geckoview.-$$Lambda$GeckoSession$PKzvNF51anwOyHsNq0868SZFMNw.run(Unknown Source:8)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoSession.shouldLoadUri(GeckoSession.java:4)
	at org.mozilla.geckoview.GeckoSession.load(GeckoSession.java:9)
	at org.mozilla.geckoview.GeckoSession.loadUri(GeckoSession.java:1)
	at org.mozilla.focus.web.GeckoWebViewProvider$GeckoWebView.loadUrl(GeckoWebViewProvider.kt:2)
	at org.mozilla.focus.fragment.WebFragment.onCreateView(WebFragment.kt:15)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:87)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:219)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:9)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
	at android.app.Activity.performStart(Activity.java:7479)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3454)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

---

Taken from: https://bugzilla.mozilla.org/show_bug.cgi?id=1682957

**Comment by jonalmeida** [comment]
This is such a strange error.

For `SessionCallbackProxy.onRequest`, the only direct reference to a "contentState" is one from `BrowserState` and _not_ from `androidx.transition.CanvasUtils.contentState`.

I wonder if there is just some symbol mix-up from the device with it tries to resolve the name. That would make more sense, since we have a `!!` non-null assertion there and that's probably the cause.

All that said, I can't reproduce this crash so let's get a null-check there for now.

**Comment by ebalazs-sv** [comment]
@jonalmeida Hi! Are there any steps to reproduce this crash so we can verify the fix?

**Comment by jonalmeida** [comment]
Hi @ebalazs-sv , unfortunately none that I've found. I've put in a speculative fix based on crash logs.

It looks like it might be related to opening app links in Focus.
