### ISSUE TITLE
java.lang.ClassNotFoundException crash spike on focus 8.13.0

### ISSUE THREAD

**Issue by jcristau** [mozilla-mobile/focus-android#4699]
google play is showing elevated crash rate for 350490945.apk

Stack traces look like this:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4589)
  at android.app.ActivityThread.access$1700 (ActivityThread.java:301)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2137)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8425)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:207)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:379)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at android.app.AppComponentFactory.instantiateService (AppComponentFactory.java:129)
  at androidx.core.app.CoreComponentFactory.instantiateService (CoreComponentFactory.java:1)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4568)
```

**Comment by jcristau** [comment]
Also filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1694150

**Comment by jonalmeida** [comment]
After chatting with folks in the AC meeting, it turns out that Crash Status strips out some of the java stack which you can see in Sentry.

```
java.lang.ClassNotFoundException: Didn't find class "org.mozilla.focus.utils.ExperimentsSyncService" on path: DexPathList[[zip file "/data/app/~~jtNNZgnXXD9Cbsy0jIFVdg==/org.mozilla.focus-4JrgKwP3MnS9RiyTryW6KA==/base.apk"],nativeLibraryDirectories=[/data/app/~~jtNNZgnXXD9Cbsy0jIFVdg==/org.mozilla.focus-4JrgKwP3MnS9RiyTryW6KA==/lib/arm64, /data/app/~~jtNNZgnXXD9Cbsy0jIFVdg==/org.mozilla.focus-4JrgKwP3MnS9RiyTryW6KA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
```

It seems like we're trying to launch the `ExperimentsSyncService` in Focus which was [recently removed](https://github.com/mozilla-mobile/focus-android/pull/4693). There is [one more reference](https://github.com/mozilla-mobile/focus-android/blob/99f65f85184ad407cdb0b7fc15e2364b49ac9125/app/src/main/AndroidManifest.xml#L138-L141) in the AndroidManifest that registers the service which also needs to be removed.

**Comment by jonalmeida** [comment]
For QA: we don't have any steps to reproduce this bug, so we're probably going to monitor the crash stats to see if it shows up in 8.13.1.
