### ISSUE TITLE
IllegalStateException: Fragment TabSheetFragment{940612e} (539f7518-1e27-4da9-a40d-cc422ba13383)} not attached to a context.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#4842]
```
                         E  FATAL EXCEPTION: main
                         E  Process: org.mozilla.focus.debug, PID: 4377
                         E  java.lang.IllegalStateException: Fragment TabSheetFragment{940612e} (539f7518-1e27-4da9-a40d-cc422ba13383)} not attached to a context.
                         E      at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
                         E      at org.mozilla.focus.ext.FragmentKt.getRequireComponents(Fragment.kt:22)
                         E      at org.mozilla.focus.session.ui.TabSheetFragment$animateAndDismiss$1.onAnimationEnd(TabSheetFragment.kt:116)
                         E      at android.graphics.animation.RenderNodeAnimator.onFinished(RenderNodeAnimator.java:370)
                         E      at android.animation.RevealAnimator.onFinished(RevealAnimator.java:43)
                         E      at android.graphics.animation.-$$Lambda$awqPSgriNRe12PWP0zkpAtPsfV4.run(Unknown Source:2)
                         E      at android.os.Handler.handleCallback(Handler.java:938)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loop(Looper.java:223)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7660)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       ExceptionHandler  E  Uncaught exception handled:
                         E  java.lang.IllegalStateException: Fragment TabSheetFragment{940612e} (539f7518-1e27-4da9-a40d-cc422ba13383)} not attached to a context.
                         E      at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
                         E      at org.mozilla.focus.ext.FragmentKt.getRequireComponents(Fragment.kt:22)
                         E      at org.mozilla.focus.session.ui.TabSheetFragment$animateAndDismiss$1.onAnimationEnd(TabSheetFragment.kt:116)
                         E      at android.graphics.animation.RenderNodeAnimator.onFinished(RenderNodeAnimator.java:370)
                         E      at android.animation.RevealAnimator.onFinished(RevealAnimator.java:43)
                         E      at android.graphics.animation.-$$Lambda$awqPSgriNRe12PWP0zkpAtPsfV4.run(Unknown Source:2)
                         E      at android.os.Handler.handleCallback(Handler.java:938)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loop(Looper.java:223)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7660)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by pocmo** [comment]
I see this crash whenever I switch tabs.
