### ISSUE TITLE
Intermittent UI test failure - <EraseBrowsingDataTest.deleteHistoryOnRestartTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#4889]
### Stacktrace:
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.mozilla.focus.activity.robots.SearchRobot.typeInSearchBar(SearchRobot.kt:27)
at org.mozilla.focus.activity.robots.SearchRobot$Transition$loadPage$1.invoke(SearchRobot.kt:67)
at org.mozilla.focus.activity.robots.SearchRobot$Transition$loadPage$1.invoke(SearchRobot.kt:63)
at org.mozilla.focus.activity.robots.SearchRobotKt.searchScreen(SearchRobot.kt:87)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:67)
at org.mozilla.focus.activity.EraseBrowsingDataTest.deleteHistoryOnRestartTest(EraseBrowsingDataTest.kt:123)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)

**Comment by sv-ohorvath** [comment]
The video shows that the notifications stack was opened on the device for some reason. We don't currently have any test to use it, so it might be something on that device, or the test clicked somewhere else than the search bar to trigger it.
The same thing happened here: #4908

**Comment by sv-ohorvath** [comment]
This hasn't failed recently, so I'm closing it. If it fails again, we can reopen.
