### ISSUE TITLE
[Crash] java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 664 ("DefaultDispatcher-worker-1")

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4981]
## Steps to reproduce
2 automated UI tests failed with this crash:
org.mozilla.focus.activity.SafeBrowsingTest.unblockSafeBrowsingTest
org.mozilla.focus.activity.CustomTabTest.testCustomTabUI
[Firebase log](https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5048718455637267608/executions/bs.7dd6269801380449/testcases/1/logs)

[Text logs](https://github.com/mozilla-mobile/focus-android/files/6791875/focus-crash.txt)

### Expected behavior
Launch app
### Actual behavior
App crashes at launch
` FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: org.mozilla.focus.debug, PID: 8981
java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 664 ("DefaultDispatcher-worker-1")
	at org.mozilla.gecko.util.ThreadUtils.assertOnThreadComparison(ThreadUtils.java:110)
	at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:86)
	at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:77)
	at org.mozilla.geckoview.GeckoRuntime.setDelegate(GeckoRuntime.java:553)
	at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:104)
	at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:75)
	at org.mozilla.focus.components.EngineProvider.createEngine(EngineProvider.kt:38)
	at org.mozilla.focus.Components$engine$2.invoke(Components.kt:81)
	at org.mozilla.focus.Components$engine$2.invoke(Components.kt:57)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.mozilla.focus.Components.getEngine(Unknown Source:2)
	at org.mozilla.focus.Components$store$2.invoke(Components.kt:117)
	at org.mozilla.focus.Components$store$2.invoke(Components.kt:57)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.mozilla.focus.Components.getStore(Unknown Source:2)
	at org.mozilla.focus.telemetry.GleanMetricsService$collectPrefMetrics$1.invokeSuspend(GleanMetricsService.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`
### Device information

* Android device: Pixel 2 (Android 10) virtual device on Firebase test lab
* Focus version: Debug

**Comment by sv-ohorvath** [comment]
dupe of https://github.com/mozilla-mobile/focus-android/issues/4964
