### ISSUE TITLE
[Crash] Browser crashes when you refresh a page

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4990]
## Steps to reproduce
1. Load a webpage.
2. Tap the refresh button in the main menu.

Or: load a page and stop it from loading by pressing the stop button in the main menu.

### Expected behavior
Page reloaded.
### Actual behavior
App crashes.
`2021-07-15 11:04:08.316 10324-10324/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.debug, PID: 10324
    java.lang.IllegalArgumentException: Unhandled menu item in BrowserFragment
        at org.mozilla.focus.fragment.BrowserFragment.onClick(BrowserFragment.kt:653)
        at org.mozilla.focus.menu.browser.BrowserMenuViewHolder.onClick(BrowserMenuViewHolder.java:40)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`
### Device information

* Android device: Pixel 2 (Android 9)
* Focus version: Debug 7/15
* Not reproducing on the latest release 8.17.1

**Comment by Nickoriginal** [comment]
Where I can download this Focus debug APK?

**Comment by lobontiumira** [comment]
Reproducible on 8.18.0-rc.1 build with HTC 10 (Android 8).

**Comment by Nickoriginal** [comment]
Reproducible in Focus 8.18.0-rc.1 on Samsung Galaxy A20s (Android 11).

**Comment by lobontiumira** [comment]
Verified as fixed on the 91.1.0 Firefox Focus build, with Google Pixel (Android 10).
