### ISSUE TITLE
Intermittent UI test failure - MultitaskingTest.testVisitingMultipleSites

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#4996]
### Firebase Test Run:
Failed 2/2 tries:
https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6414384169363496649/executions/bs.ff1ba623613eb2a5/testcases/1### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.mozilla.focus.helpers.TestHelper.verifySnackBarText(TestHelper.kt:58)
at org.mozilla.focus.activity.MultitaskingTest$testVisitingMultipleSites$3.invoke(MultitaskingTest.kt:74)
at org.mozilla.focus.activity.MultitaskingTest$testVisitingMultipleSites$3.invoke(MultitaskingTest.kt:30)
at org.mozilla.focus.activity.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:201)
at org.mozilla.focus.activity.MultitaskingTest.testVisitingMultipleSites(MultitaskingTest.kt:71)`
### Build: 
Master 7/15

**Comment by sv-ohorvath** [comment]
Maybe it's worth changing the test a bit and re-enable it here https://github.com/mozilla-mobile/focus-android/issues/5854 with other "tabs" tests.

**Comment by mcarare** [comment]
Failing with:

```
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'has descendant: (with text: is "localhost/tab3.html" and with parent index: 1)' doesn't match the selected view.
Expected: has descendant: (with text: is "localhost/tab3.html" and with parent index: 1)
Got: "RecyclerView{id=2131362305, res-name=sessions, visibility=VISIBLE, width=772, height=462, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@94722a1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}"
```
https://console.firebase.google.com/u/1/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7274169673281677484/executions/bs.ae32ec2f0c1b1036/testcases/1

**Comment by sv-ohorvath** [comment]
Closing because it hasn't failed in more than a month. Please open a new issue if any new problems appear.
