### ISSUE TITLE
[crash] Debug build crashes when refreshing the page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5006]
## Steps to reproduce
1. Open a page, and refresh it.

### Expected behavior
The page reloads.

### Actual behavior
The app crashes.

### Device information
* Android device: Google Pixel (Android 10)
* Focus version: the debug build 8.13.1 (1191.0a1-20210705095222)

    
```
    --------- beginning of crash
2021-07-22 16:52:26.113 9173-9173/org.mozilla.focus.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.debug, PID: 9173
    java.lang.IllegalArgumentException: Unhandled menu item in BrowserFragment
        at org.mozilla.focus.fragment.BrowserFragment.onClick(BrowserFragment.kt:653)
        at org.mozilla.focus.menu.browser.BrowserMenuViewHolder.onClick(BrowserMenuViewHolder.java:40)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-07-22 16:52:26.115 9173-9173/org.mozilla.focus.debug E/ExceptionHandler: Uncaught exception handled: 
    java.lang.IllegalArgumentException: Unhandled menu item in BrowserFragment
        at org.mozilla.focus.fragment.BrowserFragment.onClick(BrowserFragment.kt:653)
        at org.mozilla.focus.menu.browser.BrowserMenuViewHolder.onClick(BrowserMenuViewHolder.java:40)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-07-22 16:52:26.121 9173-9173/org.mozilla.focus.debug I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(timestamp=1626961946120, throwable=java.lang.IllegalArgumentException: Unhandled menu item in BrowserFragment, breadcrumbs=[], uuid=e87fddfa-d85c-458e-a655-123115179cae)
2021-07-22 16:52:26.177 9173-9173/org.mozilla.focus.debug I/mozac/CrashReporter: Showing notification
2021-07-22 16:52:26.233 9173-9362/org.mozilla.focus.debug V/StudioTransport: Handling agent command 1200 for pid: 9173.
2021-07-22 16:52:26.315 9173-9362/org.mozilla.focus.debug V/StudioTransport: Handling agent command 1200 for pid: 9173.
2021-07-22 16:52:26.736 9173-9227/org.mozilla.focus.debug E/GeckoConsole: [JavaScript Error: "NS_ERROR_FILE_NOT_FOUND: " {file: "resource://gre/modules/SessionStoreFunctions.jsm" line: 120}]
    SSF_updateSessionStoreForWindow@resource://gre/modules/SessionStoreFunctions.jsm:120:5
    UpdateSessionStoreForStorage@resource://gre/modules/SessionStoreFunctions.jsm:54:35
2021-07-22 16:52:27.049 9173-9227/org.mozilla.focus.debug E/GeckoConsole: [JavaScript Error: "NS_ERROR_FILE_NOT_FOUND: " {file: "resource://gre/modules/SessionStoreFunctions.jsm" line: 120}]
    SSF_updateSessionStoreForWindow@resource://gre/modules/SessionStoreFunctions.jsm:120:5
    UpdateSessionStoreForStorage@resource://gre/modules/SessionStoreFunctions.jsm:54:35
2021-07-22 16:52:27.252 9173-9362/org.mozilla.focus.debug V/StudioTransport: Handling agent command 1200 for pid: 9173.
2021-07-22 16:52:27.458 9173-9362/org.mozilla.focus.debug V/StudioTransport: Handling agent command 1200 for pid: 9173.

```

https://user-images.githubusercontent.com/40694158/126651060-09830438-ecd9-45f7-91ad-8f04ea655375.mp4

**Comment by Nickoriginal** [comment]
Duplicate of #4990?

**Comment by lobontiumira** [comment]
Closing as duplicate of #4990.
