### ISSUE TITLE
Intermittent UI test failure - <MozillaSupportPagesTest.openYourRightsPageTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5075]
### Stacktrace:
08-07 23:25:23.132: I/Remoter(1927): --------- beginning of crash
08-07 23:25:23.137: E/AndroidRuntime(7655): FATAL EXCEPTION: DefaultDispatcher-worker-3
08-07 23:25:23.137: E/AndroidRuntime(7655): Process: org.mozilla.focus.debug, PID: 7655
08-07 23:25:23.137: E/AndroidRuntime(7655): java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 414 ("DefaultDispatcher-worker-1")
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.gecko.util.ThreadUtils.assertOnThreadComparison(ThreadUtils.java:110)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:86)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:77)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.geckoview.GeckoRuntime.setDelegate(GeckoRuntime.java:541)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:109)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:68)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.focus.components.EngineProvider.createEngine(EngineProvider.kt:38)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.focus.Components$engine$2.invoke(Components.kt:90)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.focus.Components$engine$2.invoke(Components.kt:89)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.focus.Components.getEngine(Components.kt:89)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.focus.Components$store$2.invoke(Components.kt:130)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.focus.Components$store$2.invoke(Components.kt:113)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.focus.Components.getStore(Components.kt:113)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at org.mozilla.focus.telemetry.GleanMetricsService$collectPrefMetrics$1.invokeSuspend(GleanMetricsService.kt:90)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
08-07 23:25:23.137: E/AndroidRuntime(7655): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
08-07 23:25:23.148: I/Process(7655): Sending signal. PID: 7655 SIG: 9
08-07 23:25:23.149: I/VoiceImeExtension(2208): Voice Extension onStartInputView() Mic status = [MicIconHidden-VoiceInputUnAvailable, MicIconHidden-IncognitoMode, ]
08-07 23:25:23.159: W/BroadcastQueue(2070): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-07 23:25:23.159: W/BroadcastQueue(2070): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-07 23:25:23.203: E/memtrack(2070): Couldn't load memtrack module
08-07 23:25:23.203: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-07 23:25:23.207: W/hwservicemanager(1841): getTransport: Cannot find entry android.hardware.configstore@1.0::ISurfaceFlingerConfigs/default in either framework or device manifest.
08-07 23:25:23.208: I/ConfigStore(2208): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
08-07 23:25:23.208: I/ConfigStore(2208): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-07 23:25:23.208: I/OpenGLRenderer(2208): Initialized EGL, version 1.4
08-07 23:25:23.208: D/OpenGLRenderer(2208): Swap behavior 1
08-07 23:25:23.248: W/eportingProces(8043): Unexpected CPU variant for X86 using defaults: x86
08-07 23:25:23.303: I/ActivityManager(2070): Start proc 8079:org.mozilla.focus.debug:mozilla.components.lib.crash.CrashReporter/u0a95 for activity org.mozilla.focus.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity
08-07 23:25:23.329: W/InputDispatcher(2070): channel '59e90e3 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-07 23:25:23.329: E/InputDispatcher(2070): channel '59e90e3 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-07 23:25:23.329: I/Zygote(1909): Process 7655 exited due to signal (9)
08-07 23:25:23.363: I/Zygote(8079): seccomp disabled by setenforce 0
08-07 23:25:23.364: I/h.CrashReporte(8079): Late-enabling -Xcheck:jni
08-07 23:25:23.402: I/ActivityManager(2070): Process org.mozilla.focus.debug (pid 7655) has died: fore TOP 
08-07 23:25:23.403: W/libprocessgroup(2070): kill(-7655, 9) failed: No such process
08-07 23:25:23.403: I/libprocessgroup(2070): Successfully killed process cgroup uid 10095 pid 7655 in 0ms

**Comment by AndiAJ** [comment]
Closing in favor of #4964
