### ISSUE TITLE
Intermittent UI test failure - <CustomTabTest.openCustomTabInFocusTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5077]
### Firebase Test Run:
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.8e54a58648eea5f9/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6066125213718826339/executions/bs.ca6aad88a2f0e9ab/testcases/1)
### Stacktrace:
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.focus.debug:id/open_in_firefox_focus

View Hierarchy:
+>PopupDecorView{id=-1, visibility=VISIBLE, width=741, height=1026, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(981,77)(wrapxwrap) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged} ty=APPLICATION_PANEL fmt=TRANSPARENT wanim=0x7f120101 surfaceInsets=Rect(45, 45 - 45, 45) (manual)
fl=SPLIT_TOUCH HARDWARE_ACCELERATED FLAG_LAYOUT_ATTACHED_IN_DECOR
pfl=WILL_NOT_REPLACE_ON_RELAUNCH LAYOUT_CHILD_WINDOW_IN_PARENT_FRAME}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+->PopupBackgroundView{id=-1, visibility=VISIBLE, width=741, height=1026, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@a725ba4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+-->CardView{id=2131296597, res-name=mozac_browser_menu_menuView, visibility=VISIBLE, width=741, height=1026, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@f752d0d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+--->DynamicWidthRecyclerView{id=2131296598, res-name=mozac_browser_menu_recyclerView, visibility=VISIBLE, width=689, height=952, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@dac54c2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=26.0, y=37.0, child-count=9}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@43f62d3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}
|
+----->AppCompatImageButton{id=-1, desc=Navigate back, visibility=VISIBLE, width=229, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@14b8e10, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+----->AppCompatImageButton{id=-1, desc=Navigate forward, visibility=VISIBLE, width=230, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@2d48d09, tag=null, root-is-layout-requested=false, has-input-connection=false, x=229.0, y=0.0}
|
+----->AppCompatImageButton{id=-1, desc=Reload website, visibility=VISIBLE, width=230, height=154, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@56efb0e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=459.0, y=0.0}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@b93592f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=154.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@c6b0f28, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=157.0, child-count=4}
|
+----->AppCompatImageView{id=2131296543, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@923d441, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131296812, res-name=text, visibility=VISIBLE, width=351, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@a335de6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Find in Page, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=184, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@45f3f27, tag=null, root-is-layout-requested=false, has-input-connection=false, x=461.0, y=64.0}
|
+----->AppCompatImageView{id=2131296669, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@f5f5d4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->SwitchCompat{id=2131296792, res-name=switch_widget, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@f98737d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=289.0, text=Desktop site, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+---->View{id=-1, visibility=VISIBLE, width=689, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@6c77272, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=421.0}
|
+---->LinearLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@312ec1f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=424.0, child-count=4}
|
+----->AppCompatImageView{id=2131296543, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@1fa2b6c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatTextView{id=2131296812, res-name=text, visibility=VISIBLE, width=510, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@2479535, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=36.0, text=Add to Home screen, input-type=0, ime-target=false, has-links=false}
|
+----->View{id=-1, visibility=VISIBLE, width=25, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@3eeddca, tag=null, root-is-layout-requested=false, has-input-connection=false, x=620.0, y=64.0}
|
+----->AppCompatImageView{id=2131296669, res-name=overflowImage, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@8842b3b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->ConstraintLayout{id=-1, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@d1235ed, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=556.0, child-count=5}
|
+----->AppCompatImageView{id=2131296543, res-name=image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@f7d5c22, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=33.0}
|
+----->AppCompatImageView{id=2131296660, res-name=notification_dot, desc=Highlighted, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@ebec6b3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=11.025001, y=-11.025001}
|
+----->AppCompatTextView{id=2131296812, res-name=text, visibility=INVISIBLE, width=287, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@9375470, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=37.0, text=Open in…, input-type=0, ime-target=false, has-links=false}
|
+----->AppCompatTextView{id=2131296525, res-name=highlight_text, visibility=VISIBLE, width=287, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@6e943e9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=110.0, y=37.0, text=Open in…, input-type=0, ime-target=false, has-links=false}
|
+----->AppCompatImageView{id=2131296478, res-name=end_image, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@339186e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=579.0, y=33.0}
|
+---->AppCompatTextView{id=2131296753, res-name=simple_text, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@7d51b0f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=688.0, text=TestItem4223, input-type=0, ime-target=false, has-links=false}
|
+---->AppCompatTextView{id=2131296753, res-name=simple_text, visibility=VISIBLE, width=689, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@95479c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=820.0, text=Powered by Firefox Focus, input-type=0, ime-target=false, has-links=false}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
at org.mozilla.focus.activity.robots.CustomTabRobot.clickOpenInFocusButton(CustomTabRobot.kt:51)
at org.mozilla.focus.activity.CustomTabTest$openCustomTabInFocusTest$4.invoke(CustomTabTest.kt:103)
at org.mozilla.focus.activity.CustomTabTest$openCustomTabInFocusTest$4.invoke(CustomTabTest.kt:100)
at org.mozilla.focus.activity.robots.CustomTabRobotKt.customTab(CustomTabRobot.kt:65)
at org.mozilla.focus.activity.CustomTabTest.openCustomTabInFocusTest(CustomTabTest.kt:100)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by sv-ohorvath** [comment]
Logged issue for the missing menu item: https://github.com/mozilla-mobile/focus-android/issues/5084

**Comment by AndiAJ** [comment]
Failed 7x on 8/13 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5421293156066582717/executions/bs.9b91b42d8a74235b/testcases/1)

In all cases:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Open in Firefox Focus"`

**Comment by AndiAJ** [comment]
Failed again on 8/13 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7427725193328934865/executions/bs.215175ee164937f5/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7427725193328934865/executions/bs.39c373712b2ab403/testcases/1)

Flaky 1x on 8/13
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5813088404962409092/executions/bs.94af7992a176ef5b/testcases/1)
