### ISSUE TITLE
UI test failure -  MozillaSupportPagesTest#openAboutPageTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5191]
### Firebase Test Run:
**Test crashed:**
https://console.firebase.google.com/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7599832758250963621/executions/bs.3c076108a7a27ad
### Stacktrace:
`java.lang.IllegalStateException: Invalid png detected
       FATAL EXCEPTION: main
Process: org.mozilla.focus.debug, PID: 7576
java.lang.IllegalStateException: Invalid png detected
	at org.mozilla.focus.utils.HtmlLoader.loadPngAsDataURI(HtmlLoader.java:82)
	at org.mozilla.focus.browser.LocalizedContent.loadAbout(LocalizedContent.kt:49)
	at org.mozilla.focus.engine.AppContentInterceptor.onLoadRequest(AppContentInterceptor.kt:30)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.maybeInterceptRequest(GeckoEngineSession.kt:570)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:492)
	at org.mozilla.geckoview.GeckoSession.lambda$shouldLoadUri$4$GeckoSession(GeckoSession.java:1760)
	at org.mozilla.geckoview.GeckoSession$$ExternalSyntheticLambda2.run(Unknown Source:8)
	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:53)
	at org.mozilla.geckoview.GeckoSession.shouldLoadUri(GeckoSession.java:1758)
	at org.mozilla.geckoview.GeckoSession.load(GeckoSession.java:1700)
	at mozilla.components.browser.engine.gecko.GeckoEngineSession.loadUrl(GeckoEngineSession.kt:175)
	at mozilla.components.concept.engine.EngineSession.loadUrl$default(EngineSession.kt:566)
	at mozilla.components.browser.state.engine.middleware.LinkingMiddleware$performLoadOnMainThread$1.invokeSuspend(LinkingMiddleware.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:525)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:484)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:236)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:162)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:139)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:170)
	at androidx.test.espresso.action.Tap.access$100(Tap.java:31)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:47)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:137)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:366)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:255)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
  `
### Build: 
8/20. Started with this [commit](https://github.com/mozilla-mobile/focus-android/commit/0f102cd6ec9a5326f4118efd1eaa7058c13f5b92).

**Comment by sv-ohorvath** [comment]
Reported issue: https://github.com/mozilla-mobile/focus-android/issues/5185

**Comment by AndiAJ** [comment]
Failed 2 more times on 8/27 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/9091435623101485288/executions/bs.b516258ce3ed852d/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/9091435623101485288/executions/bs.4ce9a0a2f495dc82/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8771200461374037208/executions/bs.f92aa5264fb0723d/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8771200461374037208/executions/bs.eb752467574a363e/testcases/1/logs)

**Comment by AndiAJ** [comment]
Failed 2x on 8/28 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5111994848005301085/executions/bs.27c11256423b9fb/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5111994848005301085/executions/bs.60d1c71e62d78263/testcases/1/logs)

**Comment by AndiAJ** [comment]
Failed 2x on 8/30 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5998186883400506373/executions/bs.95659535e74fe6e/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5998186883400506373/executions/bs.1d52f9a2e08070f3/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5965711351299192389/executions/bs.941abbdedcf1eb11/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5965711351299192389/executions/bs.613c5cef84199e1d/testcases/1/logs)

**Comment by AndiAJ** [comment]
Failed again 4x on 8/30 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6422186711168166134/executions/bs.3efb5ea17f1ab55a/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6422186711168166134/executions/bs.af4f96b01ea627/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6163529191173936926/executions/bs.3462d2f98e8cc91c/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6163529191173936926/executions/bs.b594677c35d18fc0/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/4718985546851459947/executions/bs.c6226c4ee65ad66/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/4718985546851459947/executions/bs.1ea12f0ca24fb298/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6292561295356878379/executions/bs.1765ce9fa09f91e3/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6292561295356878379/executions/bs.4c0e1b102a600848/testcases/1/logs)

**Comment by AndiAJ** [comment]
Failed 3x on 8/31 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6083435138422544167/executions/bs.66001bf6c292822b/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6083435138422544167/executions/bs.8666d989cdd95186/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5575024507610603154/executions/bs.3e65e0f42e77d77f/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5575024507610603154/executions/bs.5e8ab2b9017ff0e4/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8319834668134171533/executions/bs.57c3a5ca1bc020d4/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8319834668134171533/executions/bs.2d8074c9cff7b9fb/testcases/1/logs)
