### ISSUE TITLE
Crash when clicking erase notification on Android 6

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#522]
STR:
1. Open Focus on Android 6
2. Start browsing
3. Tap the erase notification

Expected: data is erased
Actual: focus crashes

java.lang.RuntimeException: Unable to start service org.mozilla.focus.notification.BrowsingNotificationService@facb2d5 with Intent { act=erase cmp=org.mozilla.focus.debug/org.mozilla.focus.notification.BrowsingNotificationService }: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                                             at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
                                                                             at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                                             at android.app.ContextImpl.startActivity(ContextImpl.java:672)
                                                                             at android.app.ContextImpl.startActivity(ContextImpl.java:659)
                                                                             at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)
                                                                             at org.mozilla.focus.notification.BrowsingNotificationService.onStartCommand(BrowsingNotificationService.java:102)
                                                                             at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
                                                                             at android.app.ActivityThread.-wrap17(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

Adding Intent.FLAG_ACTIVITY_NEW_TASK fixes the crash on Android 6. I haven't test 5 or 7.0 yet.

**Comment by ahunt** [comment]
I'll keep this open until I can test across multiple Android versions. Ideally we could try to only add the flag on devices where it's needed (sebastian tested without the flag on 7.1, I've tested on Android 6 where the flag is needed, we don't know if 7.0 needs it yet).
