### ISSUE TITLE
Intermittent UI test failure - <MozillaSupportPagesTest.turnOffHomeScreenTipsTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5259]
### Firebase Test Run:
Failed 2x
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5998186883400506373/executions/bs.f66fc81bf391e1fb/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5998186883400506373/executions/bs.5393a3db96b39d0b/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5965711351299192389/executions/bs.817d8a779ff0207c/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5965711351299192389/executions/bs.edf710e07208bbbe/testcases/1)

### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=org.mozilla.focus.debug:id/homeViewTipsLabel]
at androidx.test.uiautomator.UiObject.getText(UiObject.java:564)
at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyHomeScreenTipIsDisplayed(HomeScreenRobot.kt:56)
at org.mozilla.focus.activity.MozillaSupportPagesTest$turnOffHomeScreenTipsTest$5.invoke(MozillaSupportPagesTest.kt:114)
at org.mozilla.focus.activity.MozillaSupportPagesTest$turnOffHomeScreenTipsTest$5.invoke(MozillaSupportPagesTest.kt:113)
at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:74)
at org.mozilla.focus.activity.MozillaSupportPagesTest.turnOffHomeScreenTipsTest(MozillaSupportPagesTest.kt:113)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by AndiAJ** [comment]
Failed again 4x on 8/30 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6422186711168166134/executions/bs.f5e95ba77ac834db/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6422186711168166134/executions/bs.88b8701be6d74cb8/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6163529191173936926/executions/bs.1da8ef0988f44fa8/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6163529191173936926/executions/bs.f7d325dd104d333d/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/4718985546851459947/executions/bs.398af1adcf405b0e/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/4718985546851459947/executions/bs.162ebbe34d852df2/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6292561295356878379/executions/bs.c1036a1dbd9813a4/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6292561295356878379/executions/bs.44430aaa904c7753/testcases/1)

**Comment by AndiAJ** [comment]
Failed 3x on 8/31 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6083435138422544167/executions/bs.15662609eb24c87/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6083435138422544167/executions/bs.a519441ed4c8e50d/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5575024507610603154/executions/bs.999282c00bfc48a3/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/5575024507610603154/executions/bs.e5bc458aef1966a7/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8319834668134171533/executions/bs.a6ddcfb1634bb148/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8319834668134171533/executions/bs.e423b400b17321be/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6111243237086851238/executions/bs.fa70010d58d6bd7e/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/6111243237086851238/executions/bs.49952b656d75597a/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8168972649305594143/executions/bs.de23619fbcd45caf/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8168972649305594143/executions/bs.447b41acf6395067/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7416737051515535645/executions/bs.c35e08f43feed718/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/7416737051515535645/executions/bs.a4b987d03cf4f1cf/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8317777655865343985/executions/bs.52cb4476e638f496/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/8317777655865343985/executions/bs.254f84f768f34633/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/4714140428427932453/executions/bs.f86a58363b1ac697/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fx-mobile-firebase-testlab/testlab/histories/bh.2b4ca2c7fdb2f0f0/matrices/4714140428427932453/executions/bs.90e81c020207bddf/testcases/1)
