### ISSUE TITLE
Intermittent UI test failure - <CustomTabTest.openCustomTabInFocusTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5261]
### Stacktrace:
androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 709, 735 and precision: 16, 16' on view 'with text: is "Open in Firefox Focus"'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:87)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:178)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:119)
at org.mozilla.focus.activity.robots.CustomTabRobot.clickOpenInFocusButton(CustomTabRobot.kt:57)
at org.mozilla.focus.activity.CustomTabTest$openCustomTabInFocusTest$4.invoke(CustomTabTest.kt:106)
at org.mozilla.focus.activity.CustomTabTest$openCustomTabInFocusTest$4.invoke(CustomTabTest.kt:102)
at org.mozilla.focus.activity.robots.CustomTabRobotKt.customTab(CustomTabRobot.kt:82)
at org.mozilla.focus.activity.CustomTabTest.openCustomTabInFocusTest(CustomTabTest.kt:102)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: java.lang.RuntimeException: Unable to stop activity {org.mozilla.focus.debug/org.mozilla.focus.activity.CustomTabActivity}: java.lang.RuntimeException: Failed to call observer method
at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4151)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4121)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4196)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:192)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)
at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:525)
at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:484)
at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:468)
at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:51)
at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:137)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:366)
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:255)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: Failed to call observer method
at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
at androidx.lifecycle.ReportFragment.onStop(ReportFragment.java:128)
at android.app.Fragment.performStop(Fragment.java:2736)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1360)
at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
at android.app.FragmentManagerImpl.dispatchStop(FragmentManager.java:3016)
at android.app.FragmentController.dispatchStop(FragmentController.java:226)
at android.app.Activity.performStop(Activity.java:7364)
at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4143)
... 27 more
Caused by: java.lang.IllegalArgumentException: Display not attached
at org.mozilla.geckoview.GeckoSession.releaseDisplay(GeckoSession.java:2368)
at org.mozilla.geckoview.GeckoView.releaseSession(GeckoView.java:408)
at mozilla.components.browser.engine.gecko.GeckoEngineView.release(GeckoEngineView.kt:155)
at mozilla.components.feature.session.engine.EngineViewPresenter.stop(EngineViewPresenter.kt:54)
at mozilla.components.feature.session.SessionFeature.stop(SessionFeature.kt:55)
at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.stop$support_base_release(ViewBoundFeatureWrapper.kt:185)
at mozilla.components.support.base.feature.LifecycleBinding.stop(ViewBoundFeatureWrapper.kt:220)
at java.lang.reflect.Method.invoke(Native Method)
at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
... 47 more

**Comment by sv-ohorvath** [comment]
> Failed 4x on 10/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8515613108131075619/executions/bs.22633528c9a887ef/testcases/1) [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8515613108131075619/executions/bs.c401ebb29575e61b/testcases/1/test-cases) [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6123382218494955745/executions/bs.b7827a686023572b/testcases/1) [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6123382218494955745/executions/bs.6c387f393ddbe9e0/testcases/1) [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8605318427067691866/executions/bs.719e96534aea8410/testcases/1) [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8605318427067691866/executions/bs.72c73aa5ee294e69/testcases/1) [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5554199495789204369/executions/bs.e49acc553ed60d43/testcases/1) [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5554199495789204369/executions/bs.72029010447660dc/testcases/1)
> 
> `androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.focus.debug:id/tabs`

Open issue to fix this by Ionut: https://github.com/mozilla-mobile/focus-android/issues/5755

**Comment by AndiAJ** [comment]
Failed again on 11/04 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5278022112031714428/executions/bs.7e39e5723feca141/testcases/1/logs)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5278022112031714428/executions/bs.5bce174f4967ff64/testcases/1/logs)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/4 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8051717352779090592/executions/bs.4fc1f2b72c2695f2/testcases/1/logs)

**Comment by sv-ohorvath** [comment]
The test was fixed and re-enabled in https://github.com/mozilla-mobile/focus-android/pull/5771
