### ISSUE TITLE
Upon selecting "New session" on the fingerprint verification, Focus crashes when exiting Settings menu

### ISSUE THREAD

**Issue by delia-pop** [mozilla-mobile/focus-android#5299]
## Steps to reproduce
Preconditions: Create and enable fingerprint ID on your device.
1. Go to Settings -> Privacy and Security -> Switching Apps section.
2. Tap "Use fingerprint to unlock app."
3. Exit Settings menu and open a page. 
Minimize and restore the app.
4. On the fingerprint verification window tap "New session".
5. Go to Settings
Exit Settings menu

### Expected behavior
The app should remain stable when returning to the homescreen.

### Actual behavior
The browser remains blank, and if tapping on the search bar or 3 dot menu, the crash reporter is displayed.

`--------- beginning of crash
2021-09-01 16:58:55.193 18933-18933/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus, PID: 18933
    java.lang.NullPointerException
        at org.mozilla.focus.menu.browser.BlockingItemViewHolder.<init>(BlockingItemViewHolder.kt:7)
        at org.mozilla.focus.menu.browser.BrowserMenuAdapter.onCreateViewHolder(BrowserMenuAdapter.kt:13)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:120)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:121)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.cardview.widget.CardView.onMeasure(CardView.java:1)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3286)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1986)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2315)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8496)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
        at android.view.Choreographer.doCallbacks(Choreographer.java:764)
        at android.view.Choreographer.doFrame(Choreographer.java:699)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2021-09-01 16:58:55.194 18933-18933/? E/ExceptionHandler: Uncaught exception handled: 
    java.lang.NullPointerException
        at org.mozilla.focus.menu.browser.BlockingItemViewHolder.<init>(BlockingItemViewHolder.kt:7)
        at org.mozilla.focus.menu.browser.BrowserMenuAdapter.onCreateViewHolder(BrowserMenuAdapter.kt:13)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:120)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:121)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.cardview.widget.CardView.onMeasure(CardView.java:1)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:24973)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3286)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1986)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2315)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8496)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
        at android.view.Choreographer.doCallbacks(Choreographer.java:764)
        at android.view.Choreographer.doFrame(Choreographer.java:699)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2021-09-01 16:58:55.194 18933-18933/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(timestamp=1630504735194, throwable=java.lang.NullPointerException, breadcrumbs=[], uuid=1f41babc-2a7f-48ba-a1bd-82edf738ec34)
2021-09-01 16:58:55.214 18933-18933/? I/mozac/CrashReporter: Showing prompt`
### Device information

* Android device: Huawei P9 Lite (Android 8) ; Huawei P20 (Android 10); Samsung Galaxy Note 8 (Android 9)
* Focus version: Release 91.4.0 (Build 352421903) ; Debug Build 93.0 (Build 11)/ 93.0a1-20210824094724

**Comment by eliserichards** [comment]
I can also reproduce this on my Pixel 3: 
<img width="333" alt="image" src="https://user-images.githubusercontent.com/43795363/131922050-47afc6fc-8d15-4051-b549-251a648f7308.png">

**Comment by eliserichards** [comment]
(whoops)

**Comment by lobontiumira** [comment]
Verified as fixed on the 93.0 build 11-GV 93.0a1-20210906031657 with OnePlus 5T (Android 9), and Samsung Galaxy Note 8 (Android 9).
