### ISSUE TITLE
Crash when starting service

### ISSUE THREAD

**Issue by ahunt** [mozilla-mobile/focus-android#535]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
                                                                             at org.mozilla.focus.notification.BrowsingNotificationService.onStartCommand(BrowsingNotificationService.java:72)
                                                                             at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)

See e.g.:
https://dashboard.buddybuild.com/apps/584f67f6f3d6eb01000842d6/crashreport/1aac0417ca325fe685485864848573a5

I've actually hit this a few times almost immediately after starting a browsing session. Sometimes it happens later when I've switched to a different app.

**Comment by ahunt** [comment]
Hidden under START_STICKY docs (!?):
" if there are not any pending start commands to be delivered to the service, it [onStartCommand] will be called with a null intent object"
https://developer.android.com/reference/android/app/Service.html#START_STICKY

**Comment by pocmo** [comment]
I think the way I used STICKY / NOT_STICKY doesn't really make sense. Instead I would like to "run the service in foreground" with a notification attached (and stop foreground once the session is destroyed).

**Comment by ahunt** [comment]
This should be resolved since c278f812fca9f902c4c91ccbb265e00d91bd7809 just landed!
