### ISSUE TITLE
UI test failure in verifyPageSecurityIconAndInfo

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5471]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6999969217828846406/executions/bs.bc0118f074f2653b/testcases/1
### Stacktrace:
`androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
Got: "TrackingProtectionIconView{id=2131362160, res-name=mozac_browser_toolbar_tracking_protection_indicator, desc=Tracking Protection has blocked trackers, visibility=GONE, width=110, height=110, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@d781f93, tag=null, root-is-layout-requested=false, has-input-connection=false, x=22.0, y=22.0}"
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:324)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
at org.mozilla.focus.activity.robots.BrowserRobot.verifySiteSecurityIconShown(BrowserRobot.kt:142)`

**Comment by AaronMT** [comment]
Should be fixed with https://github.com/mozilla-mobile/focus-android/pull/5439 - re-open if it appears again
