### ISSUE TITLE
Clicking the secure/ETP icon in a Custom Tab crashes

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5473]
## Steps to reproduce
1. Set Focus as the default browser.
2. Clear app data for Focus.
1. Open a site in a Custom Tab.
2. Click on the secure lock or the ETP icon (which ever shows up first)

### Expected behavior
- You see the site security/ETP panel.

### Actual behavior
- 💥

### Device information

* Android device: Pixel 3
* Focus version: `main` from 2 days ago (sorry, filling on mobile, will update later if needed)

**Comment by mcarare** [comment]
I can't seem to reproduce this with on the latest master, with opening a custom tab from youtube. 
@jonalmeida Is there a specific page you have opened?

**Comment by jonalmeida** [comment]
There wasn't a specific page. I'm still able to reproduce this:

```
2021-09-27 18:12:21.723 27701-27701/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.debug, PID: 27701
    android.view.InflateException: Binary XML file line #39 in org.mozilla.focus.debug:layout/dialog_tracking_protection_sheet: Binary XML file line #39 in org.mozilla.focus.debug:layout/dialog_tracking_protection_sheet: Error inflating class com.google.android.material.textview.MaterialTextView
    Caused by: android.view.InflateException: Binary XML file line #39 in org.mozilla.focus.debug:layout/dialog_tracking_protection_sheet: Error inflating class com.google.android.material.textview.MaterialTextView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at org.mozilla.focus.databinding.DialogTrackingProtectionSheetBinding.inflate(DialogTrackingProtectionSheetBinding.java:93)
        at org.mozilla.focus.settings.privacy.TrackingProtectionPanel.<init>(TrackingProtectionPanel.kt:36)
        at org.mozilla.focus.fragment.BrowserFragment.showTrackingProtectionPanel(BrowserFragment.kt:809)
        at org.mozilla.focus.browser.integration.BrowserToolbarIntegration$2.invoke(BrowserToolbarIntegration.kt:107)
        at org.mozilla.focus.browser.integration.BrowserToolbarIntegration$2.invoke(BrowserToolbarIntegration.kt:105)
        at mozilla.components.browser.toolbar.display.DisplayToolbar.setOnTrackingProtectionClickedListener$lambda-3(DisplayToolbar.kt:279)
        at mozilla.components.browser.toolbar.display.DisplayToolbar.$r8$lambda$yNwfQYFAPQK_eeORzsWYmNCAw9Y(Unknown Source:0)
        at mozilla.components.browser.toolbar.display.DisplayToolbar$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.UnsupportedOperationException: Can't convert to ComplexColor: type=0x1
        at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1152)
        at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1028)
        at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1107)
        at android.content.res.Resources.loadColorStateList(Resources.java:1139)
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:600)
        at android.widget.TextView.readTextAppearance(TextView.java:4006)
        at android.widget.TextView.<init>(TextView.java:1093)
        at android.widget.TextView.<init>(TextView.java:994)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:102)
        at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:93)

```

I see now that it doesn't reproduce with all Custom Tab apps like Gmail, but I'm able to consistently reproduce it with [another third party client](https://play.google.com/store/apps/details?id=com.leavjenn.hews).

**Comment by jonalmeida** [comment]
Ah ha! You have to clear app data of Focus and then it crashes. (updating the STR above).

**Comment by lobontiumira** [comment]
Verified as fixed on the latest debug build from main from 9/30 (build 11 GV 94.0a1-20210927093458) with Sony Xperia Z5 Premium (Android 7.1.1), and Lenovo Tab M10 (Android 10).
