### ISSUE TITLE
WebViewDataTest fails with whitelist error

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/focus-android#551]
java.lang.AssertionError

java.lang.AssertionError: Check 'app_textures' is in whitelist
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.mozilla.focus.activity.WebViewDataTest.DeleteWebViewDataTest(WebViewDataTest.java:195)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethodX1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
	at android.support.test.rule.ActivityTestRuleXActivityStatement.evaluate(ActivityTestRule.java:270)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunnerX3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunnerX1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.accessX000(ParentRunner.java:58)
	at org.junit.runners.ParentRunnerX2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunnerX3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunnerX1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.accessX000(ParentRunner.java:58)
	at org.junit.runners.ParentRunnerX2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.InstrumentationXInstrumentationThread.run(Instrumentation.java:1879)

**Comment by npark-mozilla** [comment]
Hmm, looks like the dataDir has everything that whitelist contains.  The content of dataDir.list() is:
0 = {File@5590} "/data/user/0/org.mozilla.focus.debug/cache"
1 = {File@5591} "/data/user/0/org.mozilla.focus.debug/code_cache"
2 = {File@5592} "/data/user/0/org.mozilla.focus.debug/shared_prefs"
3 = {File@5593} "/data/user/0/org.mozilla.focus.debug/telemetry"
4 = {File@5594} "/data/user/0/org.mozilla.focus.debug/app_webview"
5 = {File@5595} "/data/user/0/org.mozilla.focus.debug/app_textures"
6 = {File@5596} "/data/user/0/org.mozilla.focus.debug/databases"
7 = {File@5597} "/data/user/0/org.mozilla.focus.debug/app_dxmaker_cache"

**Comment by npark-mozilla** [comment]
@pocmo should we investigate this failure before release?  If it's just a test issue, we can disable the run for now.  What do you think?

**Comment by pocmo** [comment]
Yep. I want to fix this before release. I want to investigate a bit what "app_textures" actually contains and whether there's anything related to the browser session in there. Basically I need to answer: Do we need to truncate it or can we just add it to the whitelist?

**Comment by pocmo** [comment]
I can't find any information what actually gets stored inside app_textures. The folder gets created on my device but not on an emulator. However it seems to be always empty - So I'm going to add it to the whitelist and assert that it's empty.
