### ISSUE TITLE
Invalid drawable tag gradient

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/focus-android#5579]
## Steps to reproduce
Run app on api 22
### Expected behavior
Main screen app should be displayed with success at run
### Actual behavior
App crash with error: Binary XML file line #19: invalid drawable tag gradient
Tag used in wordmark2 vector
### Device information

* Android device: Pixel 2 Api 22
* Focus version: 95.0

**Comment by lobontiumira** [comment]
I reproduced this crash on Xiaomi mi4i (Android 5.0.2) on Beta 94.0.0-beta.1:

```
2021-10-15 17:19:47.516 7958-7958/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(timestamp=1634307587529, throwable=android.view.InflateException: Binary XML file line #40: Error inflating class androidx.appcompat.widget.AppCompatImageView, breadcrumbs=[], uuid=c7ca48a5-ab15-45f5-9e1c-6686e2cff1e7)
2021-10-15 17:19:47.586 7958-7958/? I/mozac/CrashReporter: Showing prompt
2021-10-15 17:19:47.586 7958-7958/? I/Timeline: Timeline: Activity_launch_request time:372945
2021-10-15 17:19:47.596 7520-7760/? I/mozac/CrashReporter: Crash report submitted to 1 telemetry services
2021-10-15 17:19:47.606 943-1781/? I/ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.focus.beta/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10002 on display 0
2021-10-15 17:19:47.606 943-1781/? W/CustomizeUtil: no getRealSize hack method
2021-10-15 17:19:47.606 943-1781/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
2021-10-15 17:19:47.616 7958-7958/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.beta, PID: 7958
    android.view.InflateException: Binary XML file line #40: Error inflating class androidx.appcompat.widget.AppCompatImageView
        at android.view.LayoutInflater.createView(LayoutInflater.java:637)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
        at org.mozilla.focus.fragment.UrlInputFragment.onCreateView(UrlInputFragment.kt:1)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:16)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5253)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:611)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
        at org.mozilla.focus.fragment.UrlInputFragment.onCreateView(UrlInputFragment.kt:1) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:16) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5253) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708) 
     Caused by: android.content.res.Resources$NotFoundException: File res/yX.xml from drawable resource ID #0x7f080198
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2478)
        at android.content.res.Resources.loadDrawable(Resources.java:2370)
        at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:394)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:751)
        at android.widget.ImageView.<init>(ImageView.java:146)
        at android.widget.ImageView.<init>(ImageView.java:135)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:3)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:2)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
        at org.mozilla.focus.fragment.UrlInputFragment.onCreateView(UrlInputFragment.kt:1) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:16) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5253) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708) 
     Caused by: android.content.res.Resources$NotFoundException: File res/Fi.xml from color state list resource ID #0x7f080043
        at android.content.res.Resources.loadColorStateList(Resources.java:2591)
        at android.content.res.TypedArray.getColor(TypedArray.java:397)
        at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1442)
        at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
        at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
        at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1097)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1019)
        at android.content.res.Resources.createFromXml(Resources.java:2783)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2464)
        at android.content.res.Resources.loadDrawable(Resources.java:2370) 
        at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:394) 
        at android.content.res.TypedArray.getDrawable(TypedArray.java:751) 
        at android.widget.ImageView.<init>(ImageView.java:146) 
        at android.widget.ImageView.<init>(ImageView.java:135) 
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:3) 
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:2) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
        at org.mozilla.focus.fragment.UrlInputFragment.onCreateView(UrlInputFragment.kt:1) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:16) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5253) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #20: invalid drawable tag gradient
        at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:148)
        at android.content.res.ColorStateList.createFromXml(ColorStateList.java:131)
        at android.content.res.Resources.loadColorStateList(Resources.java:2587)
        at android.content.res.TypedArray.getColor(TypedArray.java:397) 
        at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1442) 
        at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421) 
        at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542) 
        at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458) 
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1097) 
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1019) 
        at android.content.res.Resources.createFromXml(Resources.java:2783) 
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2464) 
        at android.content.res.Resources.loadDrawable(Resources.java:2370) 
        at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:394) 
        at android.content.res.TypedArray.getDrawable(TypedArray.java:751) 
        at android.widget.ImageView.<init>(ImageView.java:146) 
        at android.widget.ImageView.<init>(ImageView.java:135) 
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:3) 
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:2) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
        at org.mozilla.focus.fragment.UrlInputFragment.onCreateView(UrlInputFragment.kt:1) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:16) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5253) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708) 
2021-10-15 17:19:47.626 1443-1586/? I/WtProcessController: Receive am_crash event for pid: 7958 pkg = org.mozilla.focus.beta
2021-10-15 17:19:47.626 1443-1586/? W/KloServer: Aborted broadcast does not supprt for: org.mozilla.focus.beta
2021-10-15 17:19:47.636 7958-7958/? I/Process: Sending signal. PID: 7958 SIG: 9
2021-10-15 17:19:47.726 1604-1604/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.auth.account.workaccount.START cmp=com.google.android.gms/.chimera.PersistentApiService }
2021-10-15 17:19:47.726 1604-1604/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.auth.account.workaccount.START cmp=com.google.android.gms/.chimera.PersistentApiService }
2021-10-15 17:19:47.736 943-1750/? W/ActivityManager: getRunningAppProcesses: caller 10009 is using old GET_TASKS but privileged; allowing
2021-10-15 17:19:47.736 1248-1267/? D/DownloadManager: call insert is com.google.android.gm pid=4936 uid=10091
2021-10-15 17:19:47.746 943-1580/? W/ActivityManager: getTasks: caller 10009 is using old GET_TASKS but privileged; allowing
2021-10-15 17:19:47.776 1248-1547/? I/DownloadService: updateLocked enter 
2021-10-15 17:19:47.786 1248-1248/? D/DMS_DownloadService: onStartCommand --->startId=13 cmd=0
2021-10-15 17:19:47.836 943-1867/? D/GraphicsStats: Buffer count: 6
2021-10-15 17:19:47.836 943-1848/? I/ActivityManager: Process org.mozilla.focus.beta (pid 7958) has died
2021-10-15 17:19:47.836 1248-1547/? I/PkgThreadPoolExecutor: addQueue mId=3672 pkg=com.google.android.gm runCount=1 mWorks={java.util.concurrent.FutureTask@35bf5ff6=>mId=3672}
2021-10-15 17:19:47.836 943-1848/? D/ActivityManager: cleanUpApplicationRecord -- 7958
2021-10-15 17:19:47.836 1248-1547/? I/DownloadService: updateLocked enter 
2021-10-15 17:19:47.836 943-1848/? I/AutoStartManagerService: MIUILOG- Reject RestartService packageName :org.mozilla.focus.beta uid : 10002
2021-10-15 17:19:47.846 943-962/? I/WindowState: WIN DEATH: Window{28d5a7fb u0 org.mozilla.focus.beta/org.mozilla.focus.activity.MainActivity}
2021-10-15 17:19:47.856 8021-8021/? I/art: System.exit called, status: 0
2021-10-15 17:19:47.856 8021-8021/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
2021-10-15 17:19:47.866 1443-1586/? I/WtProcessController: MOVE TO FOREGROUND: org.mozilla.focus.beta 10002
2021-10-15 17:19:47.876 1443-1586/? I/StatusController: Last foreground:org.mozilla.focus.beta uid:10002 Current foreground:org.mozilla.focus.beta uid:10002
2021-10-15 17:19:47.876 1443-1586/? I/WtProcessController: FOREGROUND INFO: name=org.mozilla.focus.beta uid=10002 pid=7545 TaskId:9
2021-10-15 17:19:47.876 943-1848/? I/Timeline: Timeline: App_transition_ready time:373237
2021-10-15 17:19:47.886 943-1781/? I/Timeline: Timeline: App_transition_ready time:373243
2021-10-15 17:19:47.896 6074-6074/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1333 android.content.ContextWrapper.sendBroadcast:386 android.content.ContextWrapper.sendBroadcast:386 com.android.settings.device.UpdateBroadcastManager.bn:27 com.android.settings.MiuiSettingsReceiver.onReceive:187 
2021-10-15 17:19:47.906 943-1867/? D/WifiService: acquireWifiLockLocked: WifiLock{DownloadManager type=3 binder=android.os.BinderProxy@1ad9d4de}
2021-10-15 17:19:47.906 943-1602/? I/Timeline: Timeline: App_transition_ready time:373267
2021-10-15 17:19:47.906 1248-8336/? D/DownloadThread: in runInternal, Download mId=3672 uri=https://mail.google.com/mail/?ui=2&ik=1ccf02652d&attid=0.2&th=17c5f9caff0786bc&view=att&realattid=17caa46947c7d3b07fc4&zw
2021-10-15 17:19:47.916 1248-8336/? D/DownloadThread: in runInternal NetworkInfo=[type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: "Orange-UM45", roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]
2021-10-15 17:19:47.926 1869-1869/? I/Launcher.ApplicationsMessage: onReceive
2021-10-15 17:19:47.926 1869-1869/? I/Launcher.ApplicationsMessage: update com.android.settings/ to 
2021-10-15 17:19:47.946 943-1012/? I/Timeline: Timeline: App_transition_ready time:373303
2021-10-15 17:19:47.946 943-1012/? I/Timeline: Timeline: App_transition_ready time:373307
2021-10-15 17:19:47.956 943-1012/? I/Timeline: Timeline: App_transition_ready time:373311
```
