### ISSUE TITLE
RequestException  Error sending request: The rust-components network backend must be initialized before use

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#5781]
https://sentry.prod.mozaws.net/operations/focus-android-nightly/issues/14541587/?query=is%3Aunresolved

```
org.mozilla.experiments.nimbus.internal.RequestException: Error sending request: The rust-components network backend must be initialized before use!
    at org.mozilla.experiments.nimbus.internal.NimbusException$ErrorHandler$lift$1.invoke(nimbus.kt:16)
    at org.mozilla.experiments.nimbus.internal.NimbusKt.liftFromRustBuffer(nimbus.kt:2)
    at org.mozilla.experiments.nimbus.internal.NimbusException$ErrorHandler.lift(nimbus.kt:2)
    at org.mozilla.experiments.nimbus.internal.NimbusClient.fetchExperiments(nimbus.kt:19)
    at org.mozilla.experiments.nimbus.Nimbus$fetchExperimentsOnThisThread$1.invoke(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.withCatchAll(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.fetchExperimentsOnThisThread$nimbus_release(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus$fetchExperiments$1.invokeSuspend(Nimbus.kt:2)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by jonalmeida** [comment]
We didn't need to do `RustHttpConfig.setClient(lazy { components.core.client })` before when using Glean because we were providing the [HttpClient directly](https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt#L68) to it.

With Nimbus, it seems like we need to use the `RustHttpConfig` way.

**Comment by jonalmeida** [comment]
Native components don't see to support private connections. I'm not sure what the value would be out of this for things like Nimbus. 
```
org.mozilla.experiments.nimbus.internal.NimbusException$RequestException: Error sending request: [no-sentry] Network error: Java error: "fetch error: Non-private request"
        at org.mozilla.experiments.nimbus.internal.NimbusException$ErrorHandler.read(nimbus.kt:1163)
        at org.mozilla.experiments.nimbus.internal.NimbusException$ErrorHandler$lift$1.invoke(nimbus.kt:1146)
        at org.mozilla.experiments.nimbus.internal.NimbusException$ErrorHandler$lift$1.invoke(nimbus.kt:1146)
        at org.mozilla.experiments.nimbus.internal.NimbusKt.liftFromRustBuffer(nimbus.kt:182)
        at org.mozilla.experiments.nimbus.internal.NimbusException$ErrorHandler.lift(nimbus.kt:1146)
        at org.mozilla.experiments.nimbus.internal.NimbusException$ErrorHandler.lift(nimbus.kt:1144)
        at org.mozilla.experiments.nimbus.internal.NimbusClient.fetchExperiments(nimbus.kt:2095)
        at org.mozilla.experiments.nimbus.Nimbus$fetchExperimentsOnThisThread$1.invoke(Nimbus.kt:429)
        at org.mozilla.experiments.nimbus.Nimbus$fetchExperimentsOnThisThread$1.invoke(Nimbus.kt:427)
```

For now, using an unwrapped client.
