### ISSUE TITLE
Intermittent UI test failure - < SettingsTest. verifyGeneralSettingsMenuTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5788]
### Firebase Test Run:
Failed on Nightly 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/9132632964294850166/executions/bs.8b98c46b592bab5f/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/9132632964294850166/executions/bs.250e7c630e0e6561/testcases/1)

Failed on Beta 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/8406837912782968060/executions/bs.2c64074790efb593/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/8406837912782968060/executions/bs.fbd329ba43948b7/testcases/1)

### Stacktrace:
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Make Firefox Focus default browser"

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x10302f8
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@b815254, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+-->ViewStub{id=16908682, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@e1dd5fd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+-->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@89562f2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+--->FitWindowsLinearLayout{id=2131361846, res-name=action_bar_root, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7cb3fc0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+---->ViewStubCompat{id=2131361858, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d76d4f9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@212bc3e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+----->FrameLayout{id=2131361940, res-name=container, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@d493a9f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+------>LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@e0497ec, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3} 
|
+------->View{id=2131362340, res-name=status_bar_background, visibility=VISIBLE, width=1080, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@ac6c7b5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+------->Toolbar{id=2131362392, res-name=toolbar, visibility=VISIBLE, width=1080, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@27a5e4a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=66.0, child-count=3} 
|
+-------->AppCompatTextView{id=-1, visibility=VISIBLE, width=190, height=74, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@e10e1bb, tag=null, root-is-layout-requested=false, has-input-connection=false, x=198.0, y=40.0, text=General, input-type=0, ime-target=false, has-links=false} 
|
+-------->AppCompatImageButton{id=-1, desc=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‏‏‏‏‎‏‎‎‎‏‏‎‏‎‎‎‏‏‎‎‎‏‏‏‏‎‏‎‎‎‎‏‏‎‏‏‎‏‎‎‏‎‎‏‎‎‎‎‎‎‏‎‏‎‎‎‎‏‏‏‎‎‎‎‎Navigate up‎‏‎‎‏‎, visibility=VISIBLE, width=154, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@39946d8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+-------->ActionMenuView{id=-1, visibility=VISIBLE, width=0, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@ee92a31, tag=null, root-is-layout-requested=false, has-input-connection=false, x=1080.0, y=0.0, child-count=0} 
|
+------->FrameLayout{id=16908351, res-name=list_container, visibility=VISIBLE, width=1080, height=1568, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@7081516, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=220.0, child-count=1} 
|
+-------->RecyclerView{id=2131362249, res-name=recycler_view, visibility=VISIBLE, width=1080, height=1568, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@9e1de97, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=6} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@af5386d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=992, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@55bcd33, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=135, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@90e18f0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Theme, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@39ee69, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d84b0ee, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
|
+--------->ConstraintLayout{id=0, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@453d41c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=147.0, child-count=3} 
|
+---------->AppCompatRadioButton{id=2131362245, res-name=radio_button, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@bfa0825, tag=null, root-is-layout-requested=false, has-input-connection=false, x=50.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=false} 
|
+---------->AppCompatTextView{id=2131362387, res-name=title, visibility=VISIBLE, width=810, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@98eedfa, tag=null, root-is-layout-requested=false, has-input-connection=false, x=226.0, y=37.0, text=Light, input-type=0, ime-target=false, has-links=false} 
|
+---------->AppCompatTextView{id=2131362432, res-name=widget_summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@7b9afab, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+--------->ConstraintLayout{id=0, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@2e801a1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=279.0, child-count=3} 
|
+---------->AppCompatRadioButton{id=2131362245, res-name=radio_button, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@cdefc6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=50.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=false} 
|
+---------->AppCompatTextView{id=2131362387, res-name=title, visibility=VISIBLE, width=810, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@fe19b87, tag=null, root-is-layout-requested=false, has-input-connection=false, x=226.0, y=37.0, text=Dark, input-type=0, ime-target=false, has-links=false} 
|
+---------->AppCompatTextView{id=2131362432, res-name=widget_summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@1dc8ab4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+--------->ConstraintLayout{id=0, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@a94252, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=411.0, child-count=3} 
|
+---------->AppCompatRadioButton{id=2131362245, res-name=radio_button, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@7b26923, tag=null, root-is-layout-requested=false, has-input-connection=false, x=50.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=true} 
|
+---------->AppCompatTextView{id=2131362387, res-name=title, visibility=VISIBLE, width=810, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@7119e20, tag=null, root-is-layout-requested=false, has-input-connection=false, x=226.0, y=37.0, text=Follow device theme, input-type=0, ime-target=false, has-links=false} 
|
+---------->AppCompatTextView{id=2131362432, res-name=widget_summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@d6e43d9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=200, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@c38747f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=543.0, child-count=2} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=992, height=200, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c27c4c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=193, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@3764495, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Language, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=VISIBLE, width=275, height=53, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@27ec9aa, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=103.0, text=System default, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4e9d99b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@c11138, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=743.0, child-count=2} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=832, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@cd7d676, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=799, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@827477, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Make Firefox Focus Beta default browser, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@21208e4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=VISIBLE, width=160, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4bb714d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=876.0, y=0.0, child-count=1} 
|
+----------->SwitchMaterial{id=2131362352, res-name=switch_widget, visibility=VISIBLE, width=128, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@ee2e402, tag=null, root-is-layout-requested=false, has-input-connection=false, x=32.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=false} 
|
+->View{id=16908336, res-name=navigationBarBackground, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@39fe113, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1788.0} 
|
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
	at org.mozilla.focus.activity.robots.SettingsGeneralMenuRobot.verifyGeneralSettingsItems(SettingsGeneralMenuRobot.kt:31)
	at org.mozilla.focus.activity.SettingsTest$verifyGeneralSettingsMenuTest$4.invoke(SettingsTest.kt:38)
	at org.mozilla.focus.activity.SettingsTest$verifyGeneralSettingsMenuTest$4.invoke(SettingsTest.kt:37)
	at org.mozilla.focus.activity.robots.SettingsRobot$Transition.openGeneralSettingsMenu(SettingsRobot.kt:47)
	at org.mozilla.focus.activity.robots.SettingsRobot$Transition.openGeneralSettingsMenu$default(SettingsRobot.kt:40)
	at org.mozilla.focus.activity.SettingsTest.verifyGeneralSettingsMenuTest(SettingsTest.kt:37)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by AndiAJ** [comment]
Failed again on Nightly 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/8130042195649987749/executions/bs.582ec023e1d42624/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/8130042195649987749/executions/bs.c820f29179ca8656/testcases/1)

Failed again on Beta 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6437334817384491805/executions/bs.19c4889acf6c629b/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6437334817384491805/executions/bs.aa0fc5b4b4dc966f/testcases/1)

**Comment by AndiAJ** [comment]
Failed again on Nightly 11/5
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/5942929985767786832/executions/bs.dd153e0812b3b40a/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/5942929985767786832/executions/bs.884ddb6952ab0701/testcases/1)

Failed again on Beta 11/5
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6532684864662653779/executions/bs.ecadb8eeffe797d1/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6532684864662653779/executions/bs.ade6a5a0d1ce1d52/testcases/1)
