### ISSUE TITLE
Intermittent UI test failure - < SetDefaultBrowserTest.changeDefaultBrowserTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5789]
### Firebase Test Run:
Failed on Nightly 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/9132632964294850166/executions/bs.ce3d3e71c67628ec/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/9132632964294850166/executions/bs.902b2c550ea37ebd/testcases/1)

Failed on Beta 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/8406837912782968060/executions/bs.18ae00cf6bd98241/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/8406837912782968060/executions/bs.a6248e768d145269/testcases/1)

### Stacktrace:
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Make Firefox Focus default browser"

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x10302f8
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@1cff475, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+-->ViewStub{id=16908682, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@984ec0a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+-->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@73fbc7b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+--->FitWindowsLinearLayout{id=2131361846, res-name=action_bar_root, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3862f1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+---->ViewStubCompat{id=2131361858, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d8dbed6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@503a557, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+----->FrameLayout{id=2131361940, res-name=container, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7381844, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+------>LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@2df3d2d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3} 
|
+------->View{id=2131362340, res-name=status_bar_background, visibility=VISIBLE, width=1080, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b7ef262, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+------->Toolbar{id=2131362392, res-name=toolbar, visibility=VISIBLE, width=1080, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@cb33ff3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=66.0, child-count=3} 
|
+-------->AppCompatTextView{id=-1, visibility=VISIBLE, width=190, height=74, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@ec074b0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=198.0, y=40.0, text=General, input-type=0, ime-target=false, has-links=false} 
|
+-------->AppCompatImageButton{id=-1, desc=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‏‏‏‏‎‏‎‎‎‏‏‎‏‎‎‎‏‏‎‎‎‏‏‏‏‎‏‎‎‎‎‏‏‎‏‏‎‏‎‎‏‎‎‏‎‎‎‎‎‎‏‎‏‎‎‎‎‏‏‏‎‎‎‎‎Navigate up‎‏‎‎‏‎, visibility=VISIBLE, width=154, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@b9f7f29, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+-------->ActionMenuView{id=-1, visibility=VISIBLE, width=0, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@e5dd2ae, tag=null, root-is-layout-requested=false, has-input-connection=false, x=1080.0, y=0.0, child-count=0} 
|
+------->FrameLayout{id=16908351, res-name=list_container, visibility=VISIBLE, width=1080, height=1568, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4b7e84f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=220.0, child-count=1} 
|
+-------->RecyclerView{id=2131362249, res-name=recycler_view, visibility=VISIBLE, width=1080, height=1568, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7302bdc, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=6} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@a386bba, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=992, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@58229c8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=135, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@9d6ea61, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Theme, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@3f18986, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@9629247, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
|
+--------->ConstraintLayout{id=0, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@836cb9d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=147.0, child-count=3} 
|
+---------->AppCompatRadioButton{id=2131362245, res-name=radio_button, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@9ccb812, tag=null, root-is-layout-requested=false, has-input-connection=false, x=50.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=false} 
|
+---------->AppCompatTextView{id=2131362387, res-name=title, visibility=VISIBLE, width=810, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@c2c0be3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=226.0, y=37.0, text=Light, input-type=0, ime-target=false, has-links=false} 
|
+---------->AppCompatTextView{id=2131362432, res-name=widget_summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@ef269e0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+--------->ConstraintLayout{id=0, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@8ba435e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=279.0, child-count=3} 
|
+---------->AppCompatRadioButton{id=2131362245, res-name=radio_button, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@89833f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=50.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=false} 
|
+---------->AppCompatTextView{id=2131362387, res-name=title, visibility=VISIBLE, width=810, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@244440c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=226.0, y=37.0, text=Dark, input-type=0, ime-target=false, has-links=false} 
|
+---------->AppCompatTextView{id=2131362432, res-name=widget_summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@114d155, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+--------->ConstraintLayout{id=0, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@d1d145b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=411.0, child-count=3} 
|
+---------->AppCompatRadioButton{id=2131362245, res-name=radio_button, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@af794f8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=50.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=true} 
|
+---------->AppCompatTextView{id=2131362387, res-name=title, visibility=VISIBLE, width=810, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@a9e2dd1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=226.0, y=37.0, text=Follow device theme, input-type=0, ime-target=false, has-links=false} 
|
+---------->AppCompatTextView{id=2131362432, res-name=widget_summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@7f56036, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=200, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@18d08a4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=543.0, child-count=2} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=992, height=200, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@486d60d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=193, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@daf49c2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Language, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=VISIBLE, width=275, height=53, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@a27b3d3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=103.0, text=System default, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@3e40b10, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@1d7c609, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=743.0, child-count=2} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=832, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@62fba2f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=799, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@c66c83c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Make Firefox Focus Beta default browser, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@32db9c5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=VISIBLE, width=160, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c704f1a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=876.0, y=0.0, child-count=1} 
|
+----------->SwitchMaterial{id=2131362352, res-name=switch_widget, visibility=VISIBLE, width=128, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c07ca4b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=32.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=false} 
|
+->View{id=16908336, res-name=navigationBarBackground, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@ff62c28, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1788.0} 
|
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
	at org.mozilla.focus.activity.robots.SettingsGeneralMenuRobot.clickSetDefaultBrowser(SettingsGeneralMenuRobot.kt:37)
	at org.mozilla.focus.activity.SetDefaultBrowserTest$changeDefaultBrowserTest$4.invoke(SetDefaultBrowserTest.kt:27)
	at org.mozilla.focus.activity.SetDefaultBrowserTest$changeDefaultBrowserTest$4.invoke(SetDefaultBrowserTest.kt:26)
	at org.mozilla.focus.activity.robots.SettingsRobot$Transition.openGeneralSettingsMenu(SettingsRobot.kt:47)
	at org.mozilla.focus.activity.robots.SettingsRobot$Transition.openGeneralSettingsMenu$default(SettingsRobot.kt:40)
	at org.mozilla.focus.activity.SetDefaultBrowserTest.changeDefaultBrowserTest(SetDefaultBrowserTest.kt:26)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
    
### Build: 11/04

❗ Similar with #5788

**Comment by AndiAJ** [comment]
Failed again on Nightly 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/8130042195649987749/executions/bs.3d38cd43b3e46f4b/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/8130042195649987749/executions/bs.2d2d5b0fc1503ed3/testcases/1)

Failed again on Beta 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6437334817384491805/executions/bs.d939866c7915b0f9/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6437334817384491805/executions/bs.9fe990cfcc1c9c81/testcases/1)

**Comment by AndiAJ** [comment]
Failed again on Nightly 11/5
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/5942929985767786832/executions/bs.b3b5ad746807030f/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/5942929985767786832/executions/bs.5f5b2ffd4ebf687d/testcases/1)

Failed again on Beta 11/5
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6532684864662653779/executions/bs.9b911489248e5c72/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6532684864662653779/executions/bs.f2b8ae5363c1d/testcases/1)
