### ISSUE TITLE
Intermittent UI test failure - < MozillaSupportPagesTest. openAboutPageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5790]
### Firebase Test Run:
Failed on Nightly 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/9132632964294850166/executions/bs.cb2a426a33af6d2f/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/9132632964294850166/executions/bs.556317a94553f58c/testcases/1)

Failed on Beta 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/8406837912782968060/executions/bs.7bad4fa5bacf2c3a/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/8406837912782968060/executions/bs.10b496df4f006874/testcases/1)

### Stacktrace:
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "About Firefox Focus"

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x10302f8
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@272173d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+-->ViewStub{id=16908682, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@3d6ab32, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+-->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@53c5083, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+--->FitWindowsLinearLayout{id=2131361846, res-name=action_bar_root, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@aedea39, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+---->ViewStubCompat{id=2131361858, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@5c0487e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@86971df, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+----->FrameLayout{id=2131361940, res-name=container, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7119e2c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+------>LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@2b9f0f5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3} 
|
+------->View{id=2131362340, res-name=status_bar_background, visibility=VISIBLE, width=1080, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@3146e8a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+------->Toolbar{id=2131362392, res-name=toolbar, visibility=VISIBLE, width=1080, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@21d4cfb, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=66.0, child-count=3} 
|
+-------->AppCompatTextView{id=-1, visibility=VISIBLE, width=179, height=74, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@9107118, tag=null, root-is-layout-requested=false, has-input-connection=false, x=198.0, y=40.0, text=Mozilla, input-type=0, ime-target=false, has-links=false} 
|
+-------->AppCompatImageButton{id=-1, desc=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‏‏‏‏‎‏‎‎‎‏‏‎‏‎‎‎‏‏‎‎‎‏‏‏‏‎‏‎‎‎‎‏‏‎‏‏‎‏‎‎‏‎‎‏‎‎‎‎‎‎‏‎‏‎‎‎‎‏‏‏‎‎‎‎‎Navigate up‎‏‎‎‏‎, visibility=VISIBLE, width=154, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@f05a771, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+-------->ActionMenuView{id=-1, visibility=VISIBLE, width=0, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@d2e956, tag=null, root-is-layout-requested=false, has-input-connection=false, x=1080.0, y=0.0, child-count=0} 
|
+------->FrameLayout{id=16908351, res-name=list_container, visibility=VISIBLE, width=1080, height=1568, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b69bdd7, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=220.0, child-count=1} 
|
+-------->RecyclerView{id=2131362249, res-name=recycler_view, visibility=VISIBLE, width=1080, height=1568, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@f2786c4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=5} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@e7c49ad, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=832, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@2a26073, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=456, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@4784b30, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Show home screen tips, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@540d3a9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=VISIBLE, width=160, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@acdcd2e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=876.0, y=0.0, child-count=1} 
|
+----------->Switch{id=16908352, res-name=switch_widget, visibility=VISIBLE, width=128, height=74, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@db890cf, tag=null, root-is-layout-requested=false, has-input-connection=false, x=32.0, y=36.0, text=, input-type=0, ime-target=false, has-links=false, is-checked=true} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@9ed8e3a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=147.0, child-count=3} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=992, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@28e5048, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=541, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@2be4ee1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=About Firefox Focus Nightly, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@a165406, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=2131362072, res-name=icon_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d5c28f4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+----------->AppCompatImageView{id=16908294, res-name=icon, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@56ff81d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@1b3aa92, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@f8ce060, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=294.0, child-count=3} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=882, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@5dddde, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=90, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@9454bbf, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Help, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@44fa28c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=2131362072, res-name=icon_frame, visibility=VISIBLE, width=110, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@db70dd5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=926.0, y=0.0, child-count=1} 
|
+----------->AppCompatImageView{id=16908294, res-name=icon, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@4e5f9ea, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=40.0} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d0ce4db, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@867b251, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=441.0, child-count=3} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=882, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@eaf3b7, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=224, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@d5b724, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Your Rights, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@2a4228d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=2131362072, res-name=icon_frame, visibility=VISIBLE, width=110, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@877dc42, tag=null, root-is-layout-requested=false, has-input-connection=false, x=926.0, y=0.0, child-count=1} 
|
+----------->AppCompatImageView{id=16908294, res-name=icon, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d311453, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=40.0} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@d492190, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
|
+--------->LinearLayout{id=0, visibility=VISIBLE, width=1080, height=147, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@22b7a8e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=588.0, child-count=3} 
|
+---------->RelativeLayout{id=-1, visibility=VISIBLE, width=882, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@946c6bc, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=0.0, child-count=2} 
|
+----------->AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=281, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@5181645, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Privacy Notice, input-type=0, ime-target=false, has-links=false} 
|
+----------->AppCompatTextView{id=16908304, res-name=summary, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@68b19a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false} 
|
+---------->LinearLayout{id=2131362072, res-name=icon_frame, visibility=VISIBLE, width=110, height=147, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@9ccbacb, tag=null, root-is-layout-requested=false, has-input-connection=false, x=926.0, y=0.0, child-count=1} 
|
+----------->AppCompatImageView{id=16908294, res-name=icon, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@11792a8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=40.0} 
|
+---------->LinearLayout{id=16908312, res-name=widget_frame, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@ba8d1c1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0} 
|
+->View{id=16908336, res-name=navigationBarBackground, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@3104d66, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1788.0} 
|
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
	at org.mozilla.focus.activity.robots.SettingsMozillaMenuRobot$Transition.openAboutPage(SettingsMozillaMenuRobot.kt:70)
	at org.mozilla.focus.activity.MozillaSupportPagesTest.openAboutPageTest(MozillaSupportPagesTest.kt:52)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
    
    
### Build: 11/04

❗ Similar with #5787

**Comment by AndiAJ** [comment]
Failed again on Nightly 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/8130042195649987749/executions/bs.3ddb862bbf31397b/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/8130042195649987749/executions/bs.ddf17da9cc9cfa73/testcases/1)

Failed again on Beta 11/4
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6437334817384491805/executions/bs.aa23f0d4a34a5385/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6437334817384491805/executions/bs.fa8415edb638fc91/testcases/1)

**Comment by AndiAJ** [comment]
Failed again on Nightly 11/5
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/5942929985767786832/executions/bs.4fe2b04af48cf482/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.99d37f16502bd2e2/matrices/5942929985767786832/executions/bs.a7a10ed20b2ea219/testcases/1)

Failed again on Beta 11/5
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6532684864662653779/executions/bs.3dbabe1faca9dfba/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6532684864662653779/executions/bs.908a91b12de0c898/testcases/1)
