### ISSUE TITLE
Intermittent UI test failure - < EraseBrowsingDataTest.trashButtonTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5791]
### Firebase Test Run:
Crashed on 11/04 Beta [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/6437334817384491805/executions/bs.6008d3f05019d510/testcases/1/logs)

### Stacktrace:

11-04 12:52:55.683: E/mozac/CrashReporter(8235): CrashHandlerService received native code crash
11-04 12:52:55.687: W/InputDispatcher(2073): channel 'b901a10 org.mozilla.focus.beta/org.mozilla.focus.activity.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-04 12:52:55.687: I/Gecko(7417): Exiting due to channel error.
11-04 12:52:55.687: E/InputDispatcher(2073): channel 'b901a10 org.mozilla.focus.beta/org.mozilla.focus.activity.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-04 12:52:55.688: I/Zygote(1915): Process 7241 exited cleanly (11)
11-04 12:52:55.689: I/ActivityManager(2073): Process org.mozilla.focus.beta (pid 7241) has died: fore TOP 
11-04 12:52:55.690: W/libprocessgroup(2073): kill(-7241, 9) failed: No such process
11-04 12:52:55.690: I/libprocessgroup(2073): Successfully killed process cgroup uid 10095 pid 7241 in 0ms
11-04 12:52:55.690: W/WindowManager(2073): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@5449998
11-04 12:52:55.691: I/WindowManager(2073): WIN DEATH: Window{b901a10 u0 org.mozilla.focus.beta/org.mozilla.focus.activity.MainActivity}
11-04 12:52:55.691: W/InputDispatcher(2073): Attempted to unregister already unregistered input channel 'b901a10 org.mozilla.focus.beta/org.mozilla.focus.activity.MainActivity (server)'
11-04 12:52:55.692: W/ActivityManager(2073): Force removing ActivityRecord{886057 u0 org.mozilla.focus.beta/org.mozilla.focus.activity.MainActivity t4}: app died, no saved state
11-04 12:52:55.693: W/BinderNative(2073): Uncaught exception from death notification
11-04 12:52:55.693: W/BinderNative(2073): java.lang.NullPointerException: Attempt to read from field 'android.accessibilityservice.IAccessibilityServiceClient com.android.server.accessibility.AbstractAccessibilityServiceConnection.mServiceInterface' on a null object reference
11-04 12:52:55.693: W/BinderNative(2073): 	at com.android.server.accessibility.UiAutomationManager.destroyUiAutomationService(UiAutomationManager.java:179)
11-04 12:52:55.693: W/BinderNative(2073): 	at com.android.server.accessibility.UiAutomationManager.access$200(UiAutomationManager.java:41)
11-04 12:52:55.693: W/BinderNative(2073): 	at com.android.server.accessibility.UiAutomationManager$UiAutomationService.binderDied(UiAutomationManager.java:230)
11-04 12:52:55.693: W/BinderNative(2073): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:1193)
11-04 12:52:55.694: W/SurfaceFlinger(1930): Attempting to destroy on removed layer: AppWindowToken{acdf02d token=Token{1b5b744 ActivityRecord{886057 u0 org.mozilla.focus.beta/org.mozilla.focus.activity.MainActivity t4}}}#0
11-04 12:52:55.695: W/ActivityManager(2073): Crash of app org.mozilla.focus.beta running instrumentation ComponentInfo{org.mozilla.focus.beta.test/androidx.test.runner.AndroidJUnitRunner}
11-04 12:52:55.695: I/ActivityManager(2073): Force stopping org.mozilla.focus.beta appid=10095 user=0: finished inst
11-04 12:52:55.695: I/ActivityManager(2073): Killing 7417:org.mozilla.focus.beta:tab11/u0a95 (adj 0): stop org.mozilla.focus.beta
11-04 12:52:55.695: W/libprocessgroup(2073): kill(-7417, 9) failed: No such process
11-04 12:52:55.696: I/ActivityManager(2073): Killing 8235:org.mozilla.focus.beta:mozilla.components.lib.crash.CrashHandler/u0a95 (adj 200): stop org.mozilla.focus.beta
11-04 12:52:55.696: W/ActivityManager(2073): Scheduling restart of crashed service 

### Build: 11/04

❓ Similar with #5590

**Comment by sv-ohorvath** [comment]
Logged a bug for investigation: https://github.com/mozilla-mobile/focus-android/issues/5794

**Comment by sv-ohorvath** [comment]
Might be fixed with https://github.com/mozilla-mobile/focus-android/pull/5798. We'll wait for a while to see if it appears again and close this if not.
