### ISSUE TITLE
Intermittent UI test failure - < MediaPlaybackTest. testVideoPlayback >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#5809]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Pause]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickPauseButton(BrowserRobot.kt:125)
	at org.mozilla.focus.activity.MediaPlaybackTest$testVideoPlayback$2.invoke(MediaPlaybackTest.kt:47)
	at org.mozilla.focus.activity.MediaPlaybackTest$testVideoPlayback$2.invoke(MediaPlaybackTest.kt:41)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:80)
	at org.mozilla.focus.activity.MediaPlaybackTest.testVideoPlayback(MediaPlaybackTest.kt:41)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/9 Beta [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.816ea1097e1f8eea/matrices/7527572025514618013/executions/bs.e4f462df1cb646ed/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Pause]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.focus.activity.robots.BrowserRobot.clickPauseButton(BrowserRobot.kt:125)
at org.mozilla.focus.activity.MediaPlaybackTest$testVideoPlayback$2.invoke(MediaPlaybackTest.kt:47)
at org.mozilla.focus.activity.MediaPlaybackTest$testVideoPlayback$2.invoke(MediaPlaybackTest.kt:41)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:80)
at org.mozilla.focus.activity.MediaPlaybackTest.testVideoPlayback(MediaPlaybackTest.kt:41)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by sv-ohorvath** [comment]
Flaky on 12/2: https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4921544606600740922/executions/bs.5e21464e495bf145/testcases/1

**Comment by sv-ohorvath** [comment]
Flaky on 12/8 debug: https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8306878456760590503/executions/bs.c481abc0de4fc971/testcases/1

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months

**Comment by AndiAJ** [comment]
Flaky 1x on 4/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5275138084709616162/executions/bs.7621d4c93cf2ef09/testcases/1)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a couple of month.
