### ISSUE TITLE
[Bug][crash] android.content.ActivityNotFoundException: No Activity found to handle Intent

### ISSUE THREAD

**Issue by RandomUser0815** [mozilla-mobile/focus-android#5841]
### Steps to reproduce

1. Use Android 9 with a Motorola G6 Play
2. Create a second User profile for example using the Shelter App.
3. Install the latest "Firefox klar" 94.1.2 beta.
4. Open Firefox on the second profile
5. Open a website 
6.  Use "oeffnen mit" and choose "Personal profile"
7. Expect Firefox Klar crashing.

### Expected behaviour

No Crash. The website should be opened in the context of the personal profile. 

### Actual behaviour

The app closes unexpectedly

### Device name

Motorola g6 play 

### Android version

Android 9 - PPPS29 55-35-18-7

### Firefox release type

Firefox Beta

### Firefox version

94.1.2

### Device logs

83a93cd3-19c3-4309-a16d-736c7d100886
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.rnz.de/... pkg=android }
 * Sentry: <No URL>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-c6f5c473-fe22-450a-8119-9f36a0211110
----
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.rnz.de/... pkg=android }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2100)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1742)
	at android.app.Activity.startActivityForResult(Activity.java:4594)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:4552)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at android.app.Activity.startActivity(Activity.java:4917)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:3)
	at org.mozilla.focus.open.AppViewHolder$1.onClick(AppViewHolder.java:8)
	at android.view.View.performClick(View.java:6600)
	at android.view.View.performClickInternal(View.java:6577)
	at android.view.View.access$3100(View.java:781)
	at android.view.View$PerformClick.run(View.java:25912)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by lobontiumira** [comment]
I have encountered this crash today on Beta 97.0.0-beta.5, and on Focus Nightly 98.0 (build 360260510 GV 98.0a1-20220125100058) with Lenovo tab M10 (Android 10).
The STR are:
1. From Settings - Advanced - enable "Open links in apps".
2. Open vimeo.com, and select to watch a video.
3. Tap on "Cancel" when asked to open in app.
4. From the three-dot menu, select the "Open in...".
5. Select the "Instant app" option (Vimeo app is not installed).
6. Focus crashes.

[logcat.txt](https://github.com/mozilla-mobile/focus-android/files/7940164/logcat.txt)
![Screenshot_1](https://user-images.githubusercontent.com/40694158/151131698-57d12fdf-3dc8-4dcb-8a7f-2478548f86ff.jpg)


https://user-images.githubusercontent.com/40694158/151132040-813813d3-4e50-4f26-82bc-5b9943b019ba.mp4

**Comment by delia-pop** [comment]
The behavior in the comment above is reproducible on RC 96.3.0 with Google Pixel 6 (Android 12) as well.

**Comment by Mugurell** [comment]
There is an important other step: instant apps needs to be enabled in device settings. (it is disabled by default)
https://support.google.com/googleplay/answer/7683278

Then indeed it crashes on Focus while on Fenix it works smoothly so there is something to be improved in Focus.
Expected behavior:


https://user-images.githubusercontent.com/11428869/151926334-4865a62d-bfbf-42bb-a213-1bebba27065a.mp4

**Comment by delia-pop** [comment]
Reproducible on RC 97.1.0 with Samsung Galaxy Note10 (Android 11), with Instant apps enabled.

**Comment by delia-pop** [comment]
Reproducible on Beta 98.0.0-beta.1 with Google Pixel 6 (Android 12).

**Comment by lobontiumira** [comment]
I was not able to reproduce the crash using the steps from [here](https://github.com/mozilla-mobile/focus-android/issues/5841#issuecomment-1021989081), on the Focus Nightly 99.0 (build 360520510 with GV 99.0a1-20220220070007) with Oppo Find X3 Lite (Android 11), nor with Lenovo Tab M10 (Android 10).
