### ISSUE TITLE
The prompt isn't dismissed after "Erase" option is selected

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#5857]
## Steps to reproduce
1. Long-tap on the Focus icon from the device's home screen.
2. Select the "Erase" option from the prompt.

### Expected behavior
The prompt is dismissed.

### Actual behavior
The prompt is not dismissed, the user doesn't know if the history was cleared

```
2021-11-11 17:04:53.304 914-3516/? I/ActivityTaskManager: START u0 {act=erase flg=0x1000c000 cmp=org.mozilla.focus/.activity.EraseShortcutActivity bnds=[265,279][843,426] (has extras)} from uid 10431
2021-11-11 17:04:53.316 669-669/? D/QCOM PowerHAL: LAUNCH HINT: ON
2021-11-11 17:04:53.317 669-669/? D/QCOM PowerHAL: Activity launch hint handled
2021-11-11 17:04:53.330 9669-9669/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@99a9384
2021-11-11 17:04:53.391 669-669/? D/QCOM PowerHAL: LAUNCH HINT: OFF
2021-11-11 17:04:53.916 24932-10116/? E/memtrack: Couldn't load memtrack module
2021-11-11 17:04:53.916 24932-10116/? W/android.os.Debug: failed to get memory consumption info: -1
2021-11-11 17:04:54.463 29478-10773/? W/AsyncOperation: operation=xlb, opStatusCode=12009 [CONTEXT service_id=45 ]
    OperationException[Status{statusCode=unknown status code: 12009, resolution=null}]
        at amxx.c(:com.google.android.gms@213918037@21.39.18 (120400-407637301):1)
        at amxx.f(:com.google.android.gms@213918037@21.39.18 (120400-407637301):47)
        at xug.run(:com.google.android.gms@213918037@21.39.18 (120400-407637301):11)
        at bgff.run(:com.google.android.gms@213918037@21.39.18 (120400-407637301):2)
        at rok.c(:com.google.android.gms@213918037@21.39.18 (120400-407637301):6)
        at rok.run(:com.google.android.gms@213918037@21.39.18 (120400-407637301):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at rsr.run(:com.google.android.gms@213918037@21.39.18 (120400-407637301):0)
        at java.lang.Thread.run(Thread.java:919)
```

### Device information
* Android device: Google Pixel (Android 10) - might be device specific
* Not reproducible on Xiaomi Mi8 Lite (Android 9), Samsung Galaxy Note 8 (Android 9), OnePlus 5T (Android 10)
* Focus version: all

https://user-images.githubusercontent.com/40694158/141321575-7b8ef908-ea65-46d9-a30c-38eb2e628275.mp4

**Comment by mcarare** [comment]
I do not think there is something we can do differently here. The menu is displayed by the launcher (based on the declared shortcuts for the app ) and it should be the one that handles the closing as well. 

Note that `reportShortcutUsed` in `ShortcutManager` is not documented to be related to the closing behavior.

**Comment by lobontiumira** [comment]
Reproducible on Beta 96.0.0-beta.4 with Xiaomi Mi8 Lite (Android 10).

**Comment by lobontiumira** [comment]
Reproducible on the latest builds (Nightly 102.0a1 from 5/26, RC 101.1.0, and Beta 101.0.0-beta.6) with Google Pixel (Android 10).

**Comment by ionutbedregeanu** [comment]
@lobontiumira Can you also check on Fenix(new private tab option), Chrome if it's reproducible?
As Mihai said we don't think is something we can do here, it seems OS related

**Comment by ionutbedregeanu** [comment]
As Mihai said, this seems an OS issue and we can't do something locally to fix this.
I don't know another app with a similar functionality in order to do more tests
I will close this ticket but feel free to reopen it if you have mixed feelings about my decision
