### ISSUE TITLE
Intermittent UI test failure - MozillaSupportPagesTest.turnOffHomeScreenTipsTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5883]
### Firebase Test Run:
Flaky:
https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8210291683145967901/executions/bs.f1af6d516d2ba696/testcases/1
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with text: is "Show home screen tips"

at org.mozilla.focus.activity.robots.SettingsMozillaMenuRobot.switchHomeScreenTips(SettingsMozillaMenuRobot.kt:35)
at org.mozilla.focus.activity.MozillaSupportPagesTest$turnOffHomeScreenTipsTest$4.invoke(MozillaSupportPagesTest.kt:109)
at org.mozilla.focus.activity.MozillaSupportPagesTest$turnOffHomeScreenTipsTest$4.invoke(MozillaSupportPagesTest.kt:108)
at org.mozilla.focus.activity.robots.SettingsRobot$Transition.openMozillaSettingsMenu(SettingsRobot.kt:77)
at org.mozilla.focus.activity.MozillaSupportPagesTest.turnOffHomeScreenTipsTest(MozillaSupportPagesTest.kt:108)`
### Build:
11/16 main

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months
