### ISSUE TITLE
Intermittent UI test failure - MediaPlaybackTest.testAudioPlayback

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5901]
### Firebase Test Run:
[Firebase test run report](https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8896965711582016141/executions/bs.aac5b44d03a68d69/testcases/1)
### Stacktrace:
`androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Pause]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.focus.activity.robots.BrowserRobot.clickPauseButton(BrowserRobot.kt:134)
at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:67)
at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:61)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:82)
at org.mozilla.focus.activity.MediaPlaybackTest.testAudioPlayback(MediaPlaybackTest.kt:61)`
### Build:
Main 11/17

**Comment by AndiAJ** [comment]
Flaky 1x on 12/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7866591100874391561/executions/bs.805cd0d23087c81b/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Pause]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.focus.activity.robots.BrowserRobot.clickPauseButton(BrowserRobot.kt:134)
at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:67)
at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:61)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:85)
at org.mozilla.focus.activity.MediaPlaybackTest.testAudioPlayback(MediaPlaybackTest.kt:61)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 12/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7418980476914102478/executions/bs.a9b4177f20a486c3/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Pause]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.focus.activity.robots.BrowserRobot.clickPauseButton(BrowserRobot.kt:132)
at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:67)
at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:61)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:85)
at org.mozilla.focus.activity.MediaPlaybackTest.testAudioPlayback(MediaPlaybackTest.kt:61)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9212347726385015954/executions/bs.a42a02aa2248de8e/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Pause]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.focus.activity.robots.BrowserRobot.clickPauseButton(BrowserRobot.kt:136)
at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:71)
at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:65)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:84)
at org.mozilla.focus.activity.MediaPlaybackTest.testAudioPlayback(MediaPlaybackTest.kt:65)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4735580266970744056/executions/bs.ec0634d4c8e2bce2/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8542436322141599091/executions/bs.2c98033ac47042a7/testcases/2)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6810144359267907816/executions/bs.88367682ef442fc1/testcases/2/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9045171159187334527/executions/bs.d5ca0a6ad94dbd6e/testcases/1)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for approx. a month.
