### ISSUE TITLE
Intermittent UI test failure - notificationEraseAndOpenButtonTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#5927]
### Firebase Test Run:
Flaky on 11/22
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9180648678380244643/executions/bs.dacc7ab0ed2b1f57
### Stacktrace:
`androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[DESCRIPTION=Erase and Open]
at androidx.test.uiautomator.UiObject.getBounds(UiObject.java:911)
at androidx.test.uiautomator.UiScrollable.ensureFullyVisible(UiScrollable.java:294)
at org.mozilla.focus.activity.robots.NotificationRobot.expandEraseBrowsingNotification(NotificationRobot.kt:46)
at org.mozilla.focus.activity.EraseBrowsingDataTest$notificationEraseAndOpenButtonTest$4.invoke(EraseBrowsingDataTest.kt:104)
at org.mozilla.focus.activity.EraseBrowsingDataTest$notificationEraseAndOpenButtonTest$4.invoke(EraseBrowsingDataTest.kt:102)
at org.mozilla.focus.activity.robots.NotificationRobotKt.notificationTray(NotificationRobot.kt:97)
at org.mozilla.focus.activity.EraseBrowsingDataTest.notificationEraseAndOpenButtonTest(EraseBrowsingDataTest.kt:102)`
### Build:
11/22 Main

**Comment by AndiAJ** [comment]
Flaky 1/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7036010280370560266/executions/bs.cb5fa10bb2de25f7/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4914389215699599308/executions/bs.a3dfff5f132e8560/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[DESCRIPTION=Erase and Open]
at androidx.test.uiautomator.UiObject.getBounds(UiObject.java:911)
at androidx.test.uiautomator.UiScrollable.ensureFullyVisible(UiScrollable.java:294)
at org.mozilla.focus.activity.robots.NotificationRobot.expandEraseBrowsingNotification(NotificationRobot.kt:46)
at org.mozilla.focus.activity.EraseBrowsingDataTest$notificationEraseAndOpenButtonTest$4.invoke(EraseBrowsingDataTest.kt:107)
at org.mozilla.focus.activity.EraseBrowsingDataTest$notificationEraseAndOpenButtonTest$4.invoke(EraseBrowsingDataTest.kt:105)
at org.mozilla.focus.activity.robots.NotificationRobotKt.notificationTray(NotificationRobot.kt:97)
at org.mozilla.focus.activity.EraseBrowsingDataTest.notificationEraseAndOpenButtonTest(EraseBrowsingDataTest.kt:105)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months
