### ISSUE TITLE
Intermittent UI test failure - SafeBrowsingTest.testLocationSharingNotAllowed 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#6156]
### Firebase Test Run:
Flaky, 1/2 runs:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8648895090964920917/executions/bs.99b9ed2081c3f305
### Stacktrace:
`androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=Get Location]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.focus.activity.robots.BrowserRobot.clickGetLocationButton(BrowserRobot.kt:79)
at org.mozilla.focus.activity.SafeBrowsingTest$testLocationSharingNotAllowed$2.invoke(SafeBrowsingTest.kt:139)
at org.mozilla.focus.activity.SafeBrowsingTest$testLocationSharingNotAllowed$2.invoke(SafeBrowsingTest.kt:138)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:85)
at org.mozilla.focus.activity.SafeBrowsingTest.testLocationSharingNotAllowed(SafeBrowsingTest.kt:138)`
### Build:
Debug 3/1/22

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months
