### ISSUE TITLE
Intermittent UI test failure - URLAutocompleteTest.duplicateCustomUrlNotAllowedTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#6160]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6220473969579829785/executions/bs.b244474c1b4cd015/testcases/1
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with string from resource id: <2131886649>[preference_autocomplete_subitem_manage_sites] value: Manage sites

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
at org.mozilla.focus.activity.robots.SearchSettingsRobot.openManageSitesSubMenu(SettingsSearchMenuRobot.kt:66)
at org.mozilla.focus.activity.URLAutocompleteTest$duplicateCustomUrlNotAllowedTest$4.invoke(URLAutocompleteTest.kt:135)
at org.mozilla.focus.activity.URLAutocompleteTest$duplicateCustomUrlNotAllowedTest$4.invoke(URLAutocompleteTest.kt:133)
at org.mozilla.focus.activity.robots.SettingsRobot$Transition.openSearchSettingsMenu(SettingsRobot.kt:36)
at org.mozilla.focus.activity.URLAutocompleteTest.duplicateCustomUrlNotAllowedTest(URLAutocompleteTest.kt:133)`
### Build:
1/4/22

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months
