### ISSUE TITLE
Intermittent UI test failure - SearchTest.disableSearchSuggestionsTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/focus-android#6181]
### Firebase Test Run:
Flaky, 1/2 runs:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6992919389546818556/executions/bs.670e6b263596cdca
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.mozilla.focus.activity.robots.SearchRobot.verifySearchBarIsDisplayed(SearchRobot.kt:24)
at org.mozilla.focus.activity.SearchTest$disableSearchSuggestionsTest$1.invoke(SearchTest.kt:127)
at org.mozilla.focus.activity.SearchTest$disableSearchSuggestionsTest$1.invoke(SearchTest.kt:125)
at org.mozilla.focus.activity.robots.SearchRobotKt.searchScreen(SearchRobot.kt:92)
at org.mozilla.focus.activity.SearchTest.disableSearchSuggestionsTest(SearchTest.kt:125)`
### Build:
1/6/22

**Comment by AndiAJ** [comment]
Closing as it didn't fail for a couple of months
