### ISSUE TITLE
Focus nightly crashes on startup with FLAG_IMMUTABLE or FLAG_MUTABLE in PendingIntent

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6244]
Focus Nightly after https://github.com/mozilla-mobile/focus-android/issues/6223 landed crash on startup. 

I and others were only able to reproduce this crash from installing the app through GPS. Building locally with debug or release didn't see to trigger the crash. See conversation on [Matrix](https://chat.mozilla.org/#/room/#focus-android:mozilla.org).

Related AC: https://github.com/mozilla-mobile/android-components/issues/11563

```
2022-01-18 01:04:09.380 7229-7229/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.focus.nightly, PID: 7229
    java.lang.RuntimeException: Unable to create application org.mozilla.focus.FocusApplication: java.lang.IllegalArgumentException: org.mozilla.focus.nightly: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6733)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.IllegalArgumentException: org.mozilla.focus.nightly: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at org.mozilla.focus.Components$crashReporter$2.invoke(Components.kt:19)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
        at org.mozilla.focus.Components.getCrashReporter(Components.kt:1)
        at org.mozilla.focus.FocusApplication.onCreate(FocusApplication.kt:6)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6728)
        	... 9 more
```

**Comment by Mugurell** [comment]
Paired with Ionut on this, seems like even after setting the right flags in Focus the app will still crash because of an older version of `androidx.work:work-runtime` - 2.4.0 used in many AC components.
We could force a newer version in build.gradle but seems like AC needs to be updated also for a proper fix.

Seems like Fenix will also crash in these conditions once being set to target 31 so AC needs to be updated before that.

**Comment by Amejia481** [comment]
> Paired with Ionut on this, seems like even after setting the right flags in Focus the app will still crash because of an older version of `androidx.work:work-runtime` - 2.4.0 used in many AC components. We could force a newer version in build.gradle but seems like AC needs to be updated also for a proper fix.
> 
> Seems like Fenix will also crash in these conditions once being set to target 31 so AC needs to be updated before that.

Then, I think we should update version AC too

**Comment by jonalmeida** [comment]
> Then, I think we should update version AC too

For context, this was originally backed out. See: https://github.com/mozilla-mobile/android-components/pull/11541

**Comment by Mugurell** [comment]
> > Then, I think we should update version AC too
> 
> For context, this was originally backed out. See: [mozilla-mobile/android-components#11541](https://github.com/mozilla-mobile/android-components/pull/11541)

"Circular dependency hell" 🤣
Then it seems like we should force 2.8.0 here since we're already targetting Android 31 (hopefully there won't be any bugs because of incompatibilities with other androidx libs).
And then for Fenix targetting Android 31 and using a newer version of WM in AC should happen ~at the same time.

**Comment by Amejia481** [comment]
> > > Then, I think we should update version AC too
> > 
> > 
> > For context, this was originally backed out. See: [mozilla-mobile/android-components#11541](https://github.com/mozilla-mobile/android-components/pull/11541)
> 
> "Circular dependency hell" 🤣 Then it seems like we should force 2.8.0 here since we're already targetting Android 31 (hopefully there won't be any bugs because of incompatibilities with other androidx libs). And then for Fenix targetting Android 31 and using a newer version of WM in AC should happen ~at the same time. After which Focus will also switch to again allow and use any transitive WM.

😆 
I guess we could temporary force the WM version until we get the updated one in AC  and then we could remove the temporary fix :)

**Comment by jonalmeida** [comment]
I think we can put the WM upgrade back in now that we have Focus on 31. I'll put up a PR for that and try it out in Focus.

**Comment by softvision-oana-arbuzov** [comment]
Also reproducible with Firefox Focus Nightly 98.0 (🦎 98.0a1-20220119093435) on Google Pixel 5 (Android 12).

Note: Not reproducible on Samsung Galaxy S8 (Android 9) with the same build.

**Comment by delia-pop** [comment]
Tested on Firefox Focus Nightly 98.0 (Build 360310515 🦎 98.0a1-20220130093554) with Google Pixel 6 (Android 12).
The application no longer crashes on launch.

**Comment by softvision-oana-arbuzov** [comment]
I can confirm it works for me too now, I was able to load Firefox Focus Nightly.
![image](https://user-images.githubusercontent.com/12184325/152185291-7fb1eb71-00b4-4e97-b155-e3f74aecdfd3.png)
 
**Tested with:**
Browser / Version: Firefox Focus Nightly 98.0 (🦎 98.0a1-20220201093942) 
Operating System: Google Pixel 5 (Android 12) - 1080 x 2340 pixels, 19.5:9 ratio (~432 ppi density)
