### ISSUE TITLE
L10N scripts: Calling python from Gradle fails

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#638]
For some kind of reason calling the python scripts from Gradle now fails for me. Running the scripts myself just works.

```
:app:stringsExport
Traceback (most recent call last):
  File "tools/l10n/android2po/a2po.py", line 1, in <module>
    import program
  File "/Users/sebastian/Projects/Mozilla/Focus/tools/l10n/android2po/program.py", line 16, in <module>
    from commands import InitCommand, ExportCommand, ImportCommand, CommandError
  File "/Users/sebastian/Projects/Mozilla/Focus/tools/l10n/android2po/commands.py", line 9, in <module>
    from lxml import etree
  File "serializer.pxi", line 4, in init lxml.etree (src/lxml/lxml.etree.c:200373)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 10, in <module>
    import io
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
:app:stringsExport FAILED
```

**Comment by pocmo** [comment]
@ahunt Do you see this too? Currently I'm running the scripts manually. This might have happened after a system / brew update.

**Comment by pocmo** [comment]
This doesn't happen anymore.
