### ISSUE TITLE
UninitializedPropertyAccessException: lateinit property browserFragment has not been initialized

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6393]
## Steps to reproduce
1. Open a custom tab in a third party app.
2. Multi-task away until the app has it's memory freed. Takes a while to happen depending on your phone.
3. Return and observe the page is blank.
4. Press the Custom Tab back button to return back to the third-party app.

### Expected behavior
- Don't crash.

### Actual behavior
- 💥

### Device information

* Android device: Android 12, Pixel 3
* Focus version: Nightly 98.0 (Build #360400511
99.0a1-20220208070047)

Crash log:

```
kotlin.UninitializedPropertyAccessException: lateinit property browserFragment has not been initialized
    at org.mozilla.focus.activity.CustomTabActivity.onBackPressed(CustomTabActivity.kt:5)
    at android.app.Activity.onKeyUp(Activity.java:3836)
    at android.view.KeyEvent.dispatch(KeyEvent.java:2878)
    at android.app.Activity.dispatchKeyEvent(Activity.java:4161)
    at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:1)
    at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:2)
    at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
    at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
    at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:404)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6275)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6141)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5623)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5811)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5654)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5868)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5627)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5654)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5627)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5844)
    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6002)
    at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3158)
    at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
    at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
    at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3135)
    at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
    at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
    at android.os.MessageQueue.next(MessageQueue.java:335)
    at android.os.Looper.loopOnce(Looper.java:161)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7842)
    at java.lang.reflect.Method.invoke(Method.java)
```

**Comment by jonalmeida** [comment]
When reviewing this PR, I had tested this case with Don't Keep Activities and changed the background process number for the app to 0, but I didn't run into this.

If the browserFragment is not init'd, then we've half restored the page? 🤔

I'm sure we've fixed this on Fenix, but maybe this is good reason to find that fix and put it in components.

cc: @mcarare - I think we should back out this change (and uplift) before it gets into release.

**Comment by mcarare** [comment]
@jonalmeida I'll look into a fail-safe for this without reverting the fixes.

From the STR you described it looks like the fragment is being destroyed without the activity being destroyed (the fact that we see a blank screen and not the third-party app). 

AFAIK this should not happen; a fragment should not be destroyed (or removed) without the associated activity being destroyed without a transaction taking effect. So I believe we are left with only one scenario: the activity was also destroyed, but it was recreated, with a non-null `savedInstanceState` Bundle. In this case, the browser fragment will not be initialized inside the ` if (savedInstanceState == null) ` block and would not be added, leaving us with the blank screen you have seen.

I'll try to recreate this scenario and see what we could do differently to avoid it.

**Comment by delia-pop** [comment]
Tested on Firefox Focus Nightly 99.0 (Build 360450513 🦎 99.0a1-20220212115333) with multiple devices, Google Pixel 6 (Android 12) included. 
We were not able to reproduce this issue.
