### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest.removeOneExceptionURLTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6425]
### Stacktrace:
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'is enabled' doesn't match the selected view.
Expected: is enabled
     Got: "AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=215, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=false, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@855f564, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Exceptions, input-type=0, ime-target=false, has-links=false}"

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:324)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
	at org.mozilla.focus.activity.robots.SettingsPrivacyMenuRobot.openExceptionsList(SettingsPrivacyMenuRobot.kt:177)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$removeOneExceptionURLTest$7.invoke(EnhancedTrackingProtectionSettingsTest.kt:294)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$removeOneExceptionURLTest$7.invoke(EnhancedTrackingProtectionSettingsTest.kt:293)
	at org.mozilla.focus.activity.robots.SettingsRobot$Transition.openPrivacySettingsMenu(SettingsRobot.kt:57)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest.removeOneExceptionURLTest(EnhancedTrackingProtectionSettingsTest.kt:293)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: junit.framework.AssertionFailedError: 'is enabled' doesn't match the selected view.
Expected: is enabled
     Got: "AppCompatTextView{id=16908310, res-name=title, visibility=VISIBLE, width=215, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=false, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@855f564, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Exceptions, input-type=0, ime-target=false, has-links=false}"

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:540)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:105)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:425)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:288)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:272)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sv-ohorvath** [comment]
Crashed 1/2 tries on debug 3/25 :
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7626558518361063044/executions/bs.a3325301d432133a

**Comment by sv-ohorvath** [comment]
Possible ANR from the logs

**Comment by sv-ohorvath** [comment]
closing as dupe in favor of https://github.com/mozilla-mobile/focus-android/issues/7344
