### ISSUE TITLE
Intermittent UI test failure - <notificationOpenButtonTest>

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#6430]
https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5933786035319020532

```Kotlin
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.mozilla.focus.activity.robots.NotificationRobot.verifySystemNotificationExists(NotificationRobot.kt:49)
at org.mozilla.focus.activity.SwitchContextTest$notificationOpenButtonTest$3.invoke(SwitchContextTest.kt:97)
at org.mozilla.focus.activity.SwitchContextTest$notificationOpenButtonTest$3.invoke(SwitchContextTest.kt:96)
at org.mozilla.focus.activity.robots.NotificationRobotKt.notificationTray(NotificationRobot.kt:94)
at org.mozilla.focus.activity.SwitchContextTest.notificationOpenButtonTest(SwitchContextTest.kt:96)
```

![image](https://user-images.githubusercontent.com/102331/153948579-c4c349e4-0224-4f42-b5f7-82616b24231d.png)

@AndiAJ It looks like there are more default notifications completely filling up the Firebase Pixel 3 device all of a sudden. Clear all is supposed to clear the silent notifications which is called in the `setup`, but it didn't do anything here. Can you see if you can reproduce locally by filling up notifications and seeing why clear all isn't working here?

**Comment by AaronMT** [comment]
Oh I think `com.android.systemui:id/btn_clear_all` is the API30 equivalent for clearing notifications. The constant needs to change in the robot.

**Comment by AndiAJ** [comment]
Flaky 1x on 2/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9060412895162901677/executions/bs.742e55b371c54ee6/testcases/1)

Let's see if #6431 fixes this problem
