### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest. verifyPageSecurityIconAndInfo >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6470]
### Notes
❗ Not sure what is causing this crash
All the steps from the test are performed.

[verifyPageSecurityIconAndInfo.txt](https://github.com/mozilla-mobile/focus-android/files/8098413/verifyPageSecurityIconAndInfo.txt)

Similar with #6436 #6437 and #6439

**Comment by AaronMT** [comment]
```Kotlin
androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Root{application-window-token=android.view.ViewRootImpl$W@8cc26da, window-token=android.view.ViewRootImpl$W@8cc26da, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x10302fe
fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
fitSides=}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1080, height=2160, has-focus=false, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x10302fe
fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}}
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1736)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
at org.mozilla.focus.activity.robots.SiteSecurityInfoSheetRobot.verifySiteConnectionInfoIsSecure(SiteSecurityInfoSheetRobot.kt:28)
at org.mozilla.focus.activity.SafeBrowsingTest$verifyPageSecurityIconAndInfo$3.invoke(SafeBrowsingTest.kt:125)
at org.mozilla.focus.activity.SafeBrowsingTest$verifyPageSecurityIconAndInfo$3.invoke(SafeBrowsingTest.kt:124)
at org.mozilla.focus.activity.robots.BrowserRobot$Transition.openSiteSecurityInfoSheet(BrowserRobot.kt:215)
at org.mozilla.focus.activity.SafeBrowsingTest.verifyPageSecurityIconAndInfo(SafeBrowsingTest.kt:124)
```

**Comment by AaronMT** [comment]
Failed in https://github.com/mozilla-mobile/focus-android/runs/5250616244

**Comment by AndiAJ** [comment]
Closing, as it didn't fail in the last months.
