### ISSUE TITLE
Intermittent UI test failure - < AddToHomescreenTest.addPageToHomeScreenTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6500]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:73)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:78)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:77)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:50)
	at org.mozilla.focus.activity.AddToHomescreenTest.addPageToHomeScreenTest(AddToHomescreenTest.kt:77)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/21 [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5597629986547380972/executions/bs.4477d99e6de5929d/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5796277028488016399/executions/bs.958c4a87bcb73b4f/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5560440525025818289/executions/bs.77fc1a9aba2ff408/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6993634925667485653/executions/bs.e1be11f8f9705765/testcases/1)
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:77)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:67)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:66)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:50)
	at org.mozilla.focus.activity.AddToHomescreenTest.addPageToHomeScreenTest(AddToHomescreenTest.kt:66)

**Comment by AndiAJ** [comment]
Closing, didn't fail for approx a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 6/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8701340939423419863/executions/bs.448b50b41e0a960f/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:77)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:68)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:67)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:50)
	at org.mozilla.focus.activity.AddToHomescreenTest.addPageToHomeScreenTest(AddToHomescreenTest.kt:67)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8482264032403030110/executions/bs.6ad0833cef21ed14/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:77)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:68)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:67)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:50)
	at org.mozilla.focus.activity.AddToHomescreenTest.addPageToHomeScreenTest(AddToHomescreenTest.kt:67)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5302511535706401145/executions/bs.e28b415ed9009f46/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:77)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:68)
	at org.mozilla.focus.activity.AddToHomescreenTest$addPageToHomeScreenTest$5.invoke(AddToHomescreenTest.kt:67)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:50)
	at org.mozilla.focus.activity.AddToHomescreenTest.addPageToHomeScreenTest(AddToHomescreenTest.kt:67)
