### ISSUE TITLE
Intermittent UI test failure - < AddToHomescreenTest.noNameShortcutTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6507]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:73)
	at org.mozilla.focus.activity.AddToHomescreenTest$noNameShortcutTest$5.invoke(AddToHomescreenTest.kt:96)
	at org.mozilla.focus.activity.AddToHomescreenTest$noNameShortcutTest$5.invoke(AddToHomescreenTest.kt:95)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:50)
	at org.mozilla.focus.activity.AddToHomescreenTest.noNameShortcutTest(AddToHomescreenTest.kt:95)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6612991286840211866/executions/bs.98293a709ed3174d/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8477825543876763748/executions/bs.50ade27fad3960b/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7920353920986193439/executions/bs.2325e60adb308eae/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5178330545741315630/executions/bs.67944f188d692e5b/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8866658494364359931/executions/bs.6574a08b06f7b102/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8488578405338500604/executions/bs.6d8fd6876498816/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:77)
	at org.mozilla.focus.activity.AddToHomescreenTest$noNameShortcutTest$5.invoke(AddToHomescreenTest.kt:84)
	at org.mozilla.focus.activity.AddToHomescreenTest$noNameShortcutTest$5.invoke(AddToHomescreenTest.kt:83)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:50)
	at org.mozilla.focus.activity.AddToHomescreenTest.noNameShortcutTest(AddToHomescreenTest.kt:83)
