### ISSUE TITLE
[crash] Focus Nightly crashes when accessing Your Rights page

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6522]
## Steps to reproduce
1. Open Focus Nightly.
2. Go to Settings - Mozilla - Your Rights.
3. Tap on it.

### Expected behavior
The "Your Rights" page openes.

### Actual behavior
Nightly crashes.

### Device information
* Android device: Oppo Find X3 Lite (Android 11), Xiaomi Mi8 Lite (Android 9)
* Focus version: Focus Nightly from 2/28

1181f2ec-af46-47c2-9d1c-c7ccada4a570
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
* Sentry: <No URL>
* Socorro: https://crash-stats.mozilla.org/report/index/bp-9c051603-8185-4cc5-b7f1-4968b0220228
----
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
at org.mozilla.focus.settings.MozillaSettingsFragment.onSharedPreferenceChanged(MozillaSettingsFragment.kt:4)
at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
at android.app.SharedPreferencesImpl$EditorImpl.lambda$notifyListeners$0$SharedPreferencesImpl$EditorImpl(SharedPreferencesImpl.java:643)
at android.app.-$$Lambda$SharedPreferencesImpl$EditorImpl$3CAjkhzA131V3V-sLfP2uy0FWZ0.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:263)
at android.app.ActivityThread.main(ActivityThread.java:8258)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
```

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly 100.0a1 (build 360680510 with GV 100.0a1-20220308100756), and on Beta 99.0.0-beta.1 with the following devices:
* Xiaomi mi4i (Android 5.0.2)
* Samsung Galaxy Note 8 (Android 9)
* Oppo Find X3 Lite (Android 11).
