### ISSUE TITLE
[crash] Rotating the device when both CFR's are displayed, crashes Focus

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#6525]
## Steps to reproduce
1. Open Focus Nightly.
2. Open an insecure page, like ananana.nn.
3. Close the page.
4. Open a new insecure page.
5. Close it.
6. Open a secure page. in order for both CFR's to be displayed.
7. Rotate the device to landscape, without dismissing the CFR's.

### Expected behavior
The app doesn't crash.

### Actual behavior
The app crashes.

### Device information
* Android device: Samsung Galaxy Tab A6 (Android 5.1.1), Oppo Find X3 Lite (Android 11)
* Focus version: Focus Nightly from 2/28

https://user-images.githubusercontent.com/40694158/155970670-442ad2e8-df97-45da-9b27-b6e9dcdea600.mp4

fa1f2fad-faf9-485f-9dd3-1866cefb321b
java.util.ConcurrentModificationException
* Sentry: <No URL>
* Socorro: https://crash-stats.mozilla.org/report/index/bp-c3eaa6d0-7704-41d9-ae96-fb2460220228
----
```
java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at org.mozilla.gecko.GeckoScreenOrientation$1.run(GeckoScreenOrientation.java:1)
at org.mozilla.gecko.GeckoScreenOrientation.update(GeckoScreenOrientation.java:16)
at org.mozilla.gecko.GeckoScreenChangeListener.onDisplayChanged(GeckoScreenChangeListener.java:3)
at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:693)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6939)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by Mugurell** [comment]
I think the issues here was that both CFRs were open at the same time, issue which is soon to be addressed.
@lobontiumira Does the issue happen when only one CFR is shown?

**Comment by lobontiumira** [comment]
@Mugurell no, Focus doesn't crash when one CFR is displayed, and the device is rotated.
I'll edit the title also.

**Comment by lobontiumira** [comment]
This isssue is no longer reproducible, because the CFR's are no longer displayed both.
Verified on the latest Focus Nightly 100.0a1 (build 360680510 with GV 100.0a1-20220308100756) with the following devices:
* Samsung Galaxy Note 8 (Android 9),
* Xiaomi mi4i (Android 5.0.2), and
* Oppo Find X3 Lite (Android 11).
