### ISSUE TITLE
Intermittent UI test failure - < MultitaskingTest. closeTabButtonTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6600]
The ANR crash reports (removed from this issue) will be tracked at https://github.com/mozilla-mobile/focus-android/issues/7344

Keeping this issue open for a (possibly) different crash, reported in a comment below: https://github.com/mozilla-mobile/focus-android/issues/6600#issuecomment-1138245397

**Comment by AndiAJ** [comment]
Disabled the test in https://github.com/mozilla-mobile/focus-android/pull/6706 due to https://github.com/mozilla-mobile/focus-android/issues/6708

**Comment by sv-ohorvath** [comment]
re-enabled in https://github.com/mozilla-mobile/focus-android/pull/6813

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a couple of month.

**Comment by AndiAJ** [comment]
Flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8436812599130824924/executions/bs.7674f2936b695b6a)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7138578875714020466/executions/bs.286e95b34eced356/testcases/1)

androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Root{application-window-token=android.view.ViewRootImpl$W@7683afb, window-token=android.view.ViewRootImpl$W@7683afb, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} layoutInDisplayCutoutMode=shortEdges ty=BASE_APPLICATION wanim=0x10302fe
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  fitSides=}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1080, height=2160, has-focus=true, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} layoutInDisplayCutoutMode=shortEdges ty=BASE_APPLICATION wanim=0x10302fe
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}}
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
	at org.mozilla.focus.activity.robots.BrowserRobot.openLinkInNewTab(BrowserRobot.kt:132)
	at org.mozilla.focus.activity.MultitaskingTest$closeTabButtonTest$2.invoke(MultitaskingTest.kt:120)
	at org.mozilla.focus.activity.MultitaskingTest$closeTabButtonTest$2.invoke(MultitaskingTest.kt:115)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.MultitaskingTest.closeTabButtonTest(MultitaskingTest.kt:115)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month.
