### ISSUE TITLE
Intermittent UI test failure - < FirstRunTest. homeScreenTipsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6626]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyTipText(HomeScreenRobot.kt:65)
	at org.mozilla.focus.activity.FirstRunTest$homeScreenTipsTest$1.invoke(FirstRunTest.kt:84)
	at org.mozilla.focus.activity.FirstRunTest$homeScreenTipsTest$1.invoke(FirstRunTest.kt:78)
	at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:144)
	at org.mozilla.focus.activity.FirstRunTest.homeScreenTipsTest(FirstRunTest.kt:78)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/26 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6901823504575733541/executions/bs.77624ee80fec53a6/testcases/1)

**Comment by AndiAJ** [comment]
Closing, as it didn't occur for more than a month.
