### ISSUE TITLE
Intermittent UI test failure - < SwitchContextTest.switchFromSettingsToFocusTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6678]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.NotificationRobot.verifySystemNotificationExists(NotificationRobot.kt:51)
	at org.mozilla.focus.activity.SwitchContextTest$switchFromSettingsToFocusTest$3.invoke(SwitchContextTest.kt:145)
	at org.mozilla.focus.activity.SwitchContextTest$switchFromSettingsToFocusTest$3.invoke(SwitchContextTest.kt:144)
	at org.mozilla.focus.activity.robots.NotificationRobotKt.notificationTray(NotificationRobot.kt:128)
	at org.mozilla.focus.activity.SwitchContextTest.switchFromSettingsToFocusTest(SwitchContextTest.kt:144)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7043092642574687492/executions/bs.a8a6c8b15e391def/testcases/1)

**Comment by AndiAJ** [comment]
Didn't fail for approx. a month, closing for now.

**Comment by AndiAJ** [comment]
Flaky again on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8900117832101464208/executions/bs.5f10aed45b3648b2/testcases/1)

**Comment by sv-ohorvath** [comment]
Disabled,see https://github.com/mozilla-mobile/focus-android/issues/6958
