### ISSUE TITLE
Intermittent UI test failure - < FirstRunTest. firstTipIsAlwaysDisplayedTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6687]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyTipText(HomeScreenRobot.kt:65)
	at org.mozilla.focus.activity.FirstRunTest$firstTipIsAlwaysDisplayedTest$1.invoke(FirstRunTest.kt:157)
	at org.mozilla.focus.activity.FirstRunTest$firstTipIsAlwaysDisplayedTest$1.invoke(FirstRunTest.kt:151)
	at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:144)
	at org.mozilla.focus.activity.FirstRunTest.firstTipIsAlwaysDisplayedTest(FirstRunTest.kt:151)

**Comment by AndiAJ** [comment]
Didn't fail for approx. a month, closing for now.
