### ISSUE TITLE
Permanent UI test failures - org.mozilla.focus.activity.MultitaskingTest testVisitingMultipleSites and closeTabButtonTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/focus-android#6707]
These started after #6531 landed cc @sv-ohorvath 

### Firebase Test Run:
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7920353920986193439
### Stacktrace:
```
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '(view is an instance of android.view.ViewGroup and has descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)))' doesn't match the selected view.
Expected: (view is an instance of android.view.ViewGroup and has descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)))
     Got: no descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)) was found
View Details: RecyclerView{id=2131362349, res-name=sessions, visibility=VISIBLE, width=770, height=616, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@899d4d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.TabsTrayRobot.verifyTabsOrderAndCorespondingCloseButton(TabsTrayRobot.kt:21)
	at org.mozilla.focus.activity.MultitaskingTest$testVisitingMultipleSites$5.invoke(MultitaskingTest.kt:106)
	at org.mozilla.focus.activity.MultitaskingTest$testVisitingMultipleSites$5.invoke(MultitaskingTest.kt:105)
	at org.mozilla.focus.activity.robots.BrowserRobot$Transition.openTabsTray(BrowserRobot.kt:399)
	at org.mozilla.focus.activity.MultitaskingTest.testVisitingMultipleSites(MultitaskingTest.kt:105)
	... 31 trimmed
Caused by: junit.framework.AssertionFailedError: '(view is an instance of android.view.ViewGroup and has descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)))' doesn't match the selected view.
Expected: (view is an instance of android.view.ViewGroup and has descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)))
     Got: no descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)) was found
View Details: RecyclerView{id=2131362349, res-name=sessions, visibility=VISIBLE, width=770, height=616, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@899d4d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
```
### Build:
https://github.com/mozilla-mobile/focus-android/commit/da1d66d65e5dbfd46d7135ce8cb62165d57cc381

**Comment by Archaeopteryx** [comment]
Fixed by #6706
