### ISSUE TITLE
Intermittent UI test failure - < MultitaskingTest.closeTabButtonTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6708]
### Firebase Test Run:
Failed 7x on Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8130161673633596199/executions/bs.7b7dd1dc7399b4b0/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8130161673633596199/executions/bs.e101dac99ee2f702/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8463988771229590824/executions/bs.39f235cffdc54811/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8463988771229590824/executions/bs.dda97411ec64ec08/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6599319346280401514/executions/bs.5600d2e44b3d10ff/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6599319346280401514/executions/bs.58922d1ef27a7a4e/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8477825543876763748/executions/bs.220d99d2254dd6c2/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8477825543876763748/executions/bs.ec955e147bce4963/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5504589848841814559/executions/bs.2583161431d6efbf/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5504589848841814559/executions/bs.f77e06474cd44a2c/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6969678591280783663/executions/bs.f6d32d10b16f4e63/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7920353920986193439/executions/bs.1c268fc65c2e662b/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7920353920986193439/executions/bs.3ae2c59e9d03f583/testcases/1)

### Stacktrace:
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '(view is an instance of android.view.ViewGroup and has descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)))' doesn't match the selected view.
Expected: (view is an instance of android.view.ViewGroup and has descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)))
     Got: no descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)) was found
View Details: RecyclerView{id=2131362349, res-name=sessions, visibility=VISIBLE, width=770, height=462, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@13e3f6e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.TabsTrayRobot.verifyTabsOrderAndCorespondingCloseButton(TabsTrayRobot.kt:21)
	at org.mozilla.focus.activity.MultitaskingTest$closeTabButtonTest$3.invoke(MultitaskingTest.kt:132)
	at org.mozilla.focus.activity.MultitaskingTest$closeTabButtonTest$3.invoke(MultitaskingTest.kt:131)
	at org.mozilla.focus.activity.robots.BrowserRobot$Transition.openTabsTray(BrowserRobot.kt:399)
	at org.mozilla.focus.activity.MultitaskingTest.closeTabButtonTest(MultitaskingTest.kt:131)
	... 31 trimmed
Caused by: junit.framework.AssertionFailedError: '(view is an instance of android.view.ViewGroup and has descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)))' doesn't match the selected view.
Expected: (view is an instance of android.view.ViewGroup and has descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)))
     Got: no descendant matching ((view is an instance of android.view.ViewGroup and has descendant matching (an instance of android.widget.TextView and view.getText() with or without transformation to match: is "localhost/tab1.html" and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching view.getId() is <2131361936>))) and (view.getParent() is an instance of android.view.ViewGroup and is at child index <0>)) was found
View Details: RecyclerView{id=2131362349, res-name=sessions, visibility=VISIBLE, width=770, height=462, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@13e3f6e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    

### Notes 
Same as #6709 the Tabs url's are displayed instead of the title in the tabs tray causing to fail at `verifyTabsOrderAndCorespondingCloseButton`

**Comment by AndiAJ** [comment]
Disabled the test in #6706

**Comment by AndiAJ** [comment]
Fixed in #6813 , closing for now.
