### ISSUE TITLE
Intermittent UI test failure - < ErrorPagesTest. noNetworkConnectionErrorPageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6732]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:53)
	at org.mozilla.focus.activity.ErrorPagesTest$noNetworkConnectionErrorPageTest$2.invoke(ErrorPagesTest.kt:56)
	at org.mozilla.focus.activity.ErrorPagesTest$noNetworkConnectionErrorPageTest$2.invoke(ErrorPagesTest.kt:55)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:111)
	at org.mozilla.focus.activity.ErrorPagesTest.noNetworkConnectionErrorPageTest(ErrorPagesTest.kt:55)

**Comment by sv-ohorvath** [comment]
A11y issue backed out from AC. Can reopen if it fails again

**Comment by AndiAJ** [comment]
Flaky 1x on 3/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9116338287357213083/executions/bs.c99716536794cd80/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:53)
	at org.mozilla.focus.activity.ErrorPagesTest$noNetworkConnectionErrorPageTest$2.invoke(ErrorPagesTest.kt:56)
	at org.mozilla.focus.activity.ErrorPagesTest$noNetworkConnectionErrorPageTest$2.invoke(ErrorPagesTest.kt:55)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.ErrorPagesTest.noNetworkConnectionErrorPageTest(ErrorPagesTest.kt:55)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
