### ISSUE TITLE
Intermittent UI test failure - < ErrorPagesTest. badURLCheckTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6733]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:53)
	at org.mozilla.focus.activity.ErrorPagesTest$badURLCheckTest$2.invoke(ErrorPagesTest.kt:44)
	at org.mozilla.focus.activity.ErrorPagesTest$badURLCheckTest$2.invoke(ErrorPagesTest.kt:43)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:111)
	at org.mozilla.focus.activity.ErrorPagesTest.badURLCheckTest(ErrorPagesTest.kt:43)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098298358948092994/executions/bs.188e054f098bb4d3/testcases/1)

**Comment by sv-ohorvath** [comment]
A11y issue backed out from AC. Can reopen if it fails again

**Comment by AndiAJ** [comment]
💥  Failed 1x on 3/30 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9116338287357213083/executions/bs.93c0cd41c3cb8ea4/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9116338287357213083/executions/bs.f953c9241bda83a5/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:53)
	at org.mozilla.focus.activity.ErrorPagesTest$badURLCheckTest$2.invoke(ErrorPagesTest.kt:44)
	at org.mozilla.focus.activity.ErrorPagesTest$badURLCheckTest$2.invoke(ErrorPagesTest.kt:43)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.ErrorPagesTest.badURLCheckTest(ErrorPagesTest.kt:43)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
💥  Failed 1x [here](https://github.com/mozilla-mobile/focus-android/pull/7118)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8266028813767143728/executions/bs.28fd80b94b721746/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8266028813767143728/executions/bs.90e5a6b1086b16d/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Re-enabled in https://github.com/mozilla-mobile/focus-android/pull/7154
