### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest. blockUnwantedSoftwarePageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6734]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:53)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:80)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:79)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:111)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockUnwantedSoftwarePageTest(SafeBrowsingTest.kt:79)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/23 Main. [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7805666101114109673/executions/bs.13be328609663045/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098298358948092994/executions/bs.605c9efcfaecd6d7/testcases/1)

**Comment by AndiAJ** [comment]
💥  Failed 1x on 3/30 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5983470003981851466/executions/bs.710781a5fcc5e483/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5983470003981851466/executions/bs.a260476c6d8851c9/testcases/1)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
