### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest. blockHarmfulPageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6742]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:53)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockHarmfulPageTest$2.invoke(SafeBrowsingTest.kt:92)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockHarmfulPageTest$2.invoke(SafeBrowsingTest.kt:91)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:111)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockHarmfulPageTest(SafeBrowsingTest.kt:91)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098298358948092994/executions/bs.707bc660841697ef/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8380194385992359688/executions/bs.8898276be1331a00/testcases/1)

**Comment by sv-ohorvath** [comment]
A11y issue backed out from AC. Can reopen if it fails again

**Comment by Archaeopteryx** [comment]
These failures got frequent again ([example](https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098553824899435090)) - https://bugzilla.mozilla.org/show_bug.cgi?id=1758540 relanded.
