### ISSUE TITLE
Intermittent UI test failure - < FirstRunTest. verifySwitchToDesktopSiteLinkFromTips >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6775]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=Switch on Desktop Site]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.HomeScreenRobot$Transition.clickLinkFromTips(HomeScreenRobot.kt:127)
	at org.mozilla.focus.activity.FirstRunTest.verifySwitchToDesktopSiteLinkFromTips(FirstRunTest.kt:145)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8230334395608195575/executions/bs.41624960918305f3/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6829641651977842799/executions/bs.a503cecf866f4ba6/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=Switch on Desktop Site]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.HomeScreenRobot$Transition.clickLinkFromTips(HomeScreenRobot.kt:129)
	at org.mozilla.focus.activity.FirstRunTest.verifySwitchToDesktopSiteLinkFromTips(FirstRunTest.kt:149)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for approx. a month.
