### ISSUE TITLE
Sanitize external intents

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/focus-android#6795]
This is created for https://github.com/mozilla-mobile/android-components/issues/11877

**Comment by iorgamgabriel** [comment]
I tested with Focus old versions and the latest  one and I managed to crash it . I send an intent from Fenix with a Parcelable intentExtra to Focus . Both the apps are open , Fenix in foreground and Focus in background and I got this crash 

2022-04-01 17:37:02.953 25596-25596/org.mozilla.focus.debug E/Parcel: Class not found when unmarshalling: org.mozilla.fenix.Student
    java.lang.ClassNotFoundException: org.mozilla.fenix.Student
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3390)
        at android.os.Parcel.readParcelable(Parcel.java:3324)
        at android.os.Parcel.readValue(Parcel.java:3226)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.containsKey(BaseBundle.java:516)
        at mozilla.components.lib.crash.Crash$Companion.isCrashIntent(Crash.kt:162)
        at org.mozilla.focus.activity.MainActivity.onNewIntent(MainActivity.kt:153)
        at android.app.Activity.performNewIntent(Activity.java:8067)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1429)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1442)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3836)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3843)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
