### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest. saveImageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6808]
### Firebase Test Run: [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6945874927224620376/executions/bs.e64c9dca52dae100/testcases/1)
Provide a Firebase test run report link here showcasing the problem
### Stacktrace:
03-30 16:03:59.043: I/WindowManager(472): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 79cf9a1 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5000ms for FocusEvent(hasFocus=false)
03-30 16:03:59.251: I/ActivityManager(472): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
03-30 16:03:59.251: I/ActivityManager(472): Killing 12383:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 16:03:59.254: W/Binder(12329): Caught a RuntimeException from the binder stub implementation.
03-30 16:03:59.254: W/Binder(12329): java.lang.SecurityException: Calling from not trusted UID!
03-30 16:03:59.254: W/Binder(12329): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
03-30 16:03:59.254: W/Binder(12329): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
03-30 16:03:59.254: W/Binder(12329): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
03-30 16:03:59.254: W/Binder(12329): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
03-30 16:03:59.254: W/Binder(12329): 	at android.os.Binder.execTransact(Binder.java:1123)
03-30 16:03:59.257: I/ServiceChildProcess(13009): Destroying GeckoServiceChildProcess
03-30 16:03:59.261: I/ServiceChildProcess(13135): Destroying GeckoServiceChildProcess
03-30 16:03:59.263: W/ActivityTaskManager(472): Force removing ActivityRecord{cd03fb1 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
03-30 16:03:59.266: I/ActivityManager(472): Killing 13009:org.mozilla.focus.debug:tab18/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 16:03:59.270: I/ActivityManager(472): Killing 13135:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
03-30 16:03:59.276: D/WindowManager(472): notifyANR took 251ms
03-30 16:03:59.300: D/AndroidRuntime(12329): Shutting down VM

### Notes
[Logcat](https://00f74ba44bb506f8a1198f2192ff52c0305cf5ec32-apidata.googleusercontent.com/download/storage/v1/b/focus_android_test_artifacts/o/2022-03-30_22-52-00.600813_xMUY%2Fmatrix_0%2FPixel3-30-en-portrait-shard_85%2Flogcat?jk=AFshE3UiUZijZ0anLqvw0gFTu23ahxyMSLAS2bsi8zNn6Pa7LZNvsGDyoxh1AkI-Yach15L2ka3YPgBO0dAI2rwGLekfbQp496yQtzoB0o8PcajtJk4skDCQQnK5evvtiRpis-EFv5Rxup73NJhhlFkpnDXvcjVOFL6vpkFfbo3Br6JbDULdsGfoF0iMLJqT13Gv_0eP5JBgr2om8fCo9gh6JzHYtFUdWVWhEdRgg2D5qDsZHlEQhDZLmRkdkMCLWXp7II7VK35_FZ8Wl4pq7-d-9H6G0PJk6diBuOuuh3uo4Nw4nabegA3pFq5afn4tAnfvku0dgnF7_Pelihl9t9XNzyhA_Mebc8_Enrd5KQNJ2FPgzM1jeaFZa0xuHbh0HhSO0SQZTTJ12TUzj9tGTJcVOuh0OCAfSFRFUPkFgoqD9IL0mxIRNxGyrw7F3rHpjbWB1sJ-uiErJGoejpoNP6jMcdApGXrNl4zm4dGkL5vpBIpCqG791fujewpioVa8s7gMOpbwGfV5h21cwTmV6VGr0i0r5paiFGe8d1ejlSgNtrscbnQomdsQlnp1ojXGy6m6mYswma2_MIiKMYjgDTcc9jOL32UFeddA6rSN5ASp21b1ejTYeA3UdAd9-tomQEZ0pw_LWN07Rqb5xhBKMLGM4WdkTLz1TFbOnUegYzBcNYJpwE34eZtXLDtloGVJVSk7P-kMdhJPBcN2B32NtrmA98o9PTsXTzN1wNcFhkPSBr-R6w5ZiPapR_kaolTM6zUkmwyrWkQwLDD1U4sdcjQLZxw9PgQfVxn3DF1exvFdZ9t077yHZm42rsXawlnXhHA23oN0G140hlmg6sMMrFs0ejbxr2WdF-_ntyl5ct846zGkj1ZsfxM-OJni3Ka2iWiqY-tUeMcPme4CLupfa9vAn3552EHtNkPhENAVg4LFj96_m40DQSabjQiO_WbmcpeYW7kbH1auBCsqBhSt8zbu-i1CiUEjDQAhKkap1KT-LCn1CyzVkeDO1BgSD0Qg-3WhJZxfdzVRZTcQDS1oLQyJRkMOqng8BcIzyTuib_cZ7Jl0bYWZNxOWDNw5tUUlDlfZteDrgQWXzauboKgdB_0U-3vyfMj2Ucke0uY8olxFe-Oc5NqRLCp6KaxkgRMLZTdHdA&isca=1)
❗ Similar with the ANR reported in [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
