### ISSUE TITLE
Intermittent UI test failure - < SettingsTest.verifyPrivacySettingsMenuTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6835]
### Stacktrace:
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=16908304, res-name=summary, visibility=VISIBLE, width=52, height=53, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@3fdbff8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=103.0, text=On, input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.SettingsPrivacyMenuRobot.verifyPrivacySettingsItems(SettingsPrivacyMenuRobot.kt:71)
	at org.mozilla.focus.activity.SettingsTest$verifyPrivacySettingsMenuTest$4.invoke(SettingsTest.kt:49)
	at org.mozilla.focus.activity.SettingsTest$verifyPrivacySettingsMenuTest$4.invoke(SettingsTest.kt:48)
	at org.mozilla.focus.activity.robots.SettingsRobot$Transition.openPrivacySettingsMenu(SettingsRobot.kt:58)
	at org.mozilla.focus.activity.SettingsTest.verifyPrivacySettingsMenuTest(SettingsTest.kt:48)
	... 31 trimmed
Caused by: junit.framework.AssertionFailedError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=16908304, res-name=summary, visibility=VISIBLE, width=52, height=53, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@3fdbff8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=103.0, text=On, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Failed 1x on 4/6 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6312638211369993871/executions/bs.7947ccde08825db3/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6312638211369993871/executions/bs.3556e529bdc12689/testcases/1)

**Comment by AndiAJ** [comment]
Fixed in #6845 , closing for now
