### ISSUE TITLE
Intermittent UI test failure - < OpenInExternalBrowserDialogueTest. openPageInExternalAppTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6850]
### Stacktrace:
04-07 09:48:19.840: I/ActivityManager(483): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
04-07 09:48:19.841: I/ActivityManager(483): Killing 12791:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
04-07 09:48:19.841: W/Binder(12691): Caught a RuntimeException from the binder stub implementation.
04-07 09:48:19.841: W/Binder(12691): java.lang.SecurityException: Calling from not trusted UID!
04-07 09:48:19.841: W/Binder(12691): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
04-07 09:48:19.841: W/Binder(12691): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
04-07 09:48:19.841: W/Binder(12691): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
04-07 09:48:19.841: W/Binder(12691): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
04-07 09:48:19.841: W/Binder(12691): 	at android.os.Binder.execTransact(Binder.java:1123)
04-07 09:48:19.843: W/ActivityTaskManager(483): Force removing ActivityRecord{fa7df76 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
04-07 09:48:19.847: I/ServiceChildProcess(13441): Destroying GeckoServiceChildProcess
04-07 09:48:19.853: D/AndroidRuntime(12691): Shutting down VM
04-07 09:48:19.861: I/ActivityManager(483): Killing 13316:org.mozilla.focus.debug:tab26/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
04-07 09:48:19.889: I/ActivityManager(483): Killing 13441:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
04-07 09:48:19.890: D/WindowManager(483): notifyANR took 431ms
### Notes
Similar ANR as reported in [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a couple of month.
