### ISSUE TITLE
Intermittent UI test failure - < CustomTabTest. openCustomTabInFocusTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6861]
### Stacktrace:
junit.framework.AssertionFailedError: Actual url: http://localhost:40255/genericPage.html
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at org.mozilla.focus.activity.robots.CustomTabRobot.verifyPageURL(CustomTabRobot.kt:66)
	at org.mozilla.focus.activity.CustomTabTest$openCustomTabInFocusTest$4.invoke(CustomTabTest.kt:115)
	at org.mozilla.focus.activity.CustomTabTest$openCustomTabInFocusTest$4.invoke(CustomTabTest.kt:113)
	at org.mozilla.focus.activity.robots.CustomTabRobotKt.customTab(CustomTabRobot.kt:112)
	at org.mozilla.focus.activity.CustomTabTest.openCustomTabInFocusTest(CustomTabTest.kt:113)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a couple of month.
