### ISSUE TITLE
NimbusFeatureException: A Context is needed but not available.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/focus-android#6989]
Sentry link: https://sentry.io/organizations/mozilla/issues/3251410449/

```java
org.mozilla.experiments.nimbus.internal.NimbusFeatureException: A Context is needed but not available. Consider passing in a context to the value() method when close to startup
    at org.mozilla.experiments.nimbus.internal.FeatureHolder.value(FeatureHolder.kt:2)
    at org.mozilla.experiments.nimbus.internal.FeatureHolder.value$default(FeatureHolder.kt:1)
    at org.mozilla.focus.tabs.MergeTabsMiddleware.invoke(MergeTabsMiddleware.kt:6)
    at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
    at org.mozilla.focus.browser.BlockedTrackersMiddleware.invoke(BlockedTrackersMiddleware.kt:13)
    at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
    at mozilla.components.feature.search.middleware.AdsTelemetryMiddleware.invoke(AdsTelemetryMiddleware.kt:51)
    at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
    at mozilla.components.feature.prompts.PromptMiddleware.invoke(PromptMiddleware.kt:18)
    at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
    at org.mozilla.focus.search.SearchFilterMiddleware.invoke(SearchFilterMiddleware.kt:13)
    at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
    at mozilla.components.feature.search.middleware.SearchMiddleware.invoke(SearchMiddleware.kt:12)
    at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
    at mozilla.components.feature.search.region.RegionMiddleware.invoke(RegionMiddleware.kt:7)
    at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
    at org.mozilla.focus.engine.SanityCheckMiddleware.invoke(SanityCheckMiddleware.kt:3)
```

**Comment by jonalmeida** [comment]
I ran into these crashes over the last few days and today I looked into where the exception is coming from, and found that it was removed in newer versions of Nimbus: https://github.com/mozilla/application-services/commit/c2823f590b26c259becd103e76050bbff1d272f2#diff-ada4355049b521b13581477fca1f1c0f4f68404558607f74162d559221247d13L30-L31

We are updating to a newer version of [A-S today](https://github.com/mozilla-mobile/android-components/pull/12120), so when we update to a newer A-C version, I'll come back here to see if these exceptions continue.

**Comment by ionutbedregeanu** [comment]
Last seen was 9 days ago, I think we can close it. Feel free to reopen it if I'm wrong
