### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest. blockHarmfulPageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#6997]
### Stacktrace:
05-09 23:10:06.003: I/WindowManager(481): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: c0c3fa9 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)
05-09 23:10:06.167: I/ActivityManager(481): Force stopping org.mozilla.focus.debug appid=10151 user=0: finished inst
05-09 23:10:06.167: I/ActivityManager(481): Killing 15936:org.mozilla.focus.debug:tab8/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-09 23:10:06.148: I/chatty(1830): uid=1041(audioserver) writer identical 12 lines
05-09 23:10:06.163: W/audio_hw_generic(1830): Hardware backing HAL too slow, could only write 0 of 661 frames
05-09 23:10:06.168: W/Binder(15313): Caught a RuntimeException from the binder stub implementation.
05-09 23:10:06.168: W/Binder(15313): java.lang.SecurityException: Calling from not trusted UID!
05-09 23:10:06.168: W/Binder(15313): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-09 23:10:06.168: W/Binder(15313): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-09 23:10:06.168: W/Binder(15313): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-09 23:10:06.168: W/Binder(15313): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-09 23:10:06.168: W/Binder(15313): 	at android.os.Binder.execTransact(Binder.java:1123)
05-09 23:10:06.177: I/ActivityManager(481): Killing 15437:org.mozilla.focus.debug/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-09 23:10:06.178: W/audio_hw_generic(1830): Hardware backing HAL too slow, could only write 0 of 661 frames
05-09 23:10:06.181: I/ServiceChildProcess(16025): Destroying GeckoServiceChildProcess
05-09 23:10:06.182: W/ActivityTaskManager(481): Force removing ActivityRecord{ecb5241 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
05-09 23:10:06.185: I/ActivityManager(481): Killing 16025:org.mozilla.focus.debug:gpu/u0a151 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-09 23:10:06.193: W/audio_hw_generic(1830): Hardware backing HAL too slow, could only write 0 of 661 frames
05-09 23:10:06.198: D/WindowManager(481): notifyANR took 218ms
### Notes: Similar with [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
