### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest.blockHarmfulPageTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7099]
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098553824899435090/executions/bs.c8a58218e98cf530/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098553824899435090/executions/bs.9caee9f592d1c136/testcases/1/test-cases)
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockHarmfulPageTest$2.invoke(SafeBrowsingTest.kt:95)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockHarmfulPageTest$2.invoke(SafeBrowsingTest.kt:94)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockHarmfulPageTest(SafeBrowsingTest.kt:94)

**Comment by AndiAJ** [comment]
💥  Failed 1x on 5/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6789958245853921790/executions/bs.8b49d198fb32897/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6789958245853921790/executions/bs.4af0995997451f/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockHarmfulPageTest$2.invoke(SafeBrowsingTest.kt:94)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockHarmfulPageTest$2.invoke(SafeBrowsingTest.kt:93)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockHarmfulPageTest(SafeBrowsingTest.kt:93)

**Comment by AndiAJ** [comment]
Closing in favour of #7113
