### ISSUE TITLE
Intermittent UI test failure - < MediaPlaybackTest. testAudioPlayback >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7105]
### Firebase Test Run: 💥 Failed 1x on 5/25 Main

[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4992641742921796752/executions/bs.16c5627a1dcae3b2/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4992641742921796752/executions/bs.ed74e3b98e4da76e/testcases/1)

### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.waitForPlaybackToStart(BrowserRobot.kt:168)
	at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:68)
	at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:66)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.MediaPlaybackTest.testAudioPlayback(MediaPlaybackTest.kt:66)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4791950053180779190/executions/bs.e18adada97fc70d1/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5457284836995453253/executions/bs.f6692d43467abd14/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.waitForPlaybackToStart(BrowserRobot.kt:168)
	at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:68)
	at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:66)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.MediaPlaybackTest.testAudioPlayback(MediaPlaybackTest.kt:66)
