### ISSUE TITLE
Intermittent UI test failure - <Classname.allowAnalyticsTrackersTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7107]
### Stacktrace:
05-24 17:43:01.447: I/WindowManager(481): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: d1fc703 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5003ms for FocusEvent(hasFocus=false)
05-24 17:43:01.432: I/chatty(1754): uid=1041(audioserver) writer identical 95 lines
05-24 17:43:01.447: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.450: E/QueryController(13912): Got null root node from accessibility - Retrying...
05-24 17:43:01.462: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.537: I/chatty(1754): uid=1041(audioserver) writer identical 5 lines
05-24 17:43:01.552: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.564: D/GeckoViewContent(13912): handleEvent: DOMWindowClose
05-24 17:43:01.565: D/GeckoViewProgressDelegate[C](14511): handleEvent: MozAfterPaint
05-24 17:43:01.567: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.571: D/GeckoViewNavigation(13912): onDisable
05-24 17:43:01.573: D/GeckoViewProcessHangMonitor(13912): onDisable
05-24 17:43:01.574: D/GeckoViewModule(13912): unregisterListener
05-24 17:43:01.578: D/GeckoViewProgressDelegate[C](14511): handleEvent: MozAfterPaint
05-24 17:43:01.578: D/GeckoViewProcessHangMonitor(13912): onDestroy
05-24 17:43:01.579: D/GeckoViewProgress(13912): onDisable
05-24 17:43:01.580: D/GeckoViewModule(13912): unregisterListener
05-24 17:43:01.581: D/GeckoViewSelectionActionDelegate[C](14511): handleEvent: visibilitychange
05-24 17:43:01.582: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.583: D/GeckoViewSelectionAction(13912): onDisable
05-24 17:43:01.585: D/GeckoViewModule(13912): unregisterListener
05-24 17:43:01.590: D/GeckoViewModule(13912): unregisterListener
05-24 17:43:01.597: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.612: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.614: D/GeckoViewMediaControl(13912): onDisable
05-24 17:43:01.615: D/GeckoViewModule(13912): unregisterListener
05-24 17:43:01.622: D/GeckoViewSelectionActionDelegate[C](14511): handleEvent: visibilitychange
05-24 17:43:01.623: D/GeckoViewAutoFill[C](14511): handleEvent: pagehide
05-24 17:43:01.627: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.642: I/chatty(1754): uid=1041(audioserver) writer identical 1 line
05-24 17:43:01.656: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.661: I/Choreographer(13912): Skipped 313 frames!  The application may be doing too much work on its main thread.
05-24 17:43:01.671: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.731: I/chatty(1754): uid=1041(audioserver) writer identical 4 lines
05-24 17:43:01.746: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.747: I/OpenGLRenderer(13912): Davey! duration=5310ms; Flags=0, IntendedVsync=710688154809, Vsync=715904821267, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=715915425913, AnimationStart=715915428678, PerformTraversalsStart=715915429216, DrawStart=715922119794, SyncQueued=715922782994, SyncStart=715925989894, IssueDrawCommandsStart=715926130049, SwapBuffers=715983312082, FrameCompleted=716002028156, DequeueBufferDuration=571447, QueueBufferDuration=2959744, GpuCompleted=690254497869, 
05-24 17:43:01.752: I/ActivityManager(481): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
05-24 17:43:01.752: I/ActivityManager(481): Killing 13912:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-24 17:43:01.760: W/ActivityTaskManager(481): Force removing ActivityRecord{6d5fdb6 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
05-24 17:43:01.761: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.762: I/ServiceChildProcess(14654): Destroying GeckoServiceChildProcess
05-24 17:43:01.763: I/ServiceChildProcess(14511): Destroying GeckoServiceChildProcess
05-24 17:43:01.763: W/Binder(13794): Caught a RuntimeException from the binder stub implementation.
05-24 17:43:01.763: W/Binder(13794): java.lang.SecurityException: Calling from not trusted UID!
05-24 17:43:01.763: W/Binder(13794): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-24 17:43:01.763: W/Binder(13794): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-24 17:43:01.763: W/Binder(13794): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-24 17:43:01.763: W/Binder(13794): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-24 17:43:01.763: W/Binder(13794): 	at android.os.Binder.execTransact(Binder.java:1123)
05-24 17:43:01.775: I/ActivityManager(481): Killing 14511:org.mozilla.focus.debug:tab39/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-24 17:43:01.776: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.781: I/PeriodicStatsRunner(2194): PeriodicStatsRunner.call():180 call()
05-24 17:43:01.781: I/PeriodicStatsRunner(2194): PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
05-24 17:43:01.791: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.794: D/AndroidRuntime(13794): Shutting down VM
05-24 17:43:01.806: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.813: I/focus.debug:gp(14654): System.exit called, status: 0
05-24 17:43:01.813: I/AndroidRuntime(14654): VM exiting with result code 0, cleanup skipped.
05-24 17:43:01.821: W/audio_hw_generic(1754): Hardware backing HAL too slow, could only write 0 of 661 frames
05-24 17:43:01.884: I/ActivityManager(481): Killing 14654:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
05-24 17:43:01.886: D/WindowManager(481): notifyANR took 457ms

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
