### ISSUE TITLE
Intermittent UI test failure - < SafeBrowsingTest. blockMalwarePageTest > <SafeBrowsingTest. blockUnwantedSoftwarePageTest> <SafeBrowsingTest.blockHarmfulPageTest> <SafeBrowsingTest. blockPhishingPageTest> 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7113]
##  1.`blockMalwarePageTest`

💥  Failed 2x on 5/25 Main 

[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4992641742921796752/executions/bs.da51a36c86b0e3b4/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4992641742921796752/executions/bs.962eb2a05b8b3efe/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8860814377759403630/executions/bs.dea35dc0699ee31b/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8860814377759403630/executions/bs.ace2c695d362eca1/testcases/1/test-cases)

##  2.`blockUnwantedSoftwarePageTest `

💥 Failed 1x in https://github.com/mozilla-mobile/focus-android/pull/7101.
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6665406313744881905/executions/bs.8e00351f07fbfb7c/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6665406313744881905/executions/bs.c3f540727c33d6aa/testcases/1)

💥  Failed 1x on 5/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8860814377759403630/executions/bs.5b4a2b4152447db8/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8860814377759403630/executions/bs.1165df8458e850bb/testcases/1/test-cases)

Flaky 1x on 5/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6789958245853921790/executions/bs.f02307ca7a7f52ec/testcases/1)

##  3.`blockHarmfulPageTest `
💥  Failed 1x on 5/24 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098553824899435090/executions/bs.c8a58218e98cf530/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098553824899435090/executions/bs.9caee9f592d1c136/testcases/1/test-cases)

Flaky 1x on 5/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7223607968309304028/executions/bs.5756846464a238da/testcases/1/test-cases)

💥  Failed 1x on 5/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6789958245853921790/executions/bs.8b49d198fb32897/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6789958245853921790/executions/bs.4af0995997451f/testcases/1)

Flaky 1x on 5/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4992641742921796752/executions/bs.a1bbb030eeeaa9f0/testcases/1)

##  4.`blockPhishingPageTest `
💥  Failed 1x on 5/24 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098553824899435090/executions/bs.a5342906f6113f66/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098553824899435090/executions/bs.34e11c796fb3db6d/testcases/1)

💥  Failed 1x on 5/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4992641742921796752/executions/bs.1b24b59a3bef9ba0/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4992641742921796752/executions/bs.c97576d6d8e8c536/testcases/1/test-cases)

### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockMalwarePageTest$2.invoke(SafeBrowsingTest.kt:59)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockMalwarePageTest$2.invoke(SafeBrowsingTest.kt:58)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockMalwarePageTest(SafeBrowsingTest.kt:58)

**Comment by AndiAJ** [comment]
Ran the tests 10x on Firebase

• With the latest AC upgrades (102.0.20220524015637 and 102.0.20220524143152) and these were the results:
matrix | result | logs | details
-- | -- | -- | --
[matrix-2hai3ihmu4gtc](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8699511863726785295) | flaky | logs | 2 test cases passed, 1 flaky
[matrix-3slac6nrvqw9k](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6131927492548032664) | failure | logs | 1 test cases failed, 2 passed
[matrix-2g07v2c6ji1b2](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8098704046728784966) | flaky | logs | 2 test cases passed, 1 flaky
[matrix-3s2314db7jpag](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8736850265329883107) | success | logs | 3 test cases passed
[matrix-189sxewf1odk4](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8130898167344478890) | flaky | logs | 2 test cases passed, 1 flaky
[matrix-1ns6upu9yka0k](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8433739947379547827) | success | logs | 3 test cases passed
[matrix-1fizndgxck0tw](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5578800602404038209) | success | logs | 3 test cases passed
[matrix-1ucead3nvitjo](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5181803126970773588) | failure | logs | 1 test cases failed, 2 passed
[matrix-wj644tsvuoy9a](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8837545603521339149) | success | logs | 3 test cases passed
[matrix-364giiqc61glh](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9018616382019152776) | flaky | logs | 1 test cases passed, 2 flaky

❗ In all cases the tests failed or were flaky due to:
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:82)
at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:81)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
at org.mozilla.focus.activity.SafeBrowsingTest.blockUnwantedSoftwarePageTest(SafeBrowsingTest.kt:81)
```

• Without the latests AC upgrades and these were the results:

matrix | result | logs | details
-- | -- | -- | --
[matrix-5rx46k9at1ysa](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9160846862996087334) | success | logs | 3 test cases passed
[matrix-1z13ytmc5mb1w](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5453423147154025095) | success | logs | 3 test cases passed
[matrix-2nqi11fpxi9gj](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/9016555475631931255) | success | logs | 3 test cases passed
[matrix-11eteiyzrkgra](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7171582343623323556) | success | logs | 3 test cases passed
[matrix-16aqzn1g3apx4](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7064333244983309664) | success | logs | 3 test cases passed
[matrix-12colrbmnqhvn](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8397594999007096437) | success | logs | 3 test cases passed
[matrix-2bzry9fj9jwci](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8433657807449581342) | flaky | logs | 2 test cases passed, 1 flaky
[matrix-32bi3we2hx2pa](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8284228123402755927) | flaky | logs | 2 test cases passed, 1 flaky
[matrix-1ii1mh97zdvrj](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7162306099771918114) | success | logs | 3 test cases passed
[matrix-2bkflheb0fnpd](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7599290576663876128) | success | logs | 3 test cases passed

✅ Flaky 2x due to the know ANR [#24047](https://github.com/mozilla-mobile/fenix/issues/24047)

**Comment by AndiAJ** [comment]
`blockUnwantedSoftwarePageTest` flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5531270115325074127/executions/bs.c58101a420f6947c/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:82)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockUnwantedSoftwarePageTest$2.invoke(SafeBrowsingTest.kt:81)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockUnwantedSoftwarePageTest(SafeBrowsingTest.kt:81)

**Comment by AndiAJ** [comment]
💥 `blockPhishingPageTest` failed 1x on 5/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8436812599130824924/executions/bs.b645a2f19e4afc85/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8436812599130824924/executions/bs.76880b62d6fcf907/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockPhishingPageTest$2.invoke(SafeBrowsingTest.kt:70)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockPhishingPageTest$2.invoke(SafeBrowsingTest.kt:69)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockPhishingPageTest(SafeBrowsingTest.kt:69)

**Comment by AndiAJ** [comment]
`blockMalwarePageTest` flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8436812599130824924/executions/bs.970425a60d9b2099/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockMalwarePageTest$2.invoke(SafeBrowsingTest.kt:58)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockMalwarePageTest$2.invoke(SafeBrowsingTest.kt:57)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockMalwarePageTest(SafeBrowsingTest.kt:57)
    

`blockHarmfulPageTest` flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8436812599130824924/executions/bs.560eaf5ce240d7ab/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockHarmfulPageTest$2.invoke(SafeBrowsingTest.kt:94)
	at org.mozilla.focus.activity.SafeBrowsingTest$blockHarmfulPageTest$2.invoke(SafeBrowsingTest.kt:93)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SafeBrowsingTest.blockHarmfulPageTest(SafeBrowsingTest.kt:93)

**Comment by AndiAJ** [comment]
Re-enabled in #7154
