### ISSUE TITLE
Intermittent UI test failure - < MediaPlaybackTest. testMediaContentNotification >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7163]
### Firebase Test Run: [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4791950053180779190/executions/bs.e5fbc90874e9477f)
ANR issues tracking moved at https://github.com/mozilla-mobile/focus-android/issues/7344

**Comment by sv-ohorvath** [comment]
Flaky on 7/6: 
https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7167323140174625877/details?stepId=bs.9618170d0f3f7524&testCaseId=1
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.focus.activity.robots.BrowserRobot.waitForPlaybackToStart(BrowserRobot.kt:168)
at org.mozilla.focus.activity.MediaPlaybackTest$testMediaContentNotification$2.invoke(MediaPlaybackTest.kt:85)
at org.mozilla.focus.activity.MediaPlaybackTest$testMediaContentNotification$2.invoke(MediaPlaybackTest.kt:83)
at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
at org.mozilla.focus.activity.MediaPlaybackTest.testMediaContentNotification(MediaPlaybackTest.kt:83)
```
