### ISSUE TITLE
Intermittent UI test failure - < ThreeDotMainMenuTest. findInPageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7164]
### Stacktrace:
06-02 16:52:29.639: I/WindowManager(481): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: 90b62ae org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5004ms for FocusEvent(hasFocus=false)
06-02 16:52:29.750: I/ActivityManager(481): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-02 16:52:29.750: I/ActivityManager(481): Killing 12042:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 16:52:29.747: I/chatty(1855): uid=1041(audioserver) writer identical 101 lines
06-02 16:52:29.762: W/audio_hw_generic(1855): Hardware backing HAL too slow, could only write 0 of 661 frames
06-02 16:52:29.763: D/AndroidRuntime(11890): Shutting down VM
06-02 16:52:29.765: W/ActivityTaskManager(481): Force removing ActivityRecord{62ec4fa u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t11 f}}: app died, no saved state
06-02 16:52:29.774: I/ServiceChildProcess(12783): Destroying GeckoServiceChildProcess
06-02 16:52:29.777: W/audio_hw_generic(1855): Hardware backing HAL too slow, could only write 0 of 661 frames
06-02 16:52:29.792: I/chatty(1855): uid=1041(audioserver) writer identical 1 line
06-02 16:52:29.807: W/audio_hw_generic(1855): Hardware backing HAL too slow, could only write 0 of 661 frames
06-02 16:52:29.811: W/Binder(11890): Caught a RuntimeException from the binder stub implementation.
06-02 16:52:29.811: W/Binder(11890): java.lang.SecurityException: Calling from not trusted UID!
06-02 16:52:29.811: W/Binder(11890): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-02 16:52:29.811: W/Binder(11890): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-02 16:52:29.811: W/Binder(11890): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-02 16:52:29.811: W/Binder(11890): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-02 16:52:29.811: W/Binder(11890): 	at android.os.Binder.execTransact(Binder.java:1123)
06-02 16:52:29.819: I/cus.debug:tab3(12783): System.exit called, status: 0
06-02 16:52:29.819: I/AndroidRuntime(12783): VM exiting with result code 0, cleanup skipped.
06-02 16:52:29.823: W/audio_hw_generic(1855): Hardware backing HAL too slow, could only write 0 of 661 frames
06-02 16:52:29.845: I/ActivityManager(481): Killing 12783:org.mozilla.focus.debug:tab39/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 16:52:29.846: I/ActivityManager(481): Killing 12937:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-02 16:52:29.847: D/WindowManager(481): notifyANR took 217ms

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
