### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest. verifySelectTextTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7185]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:153)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:148)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifySelectTextTest(WebControlsTest.kt:148)

**Comment by AndiAJ** [comment]
[Flaky 1x on 6/12 Main [Firebase link](url)](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8986749905994727199/executions/bs.c4bde207971d8518/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:54)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:153)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:148)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifySelectTextTest(WebControlsTest.kt:148)

**Comment by sv-ohorvath** [comment]
Closing as it hasn't failed in a month
