### ISSUE TITLE
Intermittent UI test failure - < FirstRunTest. verifyAllowListLinkFromTips >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7218]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:77)
	at org.mozilla.focus.activity.FirstRunTest$verifyAllowListLinkFromTips$2.invoke(FirstRunTest.kt:134)
	at org.mozilla.focus.activity.FirstRunTest$verifyAllowListLinkFromTips$2.invoke(FirstRunTest.kt:133)
	at org.mozilla.focus.activity.robots.HomeScreenRobot$Transition.clickLinkFromTips(HomeScreenRobot.kt:131)
	at org.mozilla.focus.activity.FirstRunTest.verifyAllowListLinkFromTips(FirstRunTest.kt:133)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/30 [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8578281270252513802/executions/bs.512cad8b676a0901/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=Add it to the Allowlist in Settings]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.HomeScreenRobot$Transition.clickLinkFromTips(HomeScreenRobot.kt:129)
	at org.mozilla.focus.activity.FirstRunTest.verifyAllowListLinkFromTips(FirstRunTest.kt:133)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month.
