### ISSUE TITLE
Intermittent UI test failure - < SearchTest.testSearchBarShowsSearchTermOnEdit>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7295]
### Stacktrace:
06-29 07:12:30.905: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity.  Reason: c26dd4e org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity (server) is not responding. Waited 5004ms for FocusEvent(hasFocus=false)
06-29 07:12:30.979: I/ActivityManager(479): Force stopping org.mozilla.focus.debug appid=10152 user=0: finished inst
06-29 07:12:30.980: I/ActivityManager(479): Killing 12166:org.mozilla.focus.debug:tab3/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 07:12:30.959: I/chatty(1857): uid=1041(audioserver) writer identical 4 lines
06-29 07:12:30.974: W/audio_hw_generic(1857): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 07:12:30.983: W/Binder(11605): Caught a RuntimeException from the binder stub implementation.
06-29 07:12:30.983: W/Binder(11605): java.lang.SecurityException: Calling from not trusted UID!
06-29 07:12:30.983: W/Binder(11605): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-29 07:12:30.983: W/Binder(11605): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-29 07:12:30.983: W/Binder(11605): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-29 07:12:30.983: W/Binder(11605): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-29 07:12:30.983: W/Binder(11605): 	at android.os.Binder.execTransact(Binder.java:1123)
06-29 07:12:30.984: I/ActivityManager(479): Killing 11722:org.mozilla.focus.debug/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 07:12:30.987: W/ActivityTaskManager(479): Force removing ActivityRecord{154e538 u0 org.mozilla.focus.debug/org.mozilla.focus.activity.MainActivity t9 f}}: app died, no saved state
06-29 07:12:30.989: W/audio_hw_generic(1857): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 07:12:30.991: D/AndroidRuntime(11605): Shutting down VM
06-29 07:12:31.004: W/audio_hw_generic(1857): Hardware backing HAL too slow, could only write 0 of 661 frames
06-29 07:12:31.029: I/ActivityManager(479): Killing 12301:org.mozilla.focus.debug:gpu/u0a152 (adj 0): stop org.mozilla.focus.debug due to finished inst
06-29 07:12:31.032: D/WindowManager(479): notifyANR took 139ms

**Comment by sv-ohorvath** [comment]
closing as dupe, in favor if https://github.com/mozilla-mobile/focus-android/issues/7344
