### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest. verifySelectTextTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7363]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:55)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:153)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:148)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifySelectTextTest(WebControlsTest.kt:148)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6340838110948385526/executions/bs.6d838d362b8c7da9/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:55)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:153)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:148)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifySelectTextTest(WebControlsTest.kt:148)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5093201059899975063/executions/bs.96a58c9c6026ee79/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:55)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:153)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:148)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifySelectTextTest(WebControlsTest.kt:148)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4767363896300740315/executions/bs.5dc620746905b18f/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:55)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:153)
	at org.mozilla.focus.activity.WebControlsTest$verifySelectTextTest$2.invoke(WebControlsTest.kt:148)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifySelectTextTest(WebControlsTest.kt:148)

**Comment by sv-ohorvath** [comment]
Flaky on 7/28, on debug: [Firebase link](https://console.firebase.google.com/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7036589545097647112/executions/bs.8789a676af5312b2)

**Comment by csadilek** [comment]
We're setting this test to `@Ignore` because we had troubles landing today's A-C upgrade.

**Comment by AndiAJ** [comment]
Re-enabled with #7779
