### ISSUE TITLE
Intermittent UI test failure - < MozillaSupportPagesTest. openAboutPageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7438]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageURL(BrowserRobot.kt:78)
	at org.mozilla.focus.activity.MozillaSupportPagesTest$openAboutPageTest$6.invoke(MozillaSupportPagesTest.kt:78)
	at org.mozilla.focus.activity.MozillaSupportPagesTest$openAboutPageTest$6.invoke(MozillaSupportPagesTest.kt:77)
	at org.mozilla.focus.activity.robots.SettingsMozillaMenuRobot$Transition.openAboutPageLearnMoreLink(SettingsMozillaMenuRobot.kt:91)
	at org.mozilla.focus.activity.MozillaSupportPagesTest.openAboutPageTest(MozillaSupportPagesTest.kt:77)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month.
