### ISSUE TITLE
Intermittent UI test failure - < EnhancedTrackingProtectionSettingsTest. blockSocialTrackersTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7619]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyTrackingProtectionAlert(BrowserRobot.kt:64)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$blockSocialTrackersTest$4.invoke(EnhancedTrackingProtectionSettingsTest.kt:178)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$blockSocialTrackersTest$4.invoke(EnhancedTrackingProtectionSettingsTest.kt:177)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest.blockSocialTrackersTest(EnhancedTrackingProtectionSettingsTest.kt:177)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6070037464796140650/executions/bs.d4a20199bc4b5fb6/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyTrackingProtectionAlert(BrowserRobot.kt:64)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$blockSocialTrackersTest$4.invoke(EnhancedTrackingProtectionSettingsTest.kt:178)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$blockSocialTrackersTest$4.invoke(EnhancedTrackingProtectionSettingsTest.kt:177)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest.blockSocialTrackersTest(EnhancedTrackingProtectionSettingsTest.kt:177)

**Comment by AndiAJ** [comment]
Disabled in #7737

**Comment by AndiAJ** [comment]
Re-enabled with #7779
