### ISSUE TITLE
Intermittent UI test failure - < SettingsAdvancedTest. openLinksInAppsTest >

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla-mobile/focus-android#7659]
All recent PRs seem to be hitting these failures. Per Slack discussion with @AaronMT, let's disable for now to unblock things.
https://firefoxci.taskcluster-artifacts.net/HM353bieQr6WdbMfip8uzQ/0/public/results/HtmlErrorReport.html
https://firefoxci.taskcluster-artifacts.net/FgF9ilFNRESho8v-u3pjqw/0/public/results/HtmlErrorReport.html
https://firefoxci.taskcluster-artifacts.net/A2ihG42pTeaXwzQrjPJOkw/0/public/results/HtmlErrorReport.html

**Comment by AndiAJ** [comment]
Failed 1x on 9/15 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6365514467495781073/executions/bs.1843176042d83299/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6365514467495781073/executions/bs.83ef122edcec558/testcases/1)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobotKt.assertOpenLinksInAppsPrompt(BrowserRobot.kt:532)
	at org.mozilla.focus.activity.robots.BrowserRobotKt.access$assertOpenLinksInAppsPrompt(BrowserRobot.kt:1)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyOpenLinksInAppsPrompt(BrowserRobot.kt:234)
	at org.mozilla.focus.activity.SettingsAdvancedTest$openLinksInAppsTest$7.invoke(SettingsAdvancedTest.kt:64)
	at org.mozilla.focus.activity.SettingsAdvancedTest$openLinksInAppsTest$7.invoke(SettingsAdvancedTest.kt:61)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SettingsAdvancedTest.openLinksInAppsTest(SettingsAdvancedTest.kt:61)

**Comment by AndiAJ** [comment]
Re-enabled with #7779
