### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest. verifyCalendarFormTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7664]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.Spinner, PACKAGE NAME=org.mozilla.focus.debug, RESOURCE_ID=calendar]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickCalendarForm(BrowserRobot.kt:264)
	at org.mozilla.focus.activity.WebControlsTest$verifyCalendarFormTest$2.invoke(WebControlsTest.kt:167)
	at org.mozilla.focus.activity.WebControlsTest$verifyCalendarFormTest$2.invoke(WebControlsTest.kt:165)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyCalendarFormTest(WebControlsTest.kt:165)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5573141444597224666/executions/bs.7184aed6c647e695/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.Spinner, PACKAGE NAME=org.mozilla.focus.debug, RESOURCE_ID=calendar]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickCalendarForm(BrowserRobot.kt:254)
	at org.mozilla.focus.activity.WebControlsTest$verifyCalendarFormTest$2.invoke(WebControlsTest.kt:169)
	at org.mozilla.focus.activity.WebControlsTest$verifyCalendarFormTest$2.invoke(WebControlsTest.kt:167)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyCalendarFormTest(WebControlsTest.kt:167)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8180432287354109742/executions/bs.4246640c19161fdb/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.Spinner, PACKAGE NAME=org.mozilla.focus.debug, RESOURCE_ID=calendar]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickCalendarForm(BrowserRobot.kt:254)
	at org.mozilla.focus.activity.WebControlsTest$verifyCalendarFormTest$2.invoke(WebControlsTest.kt:169)
	at org.mozilla.focus.activity.WebControlsTest$verifyCalendarFormTest$2.invoke(WebControlsTest.kt:167)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyCalendarFormTest(WebControlsTest.kt:167)
