### ISSUE TITLE
Intermittent UI test failure - < SitePermissionsTest. testLocationSharingNotAllowed >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7665]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=Get Location]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickGetLocationButton(BrowserRobot.kt:87)
	at org.mozilla.focus.activity.SitePermissionsTest$testLocationSharingNotAllowed$2.invoke(SitePermissionsTest.kt:221)
	at org.mozilla.focus.activity.SitePermissionsTest$testLocationSharingNotAllowed$2.invoke(SitePermissionsTest.kt:220)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.SitePermissionsTest.testLocationSharingNotAllowed(SitePermissionsTest.kt:220)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
