### ISSUE TITLE
Intermittent UI test failure - < CustomTabTest. customTabNavigationButtonsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7666]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.CustomTabRobot.verifyPageContent(CustomTabRobot.kt:80)
	at org.mozilla.focus.activity.CustomTabTest$customTabNavigationButtonsTest$1.invoke(CustomTabTest.kt:136)
	at org.mozilla.focus.activity.CustomTabTest$customTabNavigationButtonsTest$1.invoke(CustomTabTest.kt:135)
	at org.mozilla.focus.activity.robots.CustomTabRobotKt.customTab(CustomTabRobot.kt:112)
	at org.mozilla.focus.activity.CustomTabTest.customTabNavigationButtonsTest(CustomTabTest.kt:135)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7413879851472276995/executions/bs.b3f3027df9517316/testcases/2)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.CustomTabRobot.verifyPageContent(CustomTabRobot.kt:83)
	at org.mozilla.focus.activity.CustomTabTest$customTabNavigationButtonsTest$1.invoke(CustomTabTest.kt:136)
	at org.mozilla.focus.activity.CustomTabTest$customTabNavigationButtonsTest$1.invoke(CustomTabTest.kt:135)
	at org.mozilla.focus.activity.robots.CustomTabRobotKt.customTab(CustomTabRobot.kt:115)
	at org.mozilla.focus.activity.CustomTabTest.customTabNavigationButtonsTest(CustomTabTest.kt:135)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5334269366706148686/executions/bs.f190b5f7e339cf2f/testcases/2)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.CustomTabRobot.verifyPageContent(CustomTabRobot.kt:83)
	at org.mozilla.focus.activity.CustomTabTest$customTabNavigationButtonsTest$1.invoke(CustomTabTest.kt:136)
	at org.mozilla.focus.activity.CustomTabTest$customTabNavigationButtonsTest$1.invoke(CustomTabTest.kt:135)
	at org.mozilla.focus.activity.robots.CustomTabRobotKt.customTab(CustomTabRobot.kt:115)
	at org.mozilla.focus.activity.CustomTabTest.customTabNavigationButtonsTest(CustomTabTest.kt:135)

**Comment by AndiAJ** [comment]
Flaky 1x in 10/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4624615460268646844/executions/bs.68225ad25bbcec16)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.CustomTabRobot.verifyPageContent(CustomTabRobot.kt:83)
	at org.mozilla.focus.activity.CustomTabTest$customTabNavigationButtonsTest$1.invoke(CustomTabTest.kt:136)
	at org.mozilla.focus.activity.CustomTabTest$customTabNavigationButtonsTest$1.invoke(CustomTabTest.kt:135)
	at org.mozilla.focus.activity.robots.CustomTabRobotKt.customTab(CustomTabRobot.kt:115)
	at org.mozilla.focus.activity.CustomTabTest.customTabNavigationButtonsTest(CustomTabTest.kt:135)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
