### ISSUE TITLE
Intermittent UI test failure - < AddToHomescreenTest. addPageToHomeScreenTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7670]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: for text= "hqKA2"
	at androidx.test.uiautomator.UiCollection.getChildByText(UiCollection.java:126)
	at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:215)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut$shortcut(AddToHomeScreenRobot.kt:46)
	at org.mozilla.focus.activity.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:47)
	at org.mozilla.focus.activity.AddToHomescreenTest.addPageToHomeScreenTest(AddToHomescreenTest.kt:66)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
