### ISSUE TITLE
Intermittent UI test failure - < testLocalAndSessionStorageIsWrittenAndRemoved. testLocalAndSessionStorageIsWrittenAndRemoved >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7672]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:55)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$testLocalAndSessionStorageIsWrittenAndRemoved$2.invoke(LocalSessionStorageTest.kt:65)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$testLocalAndSessionStorageIsWrittenAndRemoved$2.invoke(LocalSessionStorageTest.kt:63)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.privacy.LocalSessionStorageTest.testLocalAndSessionStorageIsWrittenAndRemoved(LocalSessionStorageTest.kt:63)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
