### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest. copyLinkAddressTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7680]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:55)
	at org.mozilla.focus.activity.ContextMenusTest$copyLinkAddressTest$2.invoke(ContextMenusTest.kt:104)
	at org.mozilla.focus.activity.ContextMenusTest$copyLinkAddressTest$2.invoke(ContextMenusTest.kt:103)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.ContextMenusTest.copyLinkAddressTest(ContextMenusTest.kt:103)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5573141444597224666/executions/bs.9341636566b521ab/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Tab 2]
	at androidx.test.uiautomator.UiObject.longClick(UiObject.java:528)
	at org.mozilla.focus.activity.robots.BrowserRobot.longPressLink(BrowserRobot.kt:117)
	at org.mozilla.focus.activity.ContextMenusTest$copyLinkAddressTest$2.invoke(ContextMenusTest.kt:105)
	at org.mozilla.focus.activity.ContextMenusTest$copyLinkAddressTest$2.invoke(ContextMenusTest.kt:103)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.ContextMenusTest.copyLinkAddressTest(ContextMenusTest.kt:103)
