### ISSUE TITLE
Compose views exit transitions cause crash.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/focus-android#7712]
When a fragment that contains a Compose view is dismissed following crash occurs:

`java.lang.UnsupportedOperationException: Cannot add views to ComposeView; only Compose content is supported`

<details>

```
java.lang.UnsupportedOperationException: Cannot add views to ComposeView; only Compose content is supported
    at androidx.compose.ui.platform.AbstractComposeView.checkAddView(ComposeView.android.kt:202)
    at androidx.compose.ui.platform.AbstractComposeView.addView(ComposeView.android.kt:346)
    at androidx.transition.TransitionUtils.createViewBitmap(TransitionUtils.java:138)
    at androidx.transition.TransitionUtils.copyViewImage(TransitionUtils.java:64)
    at androidx.transition.Visibility.onDisappear(Visibility.java:404)
    at androidx.transition.Visibility.createAnimator(Visibility.java:257)
    at androidx.transition.Transition.createAnimators(Transition.java:744)
    at androidx.transition.TransitionSet.createAnimators(TransitionSet.java:480)
    at androidx.transition.TransitionSet.createAnimators(TransitionSet.java:480)
    at androidx.transition.Transition.playTransition(Transition.java:1808)
    at androidx.transition.TransitionManager$MultiListener.onPreDraw(TransitionManager.java:300)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2745)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
    at android.view.Choreographer.doCallbacks(Choreographer.java:790)
    at android.view.Choreographer.doFrame(Choreographer.java:725)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

</details>

Besides the fix, we should also investigate what update / change has introduced this behavior.

**Comment by mcarare** [comment]
This is possibly a  bug in `androidx.transition`. On a fade animated transition, a `ViewGroup` is added to the `ComposeView`. It might be a problem only for fragments that only have a  `ComposeView` as a root view.

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 107.0a1 from 9/23 with the following devices:
* Samsung Galaxy Note 8 (Android 9),
* Xiaomi mi8 Lite (Android 10),
* HTC 10 (Android 8), and 
* Oppo Reno 6 (Android 12).
The app didn't crash after a clean install, or after the onboarding was dismissed.

**Comment by lobontiumira** [comment]
Verified on the latest Focus Nightly 107.0a1 from 10/3 with the following devices:
* Lenovo tablet M10 (Android 10),
* Xiaomi Mi8 Lite (Android 10), and
* Samsung Galaxy Tab A6 (Android 5.1.1).

Focus Nightly did not crash after dissmissing the onboarding, and browsing a few pages.
