### ISSUE TITLE
Intermittent UI test failure - < LocalSessionStorageTest.eraseCookiesTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7738]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=setCookies]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickSetCookiesButton(BrowserRobot.kt:432)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:88)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:86)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.privacy.LocalSessionStorageTest.eraseCookiesTest(LocalSessionStorageTest.kt:86)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6177875886863329764/executions/bs.8eb5527fc6e796e1/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=setCookies]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickSetCookiesButton(BrowserRobot.kt:451)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:88)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:86)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.privacy.LocalSessionStorageTest.eraseCookiesTest(LocalSessionStorageTest.kt:86)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6935821241770095571/executions/bs.9a601b013e6435f1/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=setCookies]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickSetCookiesButton(BrowserRobot.kt:512)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:88)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:86)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.privacy.LocalSessionStorageTest.eraseCookiesTest(LocalSessionStorageTest.kt:86)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5799304605837333543/executions/bs.7a8cc91db188e30b/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=setCookies]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickSetCookiesButton(BrowserRobot.kt:546)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:88)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:86)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.privacy.LocalSessionStorageTest.eraseCookiesTest(LocalSessionStorageTest.kt:86)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/3 [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8396834859214923863/executions/bs.fc5dbbbd7ca140d9/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=setCookies]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickSetCookiesButton(BrowserRobot.kt:546)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:88)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:86)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.privacy.LocalSessionStorageTest.eraseCookiesTest(LocalSessionStorageTest.kt:86)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7116449650622538788/executions/bs.8edf91685d4c7110/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=setCookies]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickSetCookiesButton(BrowserRobot.kt:546)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:88)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:86)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.privacy.LocalSessionStorageTest.eraseCookiesTest(LocalSessionStorageTest.kt:86)

**Comment by AndiAJ** [comment]
💥 Failed 1x on 10/4 Main 
[Fireabase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4668085402887524157/executions/bs.6d6e47c17d9e838f/testcases/1)
[Fireabase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4668085402887524157/executions/bs.e386bec9e7f8df8b/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=setCookies]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickSetCookiesButton(BrowserRobot.kt:546)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:88)
	at org.mozilla.focus.privacy.LocalSessionStorageTest$eraseCookiesTest$2.invoke(LocalSessionStorageTest.kt:86)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.privacy.LocalSessionStorageTest.eraseCookiesTest(LocalSessionStorageTest.kt:86)
