### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest.simpleImageContextMenuItemsTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7739]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=rabbit.jpg]
	at androidx.test.uiautomator.UiObject.longClick(UiObject.java:528)
	at org.mozilla.focus.activity.robots.BrowserRobot.longPressLink(BrowserRobot.kt:117)
	at org.mozilla.focus.activity.ContextMenusTest$simpleImageContextMenuItemsTest$2.invoke(ContextMenusTest.kt:77)
	at org.mozilla.focus.activity.ContextMenusTest$simpleImageContextMenuItemsTest$2.invoke(ContextMenusTest.kt:76)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.ContextMenusTest.simpleImageContextMenuItemsTest(ContextMenusTest.kt:76)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/26 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5285637253412688667/executions/bs.974471bd10c44ecb/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=rabbit.jpg]
	at androidx.test.uiautomator.UiObject.longClick(UiObject.java:528)
	at org.mozilla.focus.activity.robots.BrowserRobot.longPressLink(BrowserRobot.kt:117)
	at org.mozilla.focus.activity.ContextMenusTest$simpleImageContextMenuItemsTest$2.invoke(ContextMenusTest.kt:77)
	at org.mozilla.focus.activity.ContextMenusTest$simpleImageContextMenuItemsTest$2.invoke(ContextMenusTest.kt:76)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.ContextMenusTest.simpleImageContextMenuItemsTest(ContextMenusTest.kt:76)
