### ISSUE TITLE
Intermittent UI test failure - < MediaPlaybackTest. testMediaContentNotification >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7741]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Play]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickPlayButton(BrowserRobot.kt:149)
	at org.mozilla.focus.activity.MediaPlaybackTest$testMediaContentNotification$2.invoke(MediaPlaybackTest.kt:83)
	at org.mozilla.focus.activity.MediaPlaybackTest$testMediaContentNotification$2.invoke(MediaPlaybackTest.kt:82)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.MediaPlaybackTest.testMediaContentNotification(MediaPlaybackTest.kt:82)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5573141444597224666/executions/bs.22350690c6bb45a9/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Play]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickPlayButton(BrowserRobot.kt:149)
	at org.mozilla.focus.activity.MediaPlaybackTest$testMediaContentNotification$2.invoke(MediaPlaybackTest.kt:83)
	at org.mozilla.focus.activity.MediaPlaybackTest$testMediaContentNotification$2.invoke(MediaPlaybackTest.kt:82)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.MediaPlaybackTest.testMediaContentNotification(MediaPlaybackTest.kt:82)

**Comment by AndiAJ** [comment]
💥 Failed 1x on 9/28 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6186565533921821440/executions/bs.f52a6b620de851c3/testcases/2)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6186565533921821440/executions/bs.1b0547dfdb47336c/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Play]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickPlayButton(BrowserRobot.kt:169)
	at org.mozilla.focus.activity.MediaPlaybackTest$testMediaContentNotification$2.invoke(MediaPlaybackTest.kt:83)
	at org.mozilla.focus.activity.MediaPlaybackTest$testMediaContentNotification$2.invoke(MediaPlaybackTest.kt:82)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.activity.MediaPlaybackTest.testMediaContentNotification(MediaPlaybackTest.kt:82)
