### ISSUE TITLE
Intermittent UI test failure - DownloadFileTest tests - no download prompt

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7742]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$cancelDownloadTest$3.invoke(DownloadFileTest.kt:108)
	at org.mozilla.focus.activity.DownloadFileTest$cancelDownloadTest$3.invoke(DownloadFileTest.kt:107)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.cancelDownloadTest(DownloadFileTest.kt:107)

**Comment by sv-ohorvath** [comment]
[downloadAndOpenJpgFileTest ](https://github.com/mozilla-mobile/focus-android/issues/7755#top) Failing and flaky on Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5334714390137909699/executions/bs.7255971c946aae08/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:129)
at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:128)
at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
at org.mozilla.focus.activity.DownloadFileTest.downloadAndOpenJpgFileTest(DownloadFileTest.kt:128)

**Comment by sv-ohorvath** [comment]
[downloadNotificationTest ](https://github.com/mozilla-mobile/focus-android/issues/7790#top)
Failing and flaky on Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5334714390137909699/executions/bs.7255971c946aae08/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:129)
at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:128)
at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
at org.mozilla.focus.activity.DownloadFileTest.downloadAndOpenJpgFileTest(DownloadFileTest.kt:128)

**Comment by AndiAJ** [comment]
`downloadAndOpenJpgFileTest` flaky 1x on 10/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7207548450910006794/executions/bs.a251e6f0d23635c4)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:129)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:128)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.downloadAndOpenJpgFileTest(DownloadFileTest.kt:128)

**Comment by AndiAJ** [comment]
`downloadAndOpenJpgFileTest` flaky 1x on 10/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5986436099381615963/executions/bs.21ebb7245a82c39/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:129)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:128)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.downloadAndOpenJpgFileTest(DownloadFileTest.kt:128)

**Comment by sv-ohorvath** [comment]
Haven't failed. in a month, closing for now.
