### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest. verifyDropdownMenuTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7743]
### Stacktrace: 
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.Spinner, PACKAGE NAME=org.mozilla.focus.debug, RESOURCE_ID=dropDown]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickDropDownForm(BrowserRobot.kt:247)
	at org.mozilla.focus.activity.WebControlsTest$verifyDropdownMenuTest$2.invoke(WebControlsTest.kt:78)
	at org.mozilla.focus.activity.WebControlsTest$verifyDropdownMenuTest$2.invoke(WebControlsTest.kt:76)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyDropdownMenuTest(WebControlsTest.kt:76)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8239883098619511115/executions/bs.c75d17ce5a403b34/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.Spinner, PACKAGE NAME=org.mozilla.focus.debug, RESOURCE_ID=dropDown]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickDropDownForm(BrowserRobot.kt:247)
	at org.mozilla.focus.activity.WebControlsTest$verifyDropdownMenuTest$2.invoke(WebControlsTest.kt:78)
	at org.mozilla.focus.activity.WebControlsTest$verifyDropdownMenuTest$2.invoke(WebControlsTest.kt:76)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyDropdownMenuTest(WebControlsTest.kt:76)
