### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest.verifyExternalLinksTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7747]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=External link]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickLinkMatchingText(BrowserRobot.kt:221)
	at org.mozilla.focus.activity.WebControlsTest$verifyExternalLinksTest$2.invoke(WebControlsTest.kt:93)
	at org.mozilla.focus.activity.WebControlsTest$verifyExternalLinksTest$2.invoke(WebControlsTest.kt:91)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyExternalLinksTest(WebControlsTest.kt:91)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8239883098619511115/executions/bs.db665a911374513d/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=External link]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickLinkMatchingText(BrowserRobot.kt:221)
	at org.mozilla.focus.activity.WebControlsTest$verifyExternalLinksTest$2.invoke(WebControlsTest.kt:93)
	at org.mozilla.focus.activity.WebControlsTest$verifyExternalLinksTest$2.invoke(WebControlsTest.kt:91)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.WebControlsTest.verifyExternalLinksTest(WebControlsTest.kt:91)
