### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest.copyImageLocationTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7748]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=rabbit.jpg]
	at androidx.test.uiautomator.UiObject.longClick(UiObject.java:528)
	at org.mozilla.focus.activity.robots.BrowserRobot.longPressLink(BrowserRobot.kt:117)
	at org.mozilla.focus.activity.ContextMenusTest$copyImageLocationTest$2.invoke(ContextMenusTest.kt:140)
	at org.mozilla.focus.activity.ContextMenusTest$copyImageLocationTest$2.invoke(ContextMenusTest.kt:139)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.ContextMenusTest.copyImageLocationTest(ContextMenusTest.kt:139)

**Comment by AndiAJ** [comment]
💥 Failed 1x on 9/27 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8239883098619511115/executions/bs.38983a4c5c347c2a/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8239883098619511115/executions/bs.6cf79eb495ca6d75/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=rabbit.jpg]
	at androidx.test.uiautomator.UiObject.longClick(UiObject.java:528)
	at org.mozilla.focus.activity.robots.BrowserRobot.longPressLink(BrowserRobot.kt:117)
	at org.mozilla.focus.activity.ContextMenusTest$copyImageLocationTest$2.invoke(ContextMenusTest.kt:140)
	at org.mozilla.focus.activity.ContextMenusTest$copyImageLocationTest$2.invoke(ContextMenusTest.kt:139)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:97)
	at org.mozilla.focus.activity.ContextMenusTest.copyImageLocationTest(ContextMenusTest.kt:139)
