### ISSUE TITLE
Intermittent UI test failure - < DownloadFileTest. downloadAndOpenJpgFileTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7755]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:129)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:128)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.downloadAndOpenJpgFileTest(DownloadFileTest.kt:128)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6076968540444097718/executions/bs.c6bda1ffcb07af6c/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:129)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:128)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.downloadAndOpenJpgFileTest(DownloadFileTest.kt:128)

**Comment by AndiAJ** [comment]
💥 Failed 1x on 10/2 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4624615460268646844/executions/bs.869b6acde5af7db7/testcases/2)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4624615460268646844/executions/bs.f00f31320277d8c0/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:129)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:128)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.downloadAndOpenJpgFileTest(DownloadFileTest.kt:128)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/5334714390137909699/executions/bs.7255971c946aae08/testcases/2)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:129)
	at org.mozilla.focus.activity.DownloadFileTest$downloadAndOpenJpgFileTest$3.invoke(DownloadFileTest.kt:128)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.downloadAndOpenJpgFileTest(DownloadFileTest.kt:128)

**Comment by sv-ohorvath** [comment]
Caused by this issue: https://github.com/mozilla-mobile/focus-android/issues/7720
