### ISSUE TITLE
Intermittent UI test failure - < MediaPlaybackTest. testVideoPlayback >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7770]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Play]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickPlayButton(BrowserRobot.kt:169)
	at org.mozilla.focus.activity.MediaPlaybackTest$testVideoPlayback$2.invoke(MediaPlaybackTest.kt:50)
	at org.mozilla.focus.activity.MediaPlaybackTest$testVideoPlayback$2.invoke(MediaPlaybackTest.kt:49)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.activity.MediaPlaybackTest.testVideoPlayback(MediaPlaybackTest.kt:49)

**Comment by AndiAJ** [comment]
Closing, as we didn't encounter this failure in a while.
