### ISSUE TITLE
Intermittent UI test failure - < MediaPlaybackTest. testAudioPlayback >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7771]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Play]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.BrowserRobot.clickPlayButton(BrowserRobot.kt:169)
	at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:66)
	at org.mozilla.focus.activity.MediaPlaybackTest$testAudioPlayback$2.invoke(MediaPlaybackTest.kt:65)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.activity.MediaPlaybackTest.testAudioPlayback(MediaPlaybackTest.kt:65)

**Comment by AndiAJ** [comment]
Closing, as we didn't encounter this failure in a while.
