### ISSUE TITLE
Intermittent UI test failure - < DownloadFileTest. downloadNotificationTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7790]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$downloadNotificationTest$4.invoke(DownloadFileTest.kt:84)
	at org.mozilla.focus.activity.DownloadFileTest$downloadNotificationTest$4.invoke(DownloadFileTest.kt:83)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.downloadNotificationTest(DownloadFileTest.kt:83)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7114780811246456922/executions/bs.a6aea60d025e48cb/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=download]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.focus.activity.robots.DownloadRobot.clickDownloadIconAsset(DownloadRobot.kt:31)
	at org.mozilla.focus.activity.DownloadFileTest$downloadNotificationTest$4.invoke(DownloadFileTest.kt:84)
	at org.mozilla.focus.activity.DownloadFileTest$downloadNotificationTest$4.invoke(DownloadFileTest.kt:83)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.downloadNotificationTest(DownloadFileTest.kt:83)

**Comment by sv-ohorvath** [comment]
I believe it's caused by this issue: https://github.com/mozilla-mobile/focus-android/issues/7720
