### ISSUE TITLE
Investigate permanent UI test failure EnhancedTrackingProtectionSettingsTest

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/focus-android#7816]
blockSocialTrackersTest Firebase Test Lab Run (10/06): [here](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/8897732563285886389/executions/bs.259e90a0a82fa339/testcases/2/test-cases)

```Kotlin
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.focus.activity.robots.BrowserRobot.verifyTrackingProtectionAlert(BrowserRobot.kt:57)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$blockSocialTrackersTest$4.invoke(EnhancedTrackingProtectionSettingsTest.kt:180)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest$blockSocialTrackersTest$4.invoke(EnhancedTrackingProtectionSettingsTest.kt:179)
	at org.mozilla.focus.activity.robots.SearchRobot$Transition.loadPage(SearchRobot.kt:101)
	at org.mozilla.focus.activity.EnhancedTrackingProtectionSettingsTest.blockSocialTrackersTest(EnhancedTrackingProtectionSettingsTest.kt:179)
```

Based on testing locally, the alert never shows. Not sure if it's a JavaScript page logic issue or a change in social tracker blocking behaviour.

**Comment by rvandermeulen** [comment]
FWIW, I reran a previously-green job and it also started failing, which makes me suspect something external to us changed.

**Comment by AaronMT** [comment]
Social trackers: 
https://social-track-digest256.dummytracker.org/test_not_blocked.png
https://not-a-tracker.dummytracker.org/test_blocked.png

**Comment by AndiAJ** [comment]
Most likely caused by https://github.com/mozilla-mobile/focus-android/issues/7821

**Comment by sv-ohorvath** [comment]
Moving here the other ETP tests disabled for the same reason, so I can close the other issues as duplicates:
[blockOtherContentTrackersTest ](https://github.com/mozilla-mobile/focus-android/issues/7598)
[blockAdTrackersTest ](https://github.com/mozilla-mobile/focus-android/issues/7751)
[blockAnalyticsTrackersTest](https://github.com/mozilla-mobile/focus-android/issues/7167)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802607

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
