### ISSUE TITLE
Intermittent UI test failure - < OldFirstRunTest. firstRunOnboardingTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7834]
### Stacktrace:

```Kotlin
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362500, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@174701f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyOnboardingThirdSlide(HomeScreenRobot.kt:44)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:49)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:44)
	at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:134)
	at org.mozilla.focus.activity.OldFirstRunTest.firstRunOnboardingTest(OldFirstRunTest.kt:44)
	... 33 trimmed
Caused by: junit.framework.AssertionFailedError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362500, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@174701f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by AndiAJ** [comment]
Flaky 1x on 10/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6265034610629772000/executions/bs.1bf499c0ddc47117/testcases/1)

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362500, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@fb75f6c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyOnboardingThirdSlide(HomeScreenRobot.kt:44)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:49)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:44)
	at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:134)
	at org.mozilla.focus.activity.OldFirstRunTest.firstRunOnboardingTest(OldFirstRunTest.kt:44)
	... 33 trimmed
Caused by: junit.framework.AssertionFailedError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362500, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@fb75f6c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/4765666895610805762/executions/bs.2a1bf99ba1c68b01/testcases/2)

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362500, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@abb57be, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyOnboardingThirdSlide(HomeScreenRobot.kt:44)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:49)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:44)
	at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:134)
	at org.mozilla.focus.activity.OldFirstRunTest.firstRunOnboardingTest(OldFirstRunTest.kt:44)
	... 33 trimmed
Caused by: junit.framework.AssertionFailedError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362500, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@abb57be, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/6475690682274607911/executions/bs.9492536dbf944ed9/testcases/2)

androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362500, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:3)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyOnboardingThirdSlide(HomeScreenRobot.kt:44)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:49)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:44)
	at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:134)
	at org.mozilla.focus.activity.OldFirstRunTest.firstRunOnboardingTest(OldFirstRunTest.kt:44)
	... 34 trimmed
Caused by: junit.framework.AssertionFailedError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362500, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:7)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:14)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7484055792126150907/executions/bs.7411228b6b59f6d2/testcases/2)

androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362546, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:3)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyOnboardingThirdSlide(HomeScreenRobot.kt:44)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:49)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:44)
	at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:142)
	at org.mozilla.focus.activity.OldFirstRunTest.firstRunOnboardingTest(OldFirstRunTest.kt:44)
	... 34 trimmed
Caused by: junit.framework.AssertionFailedError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362546, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:7)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:14)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7912267850558433405/executions/bs.57222b93cc2f0737/testcases/2)

androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362546, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:3)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.focus.activity.robots.HomeScreenRobot.verifyOnboardingThirdSlide(HomeScreenRobot.kt:44)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:49)
	at org.mozilla.focus.activity.OldFirstRunTest$firstRunOnboardingTest$1.invoke(OldFirstRunTest.kt:44)
	at org.mozilla.focus.activity.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:142)
	at org.mozilla.focus.activity.OldFirstRunTest.firstRunOnboardingTest(OldFirstRunTest.kt:44)
	... 34 trimmed
Caused by: junit.framework.AssertionFailedError: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)' doesn't match the selected view.
Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() to return non-empty rectangle)
     Got: view.getGlobalVisibleRect() returned empty rectangle
View Details: AppCompatTextView{id=2131362546, res-name=title, visibility=VISIBLE, width=662, height=133, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=620.0, text=Add shortcuts to your home screen, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:7)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:14)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1802604

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
