### ISSUE TITLE
Intermittent UI test failure - < DownloadFileTest.verifyDownloadedFileOnStorageTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/focus-android#7887]
### Stacktrace:
java.lang.AssertionError: textfile(2).txt finished
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.focus.activity.robots.DownloadRobot.verifyDownloadConfirmationMessage(DownloadRobot.kt:51)
	at org.mozilla.focus.activity.DownloadFileTest$verifyDownloadedFileOnStorageTest$3.invoke(DownloadFileTest.kt:205)
	at org.mozilla.focus.activity.DownloadFileTest$verifyDownloadedFileOnStorageTest$3.invoke(DownloadFileTest.kt:202)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.verifyDownloadedFileOnStorageTest(DownloadFileTest.kt:202)

**Comment by AndiAJ** [comment]
Flaky 11/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-focus-android/testlab/histories/bh.2189b040bbce6d5a/matrices/7597818670778612449/executions/bs.c1b965d66d3bde50/testcases/2)

java.lang.AssertionError: textfile(2).txt finished
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.focus.activity.robots.DownloadRobot.verifyDownloadConfirmationMessage(DownloadRobot.kt:51)
	at org.mozilla.focus.activity.DownloadFileTest$verifyDownloadedFileOnStorageTest$3.invoke(DownloadFileTest.kt:205)
	at org.mozilla.focus.activity.DownloadFileTest$verifyDownloadedFileOnStorageTest$3.invoke(DownloadFileTest.kt:202)
	at org.mozilla.focus.activity.robots.DownloadRobotKt.downloadRobot(DownloadRobot.kt:67)
	at org.mozilla.focus.activity.DownloadFileTest.verifyDownloadedFileOnStorageTest(DownloadFileTest.kt:202)
