### ISSUE TITLE
Focus crashes when search engines are restored

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/focus-android#8054]
## Steps to reproduce
1. Go to Settings - Search - Search engines, and from the three-dot menu select the "Remove" option.
2. Remove some search engines.
3. From the three-sot menu, select the "Restore default search engines" option.

### Expected behavior
The search engines are restored without issues.

### Actual behavior
Focus crashes:
f110cc3b-3d1b-4801-b9ba-6638ad7cb4be
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isPressed()' on a null object reference

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isPressed()' on a null object reference
at org.mozilla.focus.search.RadioSearchEngineListPreference.onCheckedChanged(RadioSearchEngineListPreference.kt:10)
at android.widget.RadioGroup.setCheckedId(RadioGroup.java:196)
at android.widget.RadioGroup.addView(RadioGroup.java:157)
at android.view.ViewGroup.addView(ViewGroup.java:4967)
at org.mozilla.focus.search.SearchEngineListPreference.refreshSearchEngineViews(SearchEngineListPreference.kt:157)
at org.mozilla.focus.search.SearchEngineListPreference.onBindViewHolder(SearchEngineListPreference.kt:49)
at org.mozilla.focus.search.RadioSearchEngineListPreference.onBindViewHolder(RadioSearchEngineListPreference.kt:1)
at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:7)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:43)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1163)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:841)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:67)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:72)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:8)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:780)
at android.view.View.layout(View.java:22085)
at android.view.ViewGroup.layout(ViewGroup.java:6330)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3209)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2705)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1788)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7867)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
at android.view.Choreographer.doCallbacks(Choreographer.java:791)
at android.view.Choreographer.doFrame(Choreographer.java:726)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7399)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

### Device information
* Android devices: Lenovo tab M10 (Android 10), Google Pixel 6 (Android 13)
* Focus version: Beta 108.0b1, Nightly 109.0a1
* logcat [logcat (2).txt](https://github.com/mozilla-mobile/focus-android/files/10040762/logcat.2.txt)

**Comment by lobontiumira** [comment]
Verified as fixed on the latest Focus Nightly build 109.0a1 from 11/21, with Lenovo Tab M10 (Android 10), and Google Pizel 6 (Android 13).

**Comment by lobontiumira** [comment]
Verified as fixed also on Beta 108.0b3 with Google Pixel 6 (Android 13), and Lenovo tablet M10 (Android 10).
