### ISSUE TITLE
Fix 1.0 Top Crash

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/focus-android#812]
```
java.lang.RuntimeException: 
  at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3776)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: android.os.TransactionTooLargeException: 
  at android.os.BinderProxy.transactNative(Native Method:0)
  at android.os.BinderProxy.transact(Binder.java:615)
  at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3700)
  at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3768)
```

**Comment by Sdaswani** [comment]
Restricted to 7.x versions of Android

**Comment by pocmo** [comment]
That's #651 (It's not actually a "visible" crash).
