### ISSUE TITLE
NullPointerException: UrlInputFragment.dismiss()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/focus-android#853]
From Google Play.

Reports: 732
Impacted users: 662

```
java.lang.NullPointerException: 
  at org.mozilla.focus.fragment.UrlInputFragment.dismiss(UrlInputFragment.java:385)
  at org.mozilla.focus.fragment.UrlInputFragment.access$300(UrlInputFragment.java:37)
  at org.mozilla.focus.fragment.UrlInputFragment$4.onAnimationEnd(UrlInputFragment.java:348)
  at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1135)
  at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
  at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
  at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
```

**Comment by pocmo** [comment]
Another one in the same area:

Reports: 671
Impacted users: 567

```
java.lang.NullPointerException: 
  at org.mozilla.focus.fragment.UrlInputFragment.dismiss(UrlInputFragment.java:385)
  at org.mozilla.focus.fragment.UrlInputFragment.access$300(UrlInputFragment.java:37)
  at org.mozilla.focus.fragment.UrlInputFragment$4.onAnimationEnd(UrlInputFragment.java:348)
  at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)
  at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
  at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
  at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
```

**Comment by pocmo** [comment]
I can reproduce this by pressing "back" during the animation of the URL bar.

**Comment by pocmo** [comment]
Saw this one too (same STR):

```
                         E  FATAL EXCEPTION: main
                         E  Process: org.mozilla.focus.debug, PID: 29616
                         E  java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager android.support.v4.app.FragmentAc
                            tivity.getSupportFragmentManager()' on a null object reference
                         E      at org.mozilla.focus.fragment.UrlInputFragment.dismiss(UrlInputFragment.java:388)
                         E      at org.mozilla.focus.fragment.UrlInputFragment.access$300(UrlInputFragment.java:37)
                         E      at org.mozilla.focus.fragment.UrlInputFragment$3.onAnimationEnd(UrlInputFragment.java:285)
                         E      at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1122)
                         E      at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
                         E      at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
                         E      at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
                         E      at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:145)
                         E      at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
                         E      at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
                         E      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
                         E      at android.view.Choreographer.doCallbacks(Choreographer.java:698)
                         E      at android.view.Choreographer.doFrame(Choreographer.java:630)
                         E      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
                         E      at android.os.Handler.handleCallback(Handler.java:769)
                         E      at android.os.Handler.dispatchMessage(Handler.java:98)
                         E      at android.os.Looper.loop(Looper.java:164)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6541)
```

**Comment by pocmo** [comment]
Overall the animations can play multiple times at a time if you are fast and/or double tap. We should not initiate any more animations while we are still running one.
